nodes = \
{'_condition_0': {'num_fields': 0, 'type': 'condition'},
 '_condition_10': {'num_fields': 0, 'type': 'condition'},
 '_condition_11': {'num_fields': 0, 'type': 'condition'},
 '_condition_12': {'num_fields': 0, 'type': 'condition'},
 '_condition_13': {'num_fields': 0, 'type': 'condition'},
 '_condition_14': {'num_fields': 0, 'type': 'condition'},
 '_condition_15': {'num_fields': 0, 'type': 'condition'},
 '_condition_16': {'num_fields': 0, 'type': 'condition'},
 '_condition_17': {'num_fields': 0, 'type': 'condition'},
 '_condition_18': {'num_fields': 0, 'type': 'condition'},
 '_condition_19': {'num_fields': 0, 'type': 'condition'},
 '_condition_2': {'num_fields': 0, 'type': 'condition'},
 '_condition_21': {'num_fields': 0, 'type': 'condition'},
 '_condition_22': {'num_fields': 0, 'type': 'condition'},
 '_condition_23': {'num_fields': 0, 'type': 'condition'},
 '_condition_25': {'num_fields': 0, 'type': 'condition'},
 '_condition_26': {'num_fields': 0, 'type': 'condition'},
 '_condition_27': {'num_fields': 0, 'type': 'condition'},
 '_condition_29': {'num_fields': 0, 'type': 'condition'},
 '_condition_3': {'num_fields': 0, 'type': 'condition'},
 '_condition_30': {'num_fields': 0, 'type': 'condition'},
 '_condition_31': {'num_fields': 0, 'type': 'condition'},
 '_condition_32': {'num_fields': 0, 'type': 'condition'},
 '_condition_33': {'num_fields': 0, 'type': 'condition'},
 '_condition_34': {'num_fields': 0, 'type': 'condition'},
 '_condition_35': {'num_fields': 0, 'type': 'condition'},
 '_condition_36': {'num_fields': 0, 'type': 'condition'},
 '_condition_37': {'num_fields': 0, 'type': 'condition'},
 '_condition_38': {'num_fields': 0, 'type': 'condition'},
 '_condition_39': {'num_fields': 0, 'type': 'condition'},
 '_condition_4': {'num_fields': 0, 'type': 'condition'},
 '_condition_40': {'num_fields': 0, 'type': 'condition'},
 '_condition_5': {'num_fields': 0, 'type': 'condition'},
 '_condition_6': {'num_fields': 0, 'type': 'condition'},
 '_condition_7': {'num_fields': 0, 'type': 'condition'},
 '_condition_8': {'num_fields': 0, 'type': 'condition'},
 '_condition_9': {'num_fields': 0, 'type': 'condition'},
 'acl_stats_ACTION': {'num_fields': 1, 'type': 'action'},
 'adjust_lkp_fields_ACTION': {'num_fields': 8, 'type': 'action'},
 'adjust_lkp_fields_MATCH': {'key_width': 2, 'type': 'match'},
 'bd_flood_ACTION': {'num_fields': 1, 'type': 'action'},
 'bd_flood_MATCH': {'key_width': 19, 'type': 'match'},
 'compute_ipv4_hashes_ACTION': {'num_fields': 2, 'type': 'action'},
 'compute_ipv4_hashes_MATCH': {'key_width': 1, 'type': 'match'},
 'compute_non_ip_hashes_ACTION': {'num_fields': 1, 'type': 'action'},
 'compute_non_ip_hashes_MATCH': {'key_width': 1, 'type': 'match'},
 'compute_other_hashes_ACTION': {'num_fields': 3, 'type': 'action'},
 'compute_other_hashes_MATCH': {'key_width': 16, 'type': 'match'},
 'dmac_ACTION': {'num_fields': 3, 'type': 'action'},
 'dmac_MATCH': {'key_width': 64, 'type': 'match'},
 'drop_stats_ACTION': {'num_fields': 1, 'type': 'action'},
 'ecmp_group_ACTION': {'num_fields': 5, 'type': 'action'},
 'ecmp_group_MATCH': {'key_width': 16, 'type': 'match'},
 'fabric_ingress_dst_lkp_ACTION': {'num_fields': 10, 'type': 'action'},
 'fabric_ingress_dst_lkp_MATCH': {'key_width': 8, 'type': 'match'},
 'fabric_ingress_src_lkp_ACTION': {'num_fields': 0, 'type': 'action'},
 'fabric_ingress_src_lkp_MATCH': {'key_width': 16, 'type': 'match'},
 'fabric_lag_ACTION': {'num_fields': 1, 'type': 'action'},
 'fabric_lag_MATCH': {'key_width': 8, 'type': 'match'},
 'fwd_result_ACTION': {'num_fields': 6, 'type': 'action'},
 'fwd_result_MATCH': {'key_width': 33, 'type': 'match'},
 'ingress_bd_stats_ACTION': {'num_fields': 1, 'type': 'action'},
 'ingress_l4_dst_port_ACTION': {'num_fields': 1, 'type': 'action'},
 'ingress_l4_dst_port_MATCH': {'key_width': 16, 'type': 'match'},
 'ingress_l4_src_port_ACTION': {'num_fields': 1, 'type': 'action'},
 'ingress_l4_src_port_MATCH': {'key_width': 16, 'type': 'match'},
 'ingress_port_mapping_ACTION': {'num_fields': 2, 'type': 'action'},
 'ingress_port_mapping_MATCH': {'key_width': 9, 'type': 'match'},
 'ingress_port_properties_ACTION': {'num_fields': 7, 'type': 'action'},
 'ingress_port_properties_MATCH': {'key_width': 9, 'type': 'match'},
 'ingress_qos_map_dscp_ACTION': {'num_fields': 2, 'type': 'action'},
 'ingress_qos_map_dscp_MATCH': {'key_width': 13, 'type': 'match'},
 'ingress_qos_map_pcp_ACTION': {'num_fields': 2, 'type': 'action'},
 'ingress_qos_map_pcp_MATCH': {'key_width': 8, 'type': 'match'},
 'ip_acl_ACTION': {'num_fields': 10, 'type': 'action'},
 'ip_acl_MATCH': {'key_width': 136, 'type': 'match'},
 'ipsg_ACTION': {'num_fields': 0, 'type': 'action'},
 'ipsg_MATCH': {'key_width': 112, 'type': 'match'},
 'ipsg_permit_special_ACTION': {'num_fields': 1, 'type': 'action'},
 'ipsg_permit_special_MATCH': {'key_width': 56, 'type': 'match'},
 'ipv4_fib_ACTION': {'num_fields': 3, 'type': 'action'},
 'ipv4_fib_MATCH': {'key_width': 48, 'type': 'match'},
 'ipv4_fib_lpm_ACTION': {'num_fields': 3, 'type': 'action'},
 'ipv4_fib_lpm_MATCH': {'key_width': 48, 'type': 'match'},
 'ipv4_multicast_bridge_ACTION': {'num_fields': 2, 'type': 'action'},
 'ipv4_multicast_bridge_MATCH': {'key_width': 80, 'type': 'match'},
 'ipv4_multicast_bridge_star_g_ACTION': {'num_fields': 2, 'type': 'action'},
 'ipv4_multicast_bridge_star_g_MATCH': {'key_width': 48, 'type': 'match'},
 'ipv4_multicast_route_ACTION': {'num_fields': 4, 'type': 'action'},
 'ipv4_multicast_route_MATCH': {'key_width': 80, 'type': 'match'},
 'ipv4_multicast_route_star_g_ACTION': {'num_fields': 4, 'type': 'action'},
 'ipv4_multicast_route_star_g_MATCH': {'key_width': 48, 'type': 'match'},
 'ipv4_racl_ACTION': {'num_fields': 8, 'type': 'action'},
 'ipv4_racl_MATCH': {'key_width': 104, 'type': 'match'},
 'ipv4_urpf_ACTION': {'num_fields': 3, 'type': 'action'},
 'ipv4_urpf_MATCH': {'key_width': 48, 'type': 'match'},
 'ipv4_urpf_lpm_ACTION': {'num_fields': 3, 'type': 'action'},
 'ipv4_urpf_lpm_MATCH': {'key_width': 48, 'type': 'match'},
 'lag_group_ACTION': {'num_fields': 2, 'type': 'action'},
 'lag_group_MATCH': {'key_width': 16, 'type': 'match'},
 'learn_notify_ACTION': {'num_fields': 1, 'type': 'action'},
 'learn_notify_MATCH': {'key_width': 20, 'type': 'match'},
 'mac_acl_ACTION': {'num_fields': 10, 'type': 'action'},
 'mac_acl_MATCH': {'key_width': 144, 'type': 'match'},
 'meter_action_ACTION': {'num_fields': 1, 'type': 'action'},
 'meter_action_MATCH': {'key_width': 18, 'type': 'match'},
 'meter_index_ACTION': {'num_fields': 0, 'type': 'action'},
 'meter_index_MATCH': {'key_width': 16, 'type': 'match'},
 'nat_dst_ACTION': {'num_fields': 4, 'type': 'action'},
 'nat_dst_MATCH': {'key_width': 72, 'type': 'match'},
 'nat_flow_ACTION': {'num_fields': 4, 'type': 'action'},
 'nat_flow_MATCH': {'key_width': 120, 'type': 'match'},
 'nat_src_ACTION': {'num_fields': 1, 'type': 'action'},
 'nat_src_MATCH': {'key_width': 72, 'type': 'match'},
 'nat_twice_ACTION': {'num_fields': 4, 'type': 'action'},
 'nat_twice_MATCH': {'key_width': 120, 'type': 'match'},
 'native_packet_over_fabric_ACTION': {'num_fields': 7, 'type': 'action'},
 'native_packet_over_fabric_MATCH': {'key_width': 2, 'type': 'match'},
 'nexthop_ACTION': {'num_fields': 4, 'type': 'action'},
 'nexthop_MATCH': {'key_width': 16, 'type': 'match'},
 'port_vlan_mapping_ACTION': {'num_fields': 21, 'type': 'action'},
 'port_vlan_mapping_MATCH': {'key_width': 42, 'type': 'match'},
 'rmac_ACTION': {'num_fields': 1, 'type': 'action'},
 'rmac_MATCH': {'key_width': 58, 'type': 'match'},
 'smac_ACTION': {'num_fields': 1, 'type': 'action'},
 'smac_MATCH': {'key_width': 64, 'type': 'match'},
 'spanning_tree_ACTION': {'num_fields': 1, 'type': 'action'},
 'spanning_tree_MATCH': {'key_width': 26, 'type': 'match'},
 'storm_control_ACTION': {'num_fields': 2, 'type': 'action'},
 'storm_control_MATCH': {'key_width': 12, 'type': 'match'},
 'storm_control_stats_ACTION': {'num_fields': 0, 'type': 'action'},
 'storm_control_stats_MATCH': {'key_width': 11, 'type': 'match'},
 'switch_config_params_ACTION': {'num_fields': 5, 'type': 'action'},
 'switch_config_params_MATCH': {'key_width': 1, 'type': 'match'},
 'system_acl_ACTION': {'num_fields': 7, 'type': 'action'},
 'system_acl_MATCH': {'key_width': 153, 'type': 'match'},
 'traffic_class_ACTION': {'num_fields': 2, 'type': 'action'},
 'traffic_class_MATCH': {'key_width': 13, 'type': 'match'},
 'urpf_bd_ACTION': {'num_fields': 1, 'type': 'action'},
 'urpf_bd_MATCH': {'key_width': 32, 'type': 'match'},
 'validate_outer_ethernet_ACTION': {'num_fields': 3, 'type': 'action'},
 'validate_outer_ethernet_MATCH': {'key_width': 98, 'type': 'match'},
 'validate_outer_ipv4_packet_ACTION': {'num_fields': 3, 'type': 'action'},
 'validate_outer_ipv4_packet_MATCH': {'key_width': 20, 'type': 'match'},
 'validate_packet_ACTION': {'num_fields': 3, 'type': 'action'},
 'validate_packet_MATCH': {'key_width': 118, 'type': 'match'}}

edges = \
{('_condition_0', 'validate_outer_ipv4_packet_ACTION'): {'delay': 0,
                                                         'dep_type': 'rmt_successor'},
 ('_condition_10', 'native_packet_over_fabric_ACTION'): {'delay': 0,
                                                         'dep_type': 'rmt_successor'},
 ('_condition_11', 'storm_control_ACTION'): {'delay': 0,
                                             'dep_type': 'rmt_successor'},
 ('_condition_12', '_condition_13'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_12', '_condition_14'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_12', '_condition_15'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_12', '_condition_16'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_12', 'ingress_l4_dst_port_ACTION'): {'delay': 0,
                                                   'dep_type': 'rmt_successor'},
 ('_condition_12', 'ingress_l4_src_port_ACTION'): {'delay': 0,
                                                   'dep_type': 'rmt_successor'},
 ('_condition_12', 'nat_twice_ACTION'): {'delay': 0,
                                         'dep_type': 'rmt_successor'},
 ('_condition_12', 'rmac_ACTION'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_13', 'fwd_result_ACTION'): {'delay': 0,
                                          'dep_type': 'rmt_reverse_read'},
 ('_condition_13', 'validate_packet_ACTION'): {'delay': 0,
                                               'dep_type': 'rmt_successor'},
 ('_condition_14', 'smac_ACTION'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_15', 'dmac_ACTION'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_16', '_condition_17'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_16', '_condition_18'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_17', 'mac_acl_ACTION'): {'delay': 0,
                                       'dep_type': 'rmt_successor'},
 ('_condition_18', '_condition_19'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_19', 'ip_acl_ACTION'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_2', 'spanning_tree_ACTION'): {'delay': 0,
                                            'dep_type': 'rmt_successor'},
 ('_condition_21', '_condition_22'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_21', '_condition_23'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_22', 'ipv4_multicast_bridge_ACTION'): {'delay': 0,
                                                     'dep_type': 'rmt_successor'},
 ('_condition_23', 'ipv4_multicast_route_ACTION'): {'delay': 0,
                                                    'dep_type': 'rmt_successor'},
 ('_condition_25', '_condition_26'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_25', '_condition_29'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_26', '_condition_27'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_26', 'ipv4_fib_ACTION'): {'delay': 0,
                                        'dep_type': 'rmt_successor'},
 ('_condition_26', 'ipv4_racl_ACTION'): {'delay': 0,
                                         'dep_type': 'rmt_successor'},
 ('_condition_27', 'ipv4_urpf_ACTION'): {'delay': 0,
                                         'dep_type': 'rmt_successor'},
 ('_condition_29', 'urpf_bd_ACTION'): {'delay': 0,
                                       'dep_type': 'rmt_successor'},
 ('_condition_3', '_condition_4'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_30', 'meter_index_ACTION'): {'delay': 0,
                                           'dep_type': 'rmt_successor'},
 ('_condition_31', 'compute_ipv4_hashes_ACTION'): {'delay': 0,
                                                   'dep_type': 'rmt_successor'},
 ('_condition_31', 'compute_non_ip_hashes_ACTION'): {'delay': 0,
                                                     'dep_type': 'rmt_successor'},
 ('_condition_32', 'meter_action_ACTION'): {'delay': 0,
                                            'dep_type': 'rmt_successor'},
 ('_condition_33', '_condition_34'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_33', '_condition_35'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_33', '_condition_36'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_33', '_condition_37'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_33', 'acl_stats_ACTION'): {'delay': 0,
                                         'dep_type': 'rmt_successor'},
 ('_condition_33', 'ingress_bd_stats_ACTION'): {'delay': 0,
                                                'dep_type': 'rmt_successor'},
 ('_condition_33', 'storm_control_stats_ACTION'): {'delay': 0,
                                                   'dep_type': 'rmt_successor'},
 ('_condition_34', 'fwd_result_ACTION'): {'delay': 0,
                                          'dep_type': 'rmt_successor'},
 ('_condition_35', 'ecmp_group_ACTION'): {'delay': 0,
                                          'dep_type': 'rmt_successor'},
 ('_condition_35', 'nexthop_ACTION'): {'delay': 0,
                                       'dep_type': 'rmt_successor'},
 ('_condition_36', 'bd_flood_ACTION'): {'delay': 0,
                                        'dep_type': 'rmt_successor'},
 ('_condition_36', 'lag_group_ACTION'): {'delay': 0,
                                         'dep_type': 'rmt_successor'},
 ('_condition_37', 'learn_notify_ACTION'): {'delay': 0,
                                            'dep_type': 'rmt_successor'},
 ('_condition_38', '_condition_39'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_39', '_condition_40'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_39', 'system_acl_ACTION'): {'delay': 0,
                                          'dep_type': 'rmt_successor'},
 ('_condition_4', '_condition_5'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_4', 'ingress_qos_map_dscp_ACTION'): {'delay': 0,
                                                   'dep_type': 'rmt_successor'},
 ('_condition_40', 'drop_stats_ACTION'): {'delay': 0,
                                          'dep_type': 'rmt_successor'},
 ('_condition_5', 'ingress_qos_map_pcp_ACTION'): {'delay': 0,
                                                  'dep_type': 'rmt_successor'},
 ('_condition_6', 'ipsg_ACTION'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_6', 'ipsg_permit_special_ACTION'): {'delay': 0,
                                                  'dep_type': 'rmt_successor'},
 ('_condition_7', '_condition_8'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_7', 'fabric_ingress_dst_lkp_ACTION'): {'delay': 0,
                                                     'dep_type': 'rmt_successor'},
 ('_condition_8', '_condition_10'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_8', '_condition_9'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_9', 'fabric_ingress_src_lkp_ACTION'): {'delay': 0,
                                                     'dep_type': 'rmt_successor'},
 ('adjust_lkp_fields_ACTION', 'compute_ipv4_hashes_ACTION'): {'delay': 1,
                                                              'dep_type': 'rmt_action'},
 ('adjust_lkp_fields_ACTION', 'compute_non_ip_hashes_ACTION'): {'delay': 1,
                                                                'dep_type': 'rmt_action'},
 ('adjust_lkp_fields_ACTION', 'dmac_MATCH'): {'delay': 1,
                                              'dep_type': 'rmt_match'},
 ('adjust_lkp_fields_ACTION', 'ingress_l4_dst_port_MATCH'): {'delay': 1,
                                                             'dep_type': 'rmt_match'},
 ('adjust_lkp_fields_ACTION', 'ingress_l4_src_port_MATCH'): {'delay': 1,
                                                             'dep_type': 'rmt_match'},
 ('adjust_lkp_fields_ACTION', 'ip_acl_MATCH'): {'delay': 1,
                                                'dep_type': 'rmt_match'},
 ('adjust_lkp_fields_ACTION', 'ipsg_MATCH'): {'delay': 1,
                                              'dep_type': 'rmt_match'},
 ('adjust_lkp_fields_ACTION', 'ipsg_permit_special_MATCH'): {'delay': 1,
                                                             'dep_type': 'rmt_match'},
 ('adjust_lkp_fields_ACTION', 'ipv4_fib_MATCH'): {'delay': 1,
                                                  'dep_type': 'rmt_match'},
 ('adjust_lkp_fields_ACTION', 'ipv4_fib_lpm_MATCH'): {'delay': 1,
                                                      'dep_type': 'rmt_match'},
 ('adjust_lkp_fields_ACTION', 'ipv4_multicast_bridge_MATCH'): {'delay': 1,
                                                               'dep_type': 'rmt_match'},
 ('adjust_lkp_fields_ACTION', 'ipv4_multicast_bridge_star_g_MATCH'): {'delay': 1,
                                                                      'dep_type': 'rmt_match'},
 ('adjust_lkp_fields_ACTION', 'ipv4_multicast_route_MATCH'): {'delay': 1,
                                                              'dep_type': 'rmt_match'},
 ('adjust_lkp_fields_ACTION', 'ipv4_multicast_route_star_g_MATCH'): {'delay': 1,
                                                                     'dep_type': 'rmt_match'},
 ('adjust_lkp_fields_ACTION', 'ipv4_racl_MATCH'): {'delay': 1,
                                                   'dep_type': 'rmt_match'},
 ('adjust_lkp_fields_ACTION', 'ipv4_urpf_MATCH'): {'delay': 1,
                                                   'dep_type': 'rmt_match'},
 ('adjust_lkp_fields_ACTION', 'ipv4_urpf_lpm_MATCH'): {'delay': 1,
                                                       'dep_type': 'rmt_match'},
 ('adjust_lkp_fields_ACTION', 'learn_notify_ACTION'): {'delay': 1,
                                                       'dep_type': 'rmt_action'},
 ('adjust_lkp_fields_ACTION', 'mac_acl_MATCH'): {'delay': 1,
                                                 'dep_type': 'rmt_match'},
 ('adjust_lkp_fields_ACTION', 'nat_dst_MATCH'): {'delay': 1,
                                                 'dep_type': 'rmt_match'},
 ('adjust_lkp_fields_ACTION', 'nat_flow_MATCH'): {'delay': 1,
                                                  'dep_type': 'rmt_match'},
 ('adjust_lkp_fields_ACTION', 'nat_src_MATCH'): {'delay': 1,
                                                 'dep_type': 'rmt_match'},
 ('adjust_lkp_fields_ACTION', 'nat_twice_MATCH'): {'delay': 1,
                                                   'dep_type': 'rmt_match'},
 ('adjust_lkp_fields_ACTION', 'native_packet_over_fabric_ACTION'): {'delay': 1,
                                                                    'dep_type': 'rmt_action'},
 ('adjust_lkp_fields_ACTION', 'rmac_MATCH'): {'delay': 1,
                                              'dep_type': 'rmt_match'},
 ('adjust_lkp_fields_ACTION', 'smac_MATCH'): {'delay': 1,
                                              'dep_type': 'rmt_match'},
 ('adjust_lkp_fields_ACTION', 'system_acl_MATCH'): {'delay': 1,
                                                    'dep_type': 'rmt_match'},
 ('adjust_lkp_fields_ACTION', 'validate_packet_MATCH'): {'delay': 1,
                                                         'dep_type': 'rmt_match'},
 ('adjust_lkp_fields_MATCH', 'adjust_lkp_fields_ACTION'): {'delay': 9,
                                                           'dep_type': 'new_match_to_action'},
 ('bd_flood_ACTION', 'fabric_lag_ACTION'): {'delay': 1,
                                            'dep_type': 'rmt_action'},
 ('bd_flood_MATCH', 'bd_flood_ACTION'): {'delay': 9,
                                         'dep_type': 'new_match_to_action'},
 ('compute_ipv4_hashes_ACTION', 'compute_other_hashes_MATCH'): {'delay': 1,
                                                                'dep_type': 'rmt_match'},
 ('compute_ipv4_hashes_ACTION', 'ecmp_group_MATCH'): {'delay': 1,
                                                      'dep_type': 'rmt_match'},
 ('compute_ipv4_hashes_ACTION', 'fabric_lag_MATCH'): {'delay': 1,
                                                      'dep_type': 'rmt_match'},
 ('compute_ipv4_hashes_ACTION', 'fwd_result_ACTION'): {'delay': 0,
                                                       'dep_type': 'rmt_reverse_read'},
 ('compute_ipv4_hashes_ACTION', 'lag_group_MATCH'): {'delay': 1,
                                                     'dep_type': 'rmt_match'},
 ('compute_ipv4_hashes_MATCH', 'compute_ipv4_hashes_ACTION'): {'delay': 9,
                                                               'dep_type': 'new_match_to_action'},
 ('compute_non_ip_hashes_ACTION', 'compute_other_hashes_ACTION'): {'delay': 1,
                                                                   'dep_type': 'rmt_action'},
 ('compute_non_ip_hashes_ACTION', 'fabric_lag_MATCH'): {'delay': 1,
                                                        'dep_type': 'rmt_match'},
 ('compute_non_ip_hashes_ACTION', 'fwd_result_ACTION'): {'delay': 0,
                                                         'dep_type': 'rmt_reverse_read'},
 ('compute_non_ip_hashes_ACTION', 'lag_group_MATCH'): {'delay': 1,
                                                       'dep_type': 'rmt_match'},
 ('compute_non_ip_hashes_MATCH', 'compute_non_ip_hashes_ACTION'): {'delay': 9,
                                                                   'dep_type': 'new_match_to_action'},
 ('compute_other_hashes_ACTION', 'ecmp_group_MATCH'): {'delay': 1,
                                                       'dep_type': 'rmt_match'},
 ('compute_other_hashes_MATCH', 'compute_other_hashes_ACTION'): {'delay': 9,
                                                                 'dep_type': 'new_match_to_action'},
 ('dmac_ACTION', '_condition_36'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('dmac_ACTION', 'bd_flood_ACTION'): {'delay': 1, 'dep_type': 'rmt_action'},
 ('dmac_ACTION', 'ecmp_group_ACTION'): {'delay': 1, 'dep_type': 'rmt_action'},
 ('dmac_ACTION', 'fabric_lag_MATCH'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('dmac_ACTION', 'fwd_result_MATCH'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('dmac_ACTION', 'lag_group_MATCH'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('dmac_ACTION', 'nexthop_ACTION'): {'delay': 1, 'dep_type': 'rmt_action'},
 ('dmac_ACTION', 'system_acl_MATCH'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('dmac_MATCH', 'dmac_ACTION'): {'delay': 9,
                                 'dep_type': 'new_match_to_action'},
 ('ecmp_group_ACTION', '_condition_36'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('ecmp_group_ACTION', 'bd_flood_ACTION'): {'delay': 1,
                                            'dep_type': 'rmt_action'},
 ('ecmp_group_ACTION', 'fabric_lag_MATCH'): {'delay': 1,
                                             'dep_type': 'rmt_match'},
 ('ecmp_group_ACTION', 'lag_group_MATCH'): {'delay': 1,
                                            'dep_type': 'rmt_match'},
 ('ecmp_group_ACTION', 'system_acl_MATCH'): {'delay': 1,
                                             'dep_type': 'rmt_match'},
 ('ecmp_group_MATCH', 'ecmp_group_ACTION'): {'delay': 9,
                                             'dep_type': 'new_match_to_action'},
 ('fabric_ingress_dst_lkp_ACTION', '_condition_10'): {'delay': 1,
                                                      'dep_type': 'rmt_match'},
 ('fabric_ingress_dst_lkp_ACTION', '_condition_31'): {'delay': 1,
                                                      'dep_type': 'rmt_match'},
 ('fabric_ingress_dst_lkp_ACTION', '_condition_9'): {'delay': 1,
                                                     'dep_type': 'rmt_match'},
 ('fabric_ingress_dst_lkp_ACTION', 'bd_flood_ACTION'): {'delay': 1,
                                                        'dep_type': 'rmt_action'},
 ('fabric_ingress_dst_lkp_ACTION', 'dmac_ACTION'): {'delay': 1,
                                                    'dep_type': 'rmt_action'},
 ('fabric_ingress_dst_lkp_ACTION', 'ecmp_group_MATCH'): {'delay': 1,
                                                         'dep_type': 'rmt_match'},
 ('fabric_ingress_dst_lkp_ACTION', 'fabric_ingress_src_lkp_MATCH'): {'delay': 1,
                                                                     'dep_type': 'rmt_match'},
 ('fabric_ingress_dst_lkp_ACTION', 'fabric_lag_MATCH'): {'delay': 1,
                                                         'dep_type': 'rmt_match'},
 ('fabric_ingress_dst_lkp_ACTION', 'fwd_result_ACTION'): {'delay': 1,
                                                          'dep_type': 'rmt_action'},
 ('fabric_ingress_dst_lkp_ACTION', 'lag_group_ACTION'): {'delay': 1,
                                                         'dep_type': 'rmt_action'},
 ('fabric_ingress_dst_lkp_ACTION', 'native_packet_over_fabric_ACTION'): {'delay': 1,
                                                                         'dep_type': 'rmt_action'},
 ('fabric_ingress_dst_lkp_ACTION', 'nexthop_MATCH'): {'delay': 1,
                                                      'dep_type': 'rmt_match'},
 ('fabric_ingress_dst_lkp_ACTION', 'system_acl_MATCH'): {'delay': 1,
                                                         'dep_type': 'rmt_match'},
 ('fabric_ingress_dst_lkp_MATCH', 'fabric_ingress_dst_lkp_ACTION'): {'delay': 9,
                                                                     'dep_type': 'new_match_to_action'},
 ('fabric_ingress_src_lkp_MATCH', 'fabric_ingress_src_lkp_ACTION'): {'delay': 9,
                                                                     'dep_type': 'new_match_to_action'},
 ('fabric_lag_ACTION', 'system_acl_ACTION'): {'delay': 0,
                                              'dep_type': 'rmt_reverse_read'},
 ('fabric_lag_MATCH', 'fabric_lag_ACTION'): {'delay': 9,
                                             'dep_type': 'new_match_to_action'},
 ('fwd_result_ACTION', '_condition_35'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('fwd_result_ACTION', '_condition_36'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('fwd_result_ACTION', '_condition_40'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('fwd_result_ACTION', 'bd_flood_ACTION'): {'delay': 1,
                                            'dep_type': 'rmt_action'},
 ('fwd_result_ACTION', 'drop_stats_ACTION'): {'delay': 1,
                                              'dep_type': 'rmt_action'},
 ('fwd_result_ACTION', 'ecmp_group_MATCH'): {'delay': 1,
                                             'dep_type': 'rmt_match'},
 ('fwd_result_ACTION', 'fabric_lag_MATCH'): {'delay': 1,
                                             'dep_type': 'rmt_match'},
 ('fwd_result_ACTION', 'lag_group_MATCH'): {'delay': 1,
                                            'dep_type': 'rmt_match'},
 ('fwd_result_ACTION', 'nexthop_MATCH'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('fwd_result_ACTION', 'system_acl_MATCH'): {'delay': 1,
                                             'dep_type': 'rmt_match'},
 ('fwd_result_MATCH', 'fwd_result_ACTION'): {'delay': 9,
                                             'dep_type': 'new_match_to_action'},
 ('ingress_l4_dst_port_ACTION', 'ip_acl_MATCH'): {'delay': 1,
                                                  'dep_type': 'rmt_match'},
 ('ingress_l4_dst_port_ACTION', 'ipv4_racl_MATCH'): {'delay': 1,
                                                     'dep_type': 'rmt_match'},
 ('ingress_l4_dst_port_MATCH', 'ingress_l4_dst_port_ACTION'): {'delay': 9,
                                                               'dep_type': 'new_match_to_action'},
 ('ingress_l4_src_port_ACTION', 'ip_acl_MATCH'): {'delay': 1,
                                                  'dep_type': 'rmt_match'},
 ('ingress_l4_src_port_ACTION', 'ipv4_racl_MATCH'): {'delay': 1,
                                                     'dep_type': 'rmt_match'},
 ('ingress_l4_src_port_MATCH', 'ingress_l4_src_port_ACTION'): {'delay': 9,
                                                               'dep_type': 'new_match_to_action'},
 ('ingress_port_mapping_ACTION', '_condition_11'): {'delay': 1,
                                                    'dep_type': 'rmt_match'},
 ('ingress_port_mapping_ACTION', '_condition_12'): {'delay': 1,
                                                    'dep_type': 'rmt_match'},
 ('ingress_port_mapping_ACTION', '_condition_14'): {'delay': 1,
                                                    'dep_type': 'rmt_match'},
 ('ingress_port_mapping_ACTION', '_condition_2'): {'delay': 1,
                                                   'dep_type': 'rmt_match'},
 ('ingress_port_mapping_ACTION', '_condition_33'): {'delay': 1,
                                                    'dep_type': 'rmt_match'},
 ('ingress_port_mapping_ACTION', '_condition_38'): {'delay': 1,
                                                    'dep_type': 'rmt_match'},
 ('ingress_port_mapping_ACTION', '_condition_6'): {'delay': 1,
                                                   'dep_type': 'rmt_match'},
 ('ingress_port_mapping_ACTION', '_condition_7'): {'delay': 1,
                                                   'dep_type': 'rmt_match'},
 ('ingress_port_mapping_ACTION', '_condition_8'): {'delay': 1,
                                                   'dep_type': 'rmt_match'},
 ('ingress_port_mapping_ACTION', 'compute_non_ip_hashes_ACTION'): {'delay': 1,
                                                                   'dep_type': 'rmt_action'},
 ('ingress_port_mapping_ACTION', 'ipsg_MATCH'): {'delay': 1,
                                                 'dep_type': 'rmt_match'},
 ('ingress_port_mapping_ACTION', 'learn_notify_ACTION'): {'delay': 1,
                                                          'dep_type': 'rmt_action'},
 ('ingress_port_mapping_ACTION', 'port_vlan_mapping_MATCH'): {'delay': 1,
                                                              'dep_type': 'rmt_match'},
 ('ingress_port_mapping_ACTION', 'smac_ACTION'): {'delay': 1,
                                                  'dep_type': 'rmt_action'},
 ('ingress_port_mapping_ACTION', 'spanning_tree_MATCH'): {'delay': 1,
                                                          'dep_type': 'rmt_match'},
 ('ingress_port_mapping_ACTION', 'switch_config_params_ACTION'): {'delay': 1,
                                                                  'dep_type': 'rmt_action'},
 ('ingress_port_mapping_ACTION', 'system_acl_MATCH'): {'delay': 1,
                                                       'dep_type': 'rmt_match'},
 ('ingress_port_mapping_MATCH', 'ingress_port_mapping_ACTION'): {'delay': 9,
                                                                 'dep_type': 'new_match_to_action'},
 ('ingress_port_properties_ACTION', '_condition_4'): {'delay': 1,
                                                      'dep_type': 'rmt_match'},
 ('ingress_port_properties_ACTION', '_condition_5'): {'delay': 1,
                                                      'dep_type': 'rmt_match'},
 ('ingress_port_properties_ACTION', 'ingress_qos_map_dscp_MATCH'): {'delay': 1,
                                                                    'dep_type': 'rmt_match'},
 ('ingress_port_properties_ACTION', 'ingress_qos_map_pcp_MATCH'): {'delay': 1,
                                                                   'dep_type': 'rmt_match'},
 ('ingress_port_properties_ACTION', 'ip_acl_MATCH'): {'delay': 1,
                                                      'dep_type': 'rmt_match'},
 ('ingress_port_properties_ACTION', 'ipv4_racl_ACTION'): {'delay': 1,
                                                          'dep_type': 'rmt_action'},
 ('ingress_port_properties_ACTION', 'mac_acl_MATCH'): {'delay': 1,
                                                       'dep_type': 'rmt_match'},
 ('ingress_port_properties_ACTION', 'meter_action_MATCH'): {'delay': 1,
                                                            'dep_type': 'rmt_match'},
 ('ingress_port_properties_ACTION', 'meter_index_ACTION'): {'delay': 1,
                                                            'dep_type': 'rmt_action'},
 ('ingress_port_properties_ACTION', 'storm_control_ACTION'): {'delay': 1,
                                                              'dep_type': 'rmt_action'},
 ('ingress_port_properties_ACTION', 'storm_control_stats_MATCH'): {'delay': 1,
                                                                   'dep_type': 'rmt_match'},
 ('ingress_port_properties_ACTION', 'system_acl_MATCH'): {'delay': 1,
                                                          'dep_type': 'rmt_match'},
 ('ingress_port_properties_ACTION', 'traffic_class_MATCH'): {'delay': 1,
                                                             'dep_type': 'rmt_match'},
 ('ingress_port_properties_MATCH', 'ingress_port_properties_ACTION'): {'delay': 9,
                                                                       'dep_type': 'new_match_to_action'},
 ('ingress_qos_map_dscp_ACTION', 'ip_acl_ACTION'): {'delay': 1,
                                                    'dep_type': 'rmt_action'},
 ('ingress_qos_map_dscp_ACTION', 'ipv4_racl_ACTION'): {'delay': 1,
                                                       'dep_type': 'rmt_action'},
 ('ingress_qos_map_dscp_ACTION', 'mac_acl_ACTION'): {'delay': 1,
                                                     'dep_type': 'rmt_action'},
 ('ingress_qos_map_dscp_ACTION', 'meter_action_MATCH'): {'delay': 1,
                                                         'dep_type': 'rmt_match'},
 ('ingress_qos_map_dscp_ACTION', 'meter_index_ACTION'): {'delay': 1,
                                                         'dep_type': 'rmt_action'},
 ('ingress_qos_map_dscp_ACTION', 'storm_control_ACTION'): {'delay': 1,
                                                           'dep_type': 'rmt_action'},
 ('ingress_qos_map_dscp_ACTION', 'storm_control_stats_MATCH'): {'delay': 1,
                                                                'dep_type': 'rmt_match'},
 ('ingress_qos_map_dscp_ACTION', 'traffic_class_MATCH'): {'delay': 1,
                                                          'dep_type': 'rmt_match'},
 ('ingress_qos_map_dscp_MATCH', 'ingress_qos_map_dscp_ACTION'): {'delay': 9,
                                                                 'dep_type': 'new_match_to_action'},
 ('ingress_qos_map_pcp_ACTION', 'ip_acl_ACTION'): {'delay': 1,
                                                   'dep_type': 'rmt_action'},
 ('ingress_qos_map_pcp_ACTION', 'ipv4_racl_ACTION'): {'delay': 1,
                                                      'dep_type': 'rmt_action'},
 ('ingress_qos_map_pcp_ACTION', 'mac_acl_ACTION'): {'delay': 1,
                                                    'dep_type': 'rmt_action'},
 ('ingress_qos_map_pcp_ACTION', 'meter_action_MATCH'): {'delay': 1,
                                                        'dep_type': 'rmt_match'},
 ('ingress_qos_map_pcp_ACTION', 'meter_index_ACTION'): {'delay': 1,
                                                        'dep_type': 'rmt_action'},
 ('ingress_qos_map_pcp_ACTION', 'storm_control_ACTION'): {'delay': 1,
                                                          'dep_type': 'rmt_action'},
 ('ingress_qos_map_pcp_ACTION', 'storm_control_stats_MATCH'): {'delay': 1,
                                                               'dep_type': 'rmt_match'},
 ('ingress_qos_map_pcp_ACTION', 'traffic_class_MATCH'): {'delay': 1,
                                                         'dep_type': 'rmt_match'},
 ('ingress_qos_map_pcp_MATCH', 'ingress_qos_map_pcp_ACTION'): {'delay': 9,
                                                               'dep_type': 'new_match_to_action'},
 ('ip_acl_ACTION', 'acl_stats_ACTION'): {'delay': 1, 'dep_type': 'rmt_action'},
 ('ip_acl_ACTION', 'fwd_result_MATCH'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('ip_acl_ACTION', 'ipv4_racl_ACTION'): {'delay': 1, 'dep_type': 'rmt_action'},
 ('ip_acl_ACTION', 'meter_action_MATCH'): {'delay': 1,
                                           'dep_type': 'rmt_match'},
 ('ip_acl_ACTION', 'meter_index_MATCH'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('ip_acl_ACTION', 'storm_control_stats_MATCH'): {'delay': 1,
                                                  'dep_type': 'rmt_match'},
 ('ip_acl_ACTION', 'system_acl_MATCH'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('ip_acl_ACTION', 'traffic_class_MATCH'): {'delay': 1,
                                            'dep_type': 'rmt_match'},
 ('ip_acl_MATCH', 'ip_acl_ACTION'): {'delay': 9,
                                     'dep_type': 'new_match_to_action'},
 ('ipsg_ACTION', 'native_packet_over_fabric_ACTION'): {'delay': 0,
                                                       'dep_type': 'rmt_reverse_read'},
 ('ipsg_MATCH', 'ipsg_ACTION'): {'delay': 9,
                                 'dep_type': 'new_match_to_action'},
 ('ipsg_permit_special_ACTION', 'native_packet_over_fabric_ACTION'): {'delay': 0,
                                                                      'dep_type': 'rmt_reverse_read'},
 ('ipsg_permit_special_ACTION', 'system_acl_MATCH'): {'delay': 1,
                                                      'dep_type': 'rmt_match'},
 ('ipsg_permit_special_MATCH', 'ipsg_permit_special_ACTION'): {'delay': 9,
                                                               'dep_type': 'new_match_to_action'},
 ('ipv4_fib_ACTION', 'fwd_result_MATCH'): {'delay': 1,
                                           'dep_type': 'rmt_match'},
 ('ipv4_fib_MATCH', 'ipv4_fib_ACTION'): {'delay': 9,
                                         'dep_type': 'new_match_to_action'},
 ('ipv4_fib_MATCH', 'ipv4_fib_lpm_ACTION'): {'delay': 9,
                                             'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('ipv4_fib_lpm_ACTION', 'fwd_result_MATCH'): {'delay': 1,
                                               'dep_type': 'rmt_match'},
 ('ipv4_fib_lpm_MATCH', 'ipv4_fib_lpm_ACTION'): {'delay': 9,
                                                 'dep_type': 'new_match_to_action'},
 ('ipv4_multicast_bridge_ACTION', 'fwd_result_MATCH'): {'delay': 1,
                                                        'dep_type': 'rmt_match'},
 ('ipv4_multicast_bridge_MATCH', 'ipv4_multicast_bridge_ACTION'): {'delay': 9,
                                                                   'dep_type': 'new_match_to_action'},
 ('ipv4_multicast_bridge_MATCH', 'ipv4_multicast_bridge_star_g_ACTION'): {'delay': 9,
                                                                          'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('ipv4_multicast_bridge_star_g_ACTION', 'fwd_result_MATCH'): {'delay': 1,
                                                               'dep_type': 'rmt_match'},
 ('ipv4_multicast_bridge_star_g_MATCH', 'ipv4_multicast_bridge_star_g_ACTION'): {'delay': 9,
                                                                                 'dep_type': 'new_match_to_action'},
 ('ipv4_multicast_route_ACTION', 'fwd_result_MATCH'): {'delay': 1,
                                                       'dep_type': 'rmt_match'},
 ('ipv4_multicast_route_MATCH', 'ipv4_multicast_route_ACTION'): {'delay': 9,
                                                                 'dep_type': 'new_match_to_action'},
 ('ipv4_multicast_route_MATCH', 'ipv4_multicast_route_star_g_ACTION'): {'delay': 9,
                                                                        'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('ipv4_multicast_route_star_g_ACTION', 'fwd_result_MATCH'): {'delay': 1,
                                                              'dep_type': 'rmt_match'},
 ('ipv4_multicast_route_star_g_ACTION', 'system_acl_MATCH'): {'delay': 1,
                                                              'dep_type': 'rmt_match'},
 ('ipv4_multicast_route_star_g_MATCH', 'ipv4_multicast_route_star_g_ACTION'): {'delay': 9,
                                                                               'dep_type': 'new_match_to_action'},
 ('ipv4_racl_ACTION', 'acl_stats_ACTION'): {'delay': 1,
                                            'dep_type': 'rmt_action'},
 ('ipv4_racl_ACTION', 'fwd_result_MATCH'): {'delay': 1,
                                            'dep_type': 'rmt_match'},
 ('ipv4_racl_ACTION', 'meter_action_MATCH'): {'delay': 1,
                                              'dep_type': 'rmt_match'},
 ('ipv4_racl_ACTION', 'meter_index_ACTION'): {'delay': 1,
                                              'dep_type': 'rmt_action'},
 ('ipv4_racl_ACTION', 'storm_control_stats_MATCH'): {'delay': 1,
                                                     'dep_type': 'rmt_match'},
 ('ipv4_racl_ACTION', 'system_acl_MATCH'): {'delay': 1,
                                            'dep_type': 'rmt_match'},
 ('ipv4_racl_ACTION', 'traffic_class_MATCH'): {'delay': 1,
                                               'dep_type': 'rmt_match'},
 ('ipv4_racl_MATCH', 'ipv4_racl_ACTION'): {'delay': 9,
                                           'dep_type': 'new_match_to_action'},
 ('ipv4_urpf_ACTION', '_condition_29'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('ipv4_urpf_ACTION', 'urpf_bd_MATCH'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('ipv4_urpf_MATCH', 'ipv4_urpf_ACTION'): {'delay': 9,
                                           'dep_type': 'new_match_to_action'},
 ('ipv4_urpf_MATCH', 'ipv4_urpf_lpm_ACTION'): {'delay': 9,
                                               'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('ipv4_urpf_lpm_ACTION', '_condition_29'): {'delay': 1,
                                             'dep_type': 'rmt_match'},
 ('ipv4_urpf_lpm_ACTION', 'system_acl_MATCH'): {'delay': 1,
                                                'dep_type': 'rmt_match'},
 ('ipv4_urpf_lpm_ACTION', 'urpf_bd_MATCH'): {'delay': 1,
                                             'dep_type': 'rmt_match'},
 ('ipv4_urpf_lpm_MATCH', 'ipv4_urpf_lpm_ACTION'): {'delay': 9,
                                                   'dep_type': 'new_match_to_action'},
 ('lag_group_ACTION', 'fabric_lag_MATCH'): {'delay': 1,
                                            'dep_type': 'rmt_match'},
 ('lag_group_ACTION', 'system_acl_ACTION'): {'delay': 1,
                                             'dep_type': 'rmt_action'},
 ('lag_group_MATCH', 'lag_group_ACTION'): {'delay': 9,
                                           'dep_type': 'new_match_to_action'},
 ('learn_notify_MATCH', 'learn_notify_ACTION'): {'delay': 9,
                                                 'dep_type': 'new_match_to_action'},
 ('mac_acl_ACTION', 'acl_stats_ACTION'): {'delay': 1,
                                          'dep_type': 'rmt_action'},
 ('mac_acl_ACTION', 'fwd_result_MATCH'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('mac_acl_ACTION', 'ipv4_racl_ACTION'): {'delay': 1,
                                          'dep_type': 'rmt_action'},
 ('mac_acl_ACTION', 'meter_action_MATCH'): {'delay': 1,
                                            'dep_type': 'rmt_match'},
 ('mac_acl_ACTION', 'meter_index_MATCH'): {'delay': 1,
                                           'dep_type': 'rmt_match'},
 ('mac_acl_ACTION', 'storm_control_stats_MATCH'): {'delay': 1,
                                                   'dep_type': 'rmt_match'},
 ('mac_acl_ACTION', 'system_acl_MATCH'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('mac_acl_ACTION', 'traffic_class_MATCH'): {'delay': 1,
                                             'dep_type': 'rmt_match'},
 ('mac_acl_MATCH', 'mac_acl_ACTION'): {'delay': 9,
                                       'dep_type': 'new_match_to_action'},
 ('meter_action_MATCH', 'meter_action_ACTION'): {'delay': 9,
                                                 'dep_type': 'new_match_to_action'},
 ('meter_index_ACTION', 'meter_action_MATCH'): {'delay': 1,
                                                'dep_type': 'rmt_match'},
 ('meter_index_ACTION', 'storm_control_stats_MATCH'): {'delay': 1,
                                                       'dep_type': 'rmt_match'},
 ('meter_index_MATCH', 'meter_index_ACTION'): {'delay': 9,
                                               'dep_type': 'new_match_to_action'},
 ('nat_dst_ACTION', 'fwd_result_MATCH'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('nat_dst_MATCH', 'nat_dst_ACTION'): {'delay': 9,
                                       'dep_type': 'new_match_to_action'},
 ('nat_dst_MATCH', 'nat_src_ACTION'): {'delay': 9,
                                       'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('nat_flow_ACTION', 'fwd_result_MATCH'): {'delay': 1,
                                           'dep_type': 'rmt_match'},
 ('nat_flow_MATCH', 'nat_flow_ACTION'): {'delay': 9,
                                         'dep_type': 'new_match_to_action'},
 ('nat_src_MATCH', 'nat_flow_ACTION'): {'delay': 9,
                                        'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('nat_src_MATCH', 'nat_src_ACTION'): {'delay': 9,
                                       'dep_type': 'new_match_to_action'},
 ('nat_twice_ACTION', 'fwd_result_MATCH'): {'delay': 1,
                                            'dep_type': 'rmt_match'},
 ('nat_twice_MATCH', 'nat_dst_ACTION'): {'delay': 9,
                                         'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('nat_twice_MATCH', 'nat_twice_ACTION'): {'delay': 9,
                                           'dep_type': 'new_match_to_action'},
 ('native_packet_over_fabric_ACTION', 'compute_ipv4_hashes_ACTION'): {'delay': 1,
                                                                      'dep_type': 'rmt_action'},
 ('native_packet_over_fabric_ACTION', 'compute_non_ip_hashes_ACTION'): {'delay': 1,
                                                                        'dep_type': 'rmt_action'},
 ('native_packet_over_fabric_ACTION', 'dmac_MATCH'): {'delay': 1,
                                                      'dep_type': 'rmt_match'},
 ('native_packet_over_fabric_ACTION', 'ingress_l4_dst_port_MATCH'): {'delay': 1,
                                                                     'dep_type': 'rmt_match'},
 ('native_packet_over_fabric_ACTION', 'ingress_l4_src_port_MATCH'): {'delay': 1,
                                                                     'dep_type': 'rmt_match'},
 ('native_packet_over_fabric_ACTION', 'ip_acl_MATCH'): {'delay': 1,
                                                        'dep_type': 'rmt_match'},
 ('native_packet_over_fabric_ACTION', 'ipv4_fib_MATCH'): {'delay': 1,
                                                          'dep_type': 'rmt_match'},
 ('native_packet_over_fabric_ACTION', 'ipv4_fib_lpm_MATCH'): {'delay': 1,
                                                              'dep_type': 'rmt_match'},
 ('native_packet_over_fabric_ACTION', 'ipv4_multicast_bridge_MATCH'): {'delay': 1,
                                                                       'dep_type': 'rmt_match'},
 ('native_packet_over_fabric_ACTION', 'ipv4_multicast_bridge_star_g_MATCH'): {'delay': 1,
                                                                              'dep_type': 'rmt_match'},
 ('native_packet_over_fabric_ACTION', 'ipv4_multicast_route_MATCH'): {'delay': 1,
                                                                      'dep_type': 'rmt_match'},
 ('native_packet_over_fabric_ACTION', 'ipv4_multicast_route_star_g_MATCH'): {'delay': 1,
                                                                             'dep_type': 'rmt_match'},
 ('native_packet_over_fabric_ACTION', 'ipv4_racl_MATCH'): {'delay': 1,
                                                           'dep_type': 'rmt_match'},
 ('native_packet_over_fabric_ACTION', 'ipv4_urpf_MATCH'): {'delay': 1,
                                                           'dep_type': 'rmt_match'},
 ('native_packet_over_fabric_ACTION', 'ipv4_urpf_lpm_MATCH'): {'delay': 1,
                                                               'dep_type': 'rmt_match'},
 ('native_packet_over_fabric_ACTION', 'learn_notify_ACTION'): {'delay': 1,
                                                               'dep_type': 'rmt_action'},
 ('native_packet_over_fabric_ACTION', 'mac_acl_MATCH'): {'delay': 1,
                                                         'dep_type': 'rmt_match'},
 ('native_packet_over_fabric_ACTION', 'nat_dst_MATCH'): {'delay': 1,
                                                         'dep_type': 'rmt_match'},
 ('native_packet_over_fabric_ACTION', 'nat_flow_MATCH'): {'delay': 1,
                                                          'dep_type': 'rmt_match'},
 ('native_packet_over_fabric_ACTION', 'nat_src_MATCH'): {'delay': 1,
                                                         'dep_type': 'rmt_match'},
 ('native_packet_over_fabric_ACTION', 'nat_twice_MATCH'): {'delay': 1,
                                                           'dep_type': 'rmt_match'},
 ('native_packet_over_fabric_ACTION', 'rmac_MATCH'): {'delay': 1,
                                                      'dep_type': 'rmt_match'},
 ('native_packet_over_fabric_ACTION', 'smac_MATCH'): {'delay': 1,
                                                      'dep_type': 'rmt_match'},
 ('native_packet_over_fabric_ACTION', 'system_acl_MATCH'): {'delay': 1,
                                                            'dep_type': 'rmt_match'},
 ('native_packet_over_fabric_ACTION', 'validate_packet_MATCH'): {'delay': 1,
                                                                 'dep_type': 'rmt_match'},
 ('native_packet_over_fabric_MATCH', 'native_packet_over_fabric_ACTION'): {'delay': 9,
                                                                           'dep_type': 'new_match_to_action'},
 ('nexthop_ACTION', '_condition_36'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('nexthop_ACTION', 'bd_flood_ACTION'): {'delay': 1, 'dep_type': 'rmt_action'},
 ('nexthop_ACTION', 'fabric_lag_MATCH'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('nexthop_ACTION', 'lag_group_MATCH'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('nexthop_ACTION', 'system_acl_MATCH'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('nexthop_MATCH', 'nexthop_ACTION'): {'delay': 9,
                                       'dep_type': 'new_match_to_action'},
 ('port_vlan_mapping_ACTION', '_condition_2'): {'delay': 1,
                                                'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', '_condition_23'): {'delay': 1,
                                                 'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', '_condition_26'): {'delay': 1,
                                                 'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', '_condition_27'): {'delay': 1,
                                                 'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', '_condition_37'): {'delay': 1,
                                                 'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', 'bd_flood_MATCH'): {'delay': 1,
                                                  'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', 'dmac_MATCH'): {'delay': 1,
                                              'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', 'ecmp_group_ACTION'): {'delay': 1,
                                                     'dep_type': 'rmt_action'},
 ('port_vlan_mapping_ACTION', 'fwd_result_MATCH'): {'delay': 1,
                                                    'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', 'ingress_bd_stats_ACTION'): {'delay': 1,
                                                           'dep_type': 'rmt_action'},
 ('port_vlan_mapping_ACTION', 'ip_acl_MATCH'): {'delay': 1,
                                                'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', 'ipsg_MATCH'): {'delay': 1,
                                              'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', 'ipv4_fib_MATCH'): {'delay': 1,
                                                  'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', 'ipv4_fib_lpm_MATCH'): {'delay': 1,
                                                      'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', 'ipv4_multicast_bridge_MATCH'): {'delay': 1,
                                                               'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', 'ipv4_multicast_bridge_star_g_MATCH'): {'delay': 1,
                                                                      'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', 'ipv4_multicast_route_MATCH'): {'delay': 1,
                                                              'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', 'ipv4_multicast_route_star_g_MATCH'): {'delay': 1,
                                                                     'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', 'ipv4_racl_MATCH'): {'delay': 1,
                                                   'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', 'ipv4_urpf_MATCH'): {'delay': 1,
                                                   'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', 'ipv4_urpf_lpm_MATCH'): {'delay': 1,
                                                       'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', 'learn_notify_ACTION'): {'delay': 1,
                                                       'dep_type': 'rmt_action'},
 ('port_vlan_mapping_ACTION', 'mac_acl_MATCH'): {'delay': 1,
                                                 'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', 'nat_dst_MATCH'): {'delay': 1,
                                                 'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', 'nat_flow_MATCH'): {'delay': 1,
                                                  'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', 'nat_src_MATCH'): {'delay': 1,
                                                 'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', 'nat_twice_MATCH'): {'delay': 1,
                                                   'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', 'nexthop_ACTION'): {'delay': 1,
                                                  'dep_type': 'rmt_action'},
 ('port_vlan_mapping_ACTION', 'rmac_MATCH'): {'delay': 1,
                                              'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', 'smac_MATCH'): {'delay': 1,
                                              'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', 'spanning_tree_MATCH'): {'delay': 1,
                                                       'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', 'system_acl_MATCH'): {'delay': 1,
                                                    'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', 'urpf_bd_MATCH'): {'delay': 1,
                                                 'dep_type': 'rmt_match'},
 ('port_vlan_mapping_ACTION', 'validate_packet_ACTION'): {'delay': 1,
                                                          'dep_type': 'rmt_action'},
 ('port_vlan_mapping_MATCH', 'port_vlan_mapping_ACTION'): {'delay': 9,
                                                           'dep_type': 'new_match_to_action'},
 ('rmac_ACTION', 'fwd_result_MATCH'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('rmac_ACTION', 'system_acl_MATCH'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('rmac_MATCH', '_condition_21'): {'delay': 9,
                                   'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('rmac_MATCH', '_condition_25'): {'delay': 9,
                                   'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('rmac_MATCH', 'rmac_ACTION'): {'delay': 9,
                                 'dep_type': 'new_match_to_action'},
 ('smac_ACTION', 'learn_notify_MATCH'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('smac_MATCH', 'smac_ACTION'): {'delay': 9,
                                 'dep_type': 'new_match_to_action'},
 ('spanning_tree_ACTION', 'learn_notify_MATCH'): {'delay': 1,
                                                  'dep_type': 'rmt_match'},
 ('spanning_tree_ACTION', 'system_acl_MATCH'): {'delay': 1,
                                                'dep_type': 'rmt_match'},
 ('spanning_tree_MATCH', 'spanning_tree_ACTION'): {'delay': 9,
                                                   'dep_type': 'new_match_to_action'},
 ('storm_control_ACTION', 'ip_acl_ACTION'): {'delay': 1,
                                             'dep_type': 'rmt_action'},
 ('storm_control_ACTION', 'ipv4_racl_ACTION'): {'delay': 1,
                                                'dep_type': 'rmt_action'},
 ('storm_control_ACTION', 'mac_acl_ACTION'): {'delay': 1,
                                              'dep_type': 'rmt_action'},
 ('storm_control_ACTION', 'meter_action_MATCH'): {'delay': 1,
                                                  'dep_type': 'rmt_match'},
 ('storm_control_ACTION', 'meter_index_MATCH'): {'delay': 1,
                                                 'dep_type': 'rmt_match'},
 ('storm_control_ACTION', 'storm_control_stats_MATCH'): {'delay': 1,
                                                         'dep_type': 'rmt_match'},
 ('storm_control_ACTION', 'validate_packet_ACTION'): {'delay': 0,
                                                      'dep_type': 'rmt_reverse_read'},
 ('storm_control_MATCH', 'storm_control_ACTION'): {'delay': 9,
                                                   'dep_type': 'new_match_to_action'},
 ('storm_control_stats_MATCH', 'storm_control_stats_ACTION'): {'delay': 9,
                                                               'dep_type': 'new_match_to_action'},
 ('switch_config_params_ACTION', 'dmac_ACTION'): {'delay': 1,
                                                  'dep_type': 'rmt_action'},
 ('switch_config_params_ACTION', 'ecmp_group_ACTION'): {'delay': 1,
                                                        'dep_type': 'rmt_action'},
 ('switch_config_params_ACTION', 'fabric_ingress_dst_lkp_ACTION'): {'delay': 1,
                                                                    'dep_type': 'rmt_action'},
 ('switch_config_params_ACTION', 'fabric_lag_ACTION'): {'delay': 1,
                                                        'dep_type': 'rmt_action'},
 ('switch_config_params_ACTION', 'fwd_result_ACTION'): {'delay': 1,
                                                        'dep_type': 'rmt_action'},
 ('switch_config_params_ACTION', 'ip_acl_ACTION'): {'delay': 1,
                                                    'dep_type': 'rmt_action'},
 ('switch_config_params_ACTION', 'lag_group_ACTION'): {'delay': 1,
                                                       'dep_type': 'rmt_action'},
 ('switch_config_params_ACTION', 'mac_acl_ACTION'): {'delay': 1,
                                                     'dep_type': 'rmt_action'},
 ('switch_config_params_ACTION', 'nexthop_ACTION'): {'delay': 1,
                                                     'dep_type': 'rmt_action'},
 ('switch_config_params_ACTION', 'system_acl_MATCH'): {'delay': 1,
                                                       'dep_type': 'rmt_match'},
 ('switch_config_params_MATCH', 'switch_config_params_ACTION'): {'delay': 9,
                                                                 'dep_type': 'new_match_to_action'},
 ('system_acl_MATCH', 'system_acl_ACTION'): {'delay': 9,
                                             'dep_type': 'new_match_to_action'},
 ('traffic_class_ACTION', 'system_acl_ACTION'): {'delay': 1,
                                                 'dep_type': 'rmt_action'},
 ('traffic_class_MATCH', 'traffic_class_ACTION'): {'delay': 9,
                                                   'dep_type': 'new_match_to_action'},
 ('urpf_bd_ACTION', 'system_acl_MATCH'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('urpf_bd_MATCH', 'urpf_bd_ACTION'): {'delay': 9,
                                       'dep_type': 'new_match_to_action'},
 ('validate_outer_ethernet_ACTION', '_condition_13'): {'delay': 1,
                                                       'dep_type': 'rmt_match'},
 ('validate_outer_ethernet_ACTION', '_condition_40'): {'delay': 1,
                                                       'dep_type': 'rmt_match'},
 ('validate_outer_ethernet_ACTION', 'bd_flood_MATCH'): {'delay': 1,
                                                        'dep_type': 'rmt_match'},
 ('validate_outer_ethernet_ACTION', 'compute_ipv4_hashes_MATCH'): {'delay': 1,
                                                                   'dep_type': 'rmt_match'},
 ('validate_outer_ethernet_ACTION', 'compute_non_ip_hashes_MATCH'): {'delay': 1,
                                                                     'dep_type': 'rmt_match'},
 ('validate_outer_ethernet_ACTION', 'drop_stats_ACTION'): {'delay': 1,
                                                           'dep_type': 'rmt_action'},
 ('validate_outer_ethernet_ACTION', 'fabric_ingress_dst_lkp_ACTION'): {'delay': 0,
                                                                       'dep_type': 'rmt_reverse_read'},
 ('validate_outer_ethernet_ACTION', 'fwd_result_ACTION'): {'delay': 1,
                                                           'dep_type': 'rmt_action'},
 ('validate_outer_ethernet_ACTION', 'ingress_qos_map_pcp_MATCH'): {'delay': 1,
                                                                   'dep_type': 'rmt_match'},
 ('validate_outer_ethernet_ACTION', 'mac_acl_MATCH'): {'delay': 1,
                                                       'dep_type': 'rmt_match'},
 ('validate_outer_ethernet_ACTION', 'native_packet_over_fabric_ACTION'): {'delay': 1,
                                                                          'dep_type': 'rmt_action'},
 ('validate_outer_ethernet_ACTION', 'storm_control_MATCH'): {'delay': 1,
                                                             'dep_type': 'rmt_match'},
 ('validate_outer_ethernet_ACTION', 'system_acl_MATCH'): {'delay': 1,
                                                          'dep_type': 'rmt_match'},
 ('validate_outer_ethernet_ACTION', 'validate_packet_ACTION'): {'delay': 1,
                                                                'dep_type': 'rmt_action'},
 ('validate_outer_ethernet_MATCH', '_condition_0'): {'delay': 9,
                                                     'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('validate_outer_ethernet_MATCH', 'validate_outer_ethernet_ACTION'): {'delay': 9,
                                                                       'dep_type': 'new_match_to_action'},
 ('validate_outer_ipv4_packet_ACTION', '_condition_13'): {'delay': 1,
                                                          'dep_type': 'rmt_match'},
 ('validate_outer_ipv4_packet_ACTION', '_condition_16'): {'delay': 1,
                                                          'dep_type': 'rmt_match'},
 ('validate_outer_ipv4_packet_ACTION', '_condition_19'): {'delay': 1,
                                                          'dep_type': 'rmt_match'},
 ('validate_outer_ipv4_packet_ACTION', '_condition_21'): {'delay': 1,
                                                          'dep_type': 'rmt_match'},
 ('validate_outer_ipv4_packet_ACTION', '_condition_26'): {'delay': 1,
                                                          'dep_type': 'rmt_match'},
 ('validate_outer_ipv4_packet_ACTION', '_condition_40'): {'delay': 1,
                                                          'dep_type': 'rmt_match'},
 ('validate_outer_ipv4_packet_ACTION', 'compute_ipv4_hashes_MATCH'): {'delay': 1,
                                                                      'dep_type': 'rmt_match'},
 ('validate_outer_ipv4_packet_ACTION', 'compute_non_ip_hashes_MATCH'): {'delay': 1,
                                                                        'dep_type': 'rmt_match'},
 ('validate_outer_ipv4_packet_ACTION', 'drop_stats_ACTION'): {'delay': 1,
                                                              'dep_type': 'rmt_action'},
 ('validate_outer_ipv4_packet_ACTION', 'fwd_result_MATCH'): {'delay': 1,
                                                             'dep_type': 'rmt_match'},
 ('validate_outer_ipv4_packet_ACTION', 'ingress_qos_map_dscp_MATCH'): {'delay': 1,
                                                                       'dep_type': 'rmt_match'},
 ('validate_outer_ipv4_packet_ACTION', 'system_acl_MATCH'): {'delay': 1,
                                                             'dep_type': 'rmt_match'},
 ('validate_outer_ipv4_packet_ACTION', 'validate_packet_MATCH'): {'delay': 1,
                                                                  'dep_type': 'rmt_match'},
 ('validate_outer_ipv4_packet_MATCH', 'validate_outer_ipv4_packet_ACTION'): {'delay': 9,
                                                                             'dep_type': 'new_match_to_action'},
 ('validate_packet_ACTION', '_condition_40'): {'delay': 1,
                                               'dep_type': 'rmt_match'},
 ('validate_packet_ACTION', 'bd_flood_MATCH'): {'delay': 1,
                                                'dep_type': 'rmt_match'},
 ('validate_packet_ACTION', 'compute_ipv4_hashes_MATCH'): {'delay': 1,
                                                           'dep_type': 'rmt_match'},
 ('validate_packet_ACTION', 'compute_non_ip_hashes_MATCH'): {'delay': 1,
                                                             'dep_type': 'rmt_match'},
 ('validate_packet_ACTION', 'drop_stats_ACTION'): {'delay': 1,
                                                   'dep_type': 'rmt_action'},
 ('validate_packet_ACTION', 'fwd_result_MATCH'): {'delay': 1,
                                                  'dep_type': 'rmt_match'},
 ('validate_packet_ACTION', 'ingress_bd_stats_ACTION'): {'delay': 1,
                                                         'dep_type': 'rmt_action'},
 ('validate_packet_ACTION', 'system_acl_MATCH'): {'delay': 1,
                                                  'dep_type': 'rmt_match'},
 ('validate_packet_MATCH', 'validate_packet_ACTION'): {'delay': 9,
                                                       'dep_type': 'new_match_to_action'}}
