dM = 9
dA = 1
dS = 0
nodes = \
{'_condition_0': { 'num_fields': 1, 'type': 'action'},
 '_condition_1': { 'num_fields': 1, 'type': 'action'},
 '_condition_10': {'num_fields': 1, 'type': 'action'},
 '_condition_11': {'num_fields': 1, 'type': 'action'},
 '_condition_12': {'num_fields': 1, 'type': 'action'},
 '_condition_13': {'num_fields': 1, 'type': 'action'},
 '_condition_14': {'num_fields': 1, 'type': 'action'},
 '_condition_15': {'num_fields': 1, 'type': 'action'},
 '_condition_16': {'num_fields': 1, 'type': 'action'},
 '_condition_17': {'num_fields': 1, 'type': 'action'},
 '_condition_18': {'num_fields': 1, 'type': 'action'},
 '_condition_19': {'num_fields': 1, 'type': 'action'},
 '_condition_2': { 'num_fields': 1, 'type': 'action'},
 '_condition_20': {'num_fields': 1, 'type': 'action'},
 '_condition_21': {'num_fields': 1, 'type': 'action'},
 '_condition_22': {'num_fields': 1, 'type': 'action'},
 '_condition_23': {'num_fields': 1, 'type': 'action'},
 '_condition_24': {'num_fields': 1, 'type': 'action'},
 '_condition_25': {'num_fields': 1, 'type': 'action'},
 '_condition_26': {'num_fields': 1, 'type': 'action'},
 '_condition_27': {'num_fields': 1, 'type': 'action'},
 '_condition_28': {'num_fields': 1, 'type': 'action'},
 '_condition_29': {'num_fields': 1, 'type': 'action'},
 '_condition_3': { 'num_fields': 1, 'type': 'action'},
 '_condition_30': {'num_fields': 1, 'type': 'action'},
 '_condition_31': {'num_fields': 1, 'type': 'action'},
 '_condition_32': {'num_fields': 1, 'type': 'action'},
 '_condition_33': {'num_fields': 1, 'type': 'action'},
 '_condition_34': {'num_fields': 1, 'type': 'action'},
 '_condition_35': {'num_fields': 1, 'type': 'action'},
 '_condition_36': {'num_fields': 1, 'type': 'action'},
 '_condition_37': {'num_fields': 1, 'type': 'action'},
 '_condition_38': {'num_fields': 1, 'type': 'action'},
 '_condition_39': {'num_fields': 1, 'type': 'action'},
 '_condition_4': { 'num_fields': 1, 'type': 'action'},
 '_condition_40': {'num_fields': 1, 'type': 'action'},
 '_condition_41': {'num_fields': 1, 'type': 'action'},
 '_condition_42': {'num_fields': 1, 'type': 'action'},
 '_condition_43': {'num_fields': 1, 'type': 'action'},
 '_condition_44': {'num_fields': 1, 'type': 'action'},
 '_condition_45': {'num_fields': 1, 'type': 'action'},
 '_condition_46': {'num_fields': 1, 'type': 'action'},
 '_condition_47': {'num_fields': 1, 'type': 'action'},
 '_condition_48': {'num_fields': 1, 'type': 'action'},
 '_condition_49': {'num_fields': 1, 'type': 'action'},
 '_condition_5': { 'num_fields': 1, 'type': 'action'},
 '_condition_50': {'num_fields': 1, 'type': 'action'},
 '_condition_51': {'num_fields': 1, 'type': 'action'},
 '_condition_52': {'num_fields': 1, 'type': 'action'},
 '_condition_53': {'num_fields': 1, 'type': 'action'},
 '_condition_54': {'num_fields': 1, 'type': 'action'},
 '_condition_6': { 'num_fields': 1, 'type': 'action'},
 '_condition_7': { 'num_fields': 1, 'type': 'action'},
 '_condition_8': { 'num_fields': 1, 'type': 'action'},
 '_condition_9': { 'num_fields': 1, 'type': 'action'},
 'acl_stats_ACTION': {'num_fields': 1, 'type': 'action'},
 'adjust_lkp_fields_ACTION': {'num_fields': 8, 'type': 'action'},
 'adjust_lkp_fields_MATCH': {'key_width': 2, 'type': 'match'},
 'bd_flood_ACTION': {'num_fields': 1, 'type': 'action'},
 'bd_flood_MATCH': {'key_width': 19, 'type': 'match'},
 'compute_ipv4_hashes_ACTION': {'num_fields': 2, 'type': 'action'},
 'compute_ipv4_hashes_MATCH': {'key_width': 1, 'type': 'match'},
 'compute_ipv6_hashes_ACTION': {'num_fields': 2, 'type': 'action'},
 'compute_ipv6_hashes_MATCH': {'key_width': 1, 'type': 'match'},
 'compute_non_ip_hashes_ACTION': {'num_fields': 1, 'type': 'action'},
 'compute_non_ip_hashes_MATCH': {'key_width': 1, 'type': 'match'},
 'compute_other_hashes_ACTION': {'num_fields': 3, 'type': 'action'},
 'compute_other_hashes_MATCH': {'key_width': 16, 'type': 'match'},
 'dmac_ACTION': {'num_fields': 3, 'type': 'action'},
 'dmac_MATCH': {'key_width': 64, 'type': 'match'},
 'drop_stats_ACTION': {'num_fields': 1, 'type': 'action'},
 'ecmp_group_ACTION': {'num_fields': 5, 'type': 'action'},
 'ecmp_group_MATCH': {'key_width': 16, 'type': 'match'},
 'fabric_ingress_dst_lkp_ACTION': {'num_fields': 10, 'type': 'action'},
 'fabric_ingress_dst_lkp_MATCH': {'key_width': 8, 'type': 'match'},
 'fabric_ingress_src_lkp_ACTION': {'num_fields': 0, 'type': 'action'},
 'fabric_ingress_src_lkp_MATCH': {'key_width': 16, 'type': 'match'},
 'fabric_lag_ACTION': {'num_fields': 1, 'type': 'action'},
 'fabric_lag_MATCH': {'key_width': 8, 'type': 'match'},
 'fwd_result_ACTION': {'num_fields': 6, 'type': 'action'},
 'fwd_result_MATCH': {'key_width': 33, 'type': 'match'},
 'ingress_bd_stats_ACTION': {'num_fields': 1, 'type': 'action'},
 'ingress_l4_dst_port_ACTION': {'num_fields': 1, 'type': 'action'},
 'ingress_l4_dst_port_MATCH': {'key_width': 16, 'type': 'match'},
 'ingress_l4_src_port_ACTION': {'num_fields': 1, 'type': 'action'},
 'ingress_l4_src_port_MATCH': {'key_width': 16, 'type': 'match'},
 'ingress_port_mapping_ACTION': {'num_fields': 2, 'type': 'action'},
 'ingress_port_mapping_MATCH': {'key_width': 9, 'type': 'match'},
 'ingress_port_properties_ACTION': {'num_fields': 7, 'type': 'action'},
 'ingress_port_properties_MATCH': {'key_width': 9, 'type': 'match'},
 'ingress_qos_map_dscp_ACTION': {'num_fields': 2, 'type': 'action'},
 'ingress_qos_map_dscp_MATCH': {'key_width': 13, 'type': 'match'},
 'ingress_qos_map_pcp_ACTION': {'num_fields': 2, 'type': 'action'},
 'ingress_qos_map_pcp_MATCH': {'key_width': 8, 'type': 'match'},
 'int_sink_update_outer_ACTION': {'num_fields': 4, 'type': 'action'},
 'int_sink_update_outer_MATCH': {'key_width': 3, 'type': 'match'},
 'int_source_ACTION': {'num_fields': 1, 'type': 'action'},
 'int_source_MATCH': {'key_width': 131, 'type': 'match'},
 'int_terminate_ACTION': {'num_fields': 29, 'type': 'action'},
 'int_terminate_MATCH': {'key_width': 68, 'type': 'match'},
 'ip_acl_ACTION': {'num_fields': 10, 'type': 'action'},
 'ip_acl_MATCH': {'key_width': 136, 'type': 'match'},
 'ipsg_ACTION': {'num_fields': 0, 'type': 'action'},
 'ipsg_MATCH': {'key_width': 112, 'type': 'match'},
 'ipsg_permit_special_ACTION': {'num_fields': 1, 'type': 'action'},
 'ipsg_permit_special_MATCH': {'key_width': 56, 'type': 'match'},
 'ipv4_dest_vtep_ACTION': {'num_fields': 2, 'type': 'action'},
 'ipv4_dest_vtep_MATCH': {'key_width': 53, 'type': 'match'},
 'ipv4_fib_ACTION': {'num_fields': 3, 'type': 'action'},
 'ipv4_fib_MATCH': {'key_width': 48, 'type': 'match'},
 'ipv4_fib_lpm_ACTION': {'num_fields': 3, 'type': 'action'},
 'ipv4_fib_lpm_MATCH': {'key_width': 48, 'type': 'match'},
 'ipv4_multicast_bridge_ACTION': {'num_fields': 2, 'type': 'action'},
 'ipv4_multicast_bridge_MATCH': {'key_width': 80, 'type': 'match'},
 'ipv4_multicast_bridge_star_g_ACTION': {'num_fields': 2, 'type': 'action'},
 'ipv4_multicast_bridge_star_g_MATCH': {'key_width': 48, 'type': 'match'},
 'ipv4_multicast_route_ACTION': {'num_fields': 4, 'type': 'action'},
 'ipv4_multicast_route_MATCH': {'key_width': 80, 'type': 'match'},
 'ipv4_multicast_route_star_g_ACTION': {'num_fields': 4, 'type': 'action'},
 'ipv4_multicast_route_star_g_MATCH': {'key_width': 48, 'type': 'match'},
 'ipv4_racl_ACTION': {'num_fields': 8, 'type': 'action'},
 'ipv4_racl_MATCH': {'key_width': 104, 'type': 'match'},
 'ipv4_src_vtep_ACTION': {'num_fields': 1, 'type': 'action'},
 'ipv4_src_vtep_MATCH': {'key_width': 53, 'type': 'match'},
 'ipv4_urpf_ACTION': {'num_fields': 3, 'type': 'action'},
 'ipv4_urpf_MATCH': {'key_width': 48, 'type': 'match'},
 'ipv4_urpf_lpm_ACTION': {'num_fields': 3, 'type': 'action'},
 'ipv4_urpf_lpm_MATCH': {'key_width': 48, 'type': 'match'},
 'ipv6_acl_ACTION': {'num_fields': 10, 'type': 'action'},
 'ipv6_acl_MATCH': {'key_width': 328, 'type': 'match'},
 'ipv6_dest_vtep_ACTION': {'num_fields': 2, 'type': 'action'},
 'ipv6_dest_vtep_MATCH': {'key_width': 149, 'type': 'match'},
 'ipv6_fib_ACTION': {'num_fields': 3, 'type': 'action'},
 'ipv6_fib_MATCH': {'key_width': 144, 'type': 'match'},
 'ipv6_fib_lpm_ACTION': {'num_fields': 3, 'type': 'action'},
 'ipv6_fib_lpm_MATCH': {'key_width': 144, 'type': 'match'},
 'ipv6_multicast_bridge_ACTION': {'num_fields': 2, 'type': 'action'},
 'ipv6_multicast_bridge_MATCH': {'key_width': 272, 'type': 'match'},
 'ipv6_multicast_bridge_star_g_ACTION': {'num_fields': 2, 'type': 'action'},
 'ipv6_multicast_bridge_star_g_MATCH': {'key_width': 144, 'type': 'match'},
 'ipv6_multicast_route_ACTION': {'num_fields': 4, 'type': 'action'},
 'ipv6_multicast_route_MATCH': {'key_width': 272, 'type': 'match'},
 'ipv6_multicast_route_star_g_ACTION': {'num_fields': 4, 'type': 'action'},
 'ipv6_multicast_route_star_g_MATCH': {'key_width': 144, 'type': 'match'},
 'ipv6_racl_ACTION': {'num_fields': 8, 'type': 'action'},
 'ipv6_racl_MATCH': {'key_width': 296, 'type': 'match'},
 'ipv6_src_vtep_ACTION': {'num_fields': 1, 'type': 'action'},
 'ipv6_src_vtep_MATCH': {'key_width': 149, 'type': 'match'},
 'ipv6_urpf_ACTION': {'num_fields': 3, 'type': 'action'},
 'ipv6_urpf_MATCH': {'key_width': 144, 'type': 'match'},
 'ipv6_urpf_lpm_ACTION': {'num_fields': 3, 'type': 'action'},
 'ipv6_urpf_lpm_MATCH': {'key_width': 144, 'type': 'match'},
 'lag_group_ACTION': {'num_fields': 2, 'type': 'action'},
 'lag_group_MATCH': {'key_width': 16, 'type': 'match'},
 'learn_notify_ACTION': {'num_fields': 1, 'type': 'action'},
 'learn_notify_MATCH': {'key_width': 20, 'type': 'match'},
 'mac_acl_ACTION': {'num_fields': 10, 'type': 'action'},
 'mac_acl_MATCH': {'key_width': 144, 'type': 'match'},
 'meter_action_ACTION': {'num_fields': 1, 'type': 'action'},
 'meter_action_MATCH': {'key_width': 18, 'type': 'match'},
 'meter_index_ACTION': {'num_fields': 0, 'type': 'action'},
 'meter_index_MATCH': {'key_width': 16, 'type': 'match'},
 'mpls_ACTION': {'num_fields': 8, 'type': 'action'},
 'mpls_MATCH': {'key_width': 22, 'type': 'match'},
 'nat_dst_ACTION': {'num_fields': 4, 'type': 'action'},
 'nat_dst_MATCH': {'key_width': 72, 'type': 'match'},
 'nat_flow_ACTION': {'num_fields': 4, 'type': 'action'},
 'nat_flow_MATCH': {'key_width': 120, 'type': 'match'},
 'nat_src_ACTION': {'num_fields': 1, 'type': 'action'},
 'nat_src_MATCH': {'key_width': 72, 'type': 'match'},
 'nat_twice_ACTION': {'num_fields': 4, 'type': 'action'},
 'nat_twice_MATCH': {'key_width': 120, 'type': 'match'},
 'native_packet_over_fabric_ACTION': {'num_fields': 7, 'type': 'action'},
 'native_packet_over_fabric_MATCH': {'key_width': 2, 'type': 'match'},
 'nexthop_ACTION': {'num_fields': 4, 'type': 'action'},
 'nexthop_MATCH': {'key_width': 16, 'type': 'match'},
 'outer_ipv4_multicast_ACTION': {'num_fields': 4, 'type': 'action'},
 'outer_ipv4_multicast_MATCH': {'key_width': 81, 'type': 'match'},
 'outer_ipv4_multicast_star_g_ACTION': {'num_fields': 5, 'type': 'action'},
 'outer_ipv4_multicast_star_g_MATCH': {'key_width': 49, 'type': 'match'},
 'outer_ipv6_multicast_ACTION': {'num_fields': 4, 'type': 'action'},
 'outer_ipv6_multicast_MATCH': {'key_width': 273, 'type': 'match'},
 'outer_ipv6_multicast_star_g_ACTION': {'num_fields': 5, 'type': 'action'},
 'outer_ipv6_multicast_star_g_MATCH': {'key_width': 145, 'type': 'match'},
 'outer_rmac_ACTION': {'num_fields': 1, 'type': 'action'},
 'outer_rmac_MATCH': {'key_width': 58, 'type': 'match'},
 'port_vlan_mapping_ACTION': {'num_fields': 21, 'type': 'action'},
 'port_vlan_mapping_MATCH': {'key_width': 42, 'type': 'match'},
 'rmac_ACTION': {'num_fields': 1, 'type': 'action'},
 'rmac_MATCH': {'key_width': 58, 'type': 'match'},
 'sflow_ing_take_sample_ACTION': {'num_fields': 2, 'type': 'action'},
 'sflow_ing_take_sample_MATCH': {'key_width': 48, 'type': 'match'},
 'sflow_ingress_ACTION': {'num_fields': 2, 'type': 'action'},
 'sflow_ingress_MATCH': {'key_width': 81, 'type': 'match'},
 'smac_ACTION': {'num_fields': 1, 'type': 'action'},
 'smac_MATCH': {'key_width': 64, 'type': 'match'},
 'spanning_tree_ACTION': {'num_fields': 1, 'type': 'action'},
 'spanning_tree_MATCH': {'key_width': 26, 'type': 'match'},
 'storm_control_ACTION': {'num_fields': 2, 'type': 'action'},
 'storm_control_MATCH': {'key_width': 12, 'type': 'match'},
 'storm_control_stats_ACTION': {'num_fields': 0, 'type': 'action'},
 'storm_control_stats_MATCH': {'key_width': 11, 'type': 'match'},
 'switch_config_params_ACTION': {'num_fields': 6, 'type': 'action'},
 'switch_config_params_MATCH': {'key_width': 1, 'type': 'match'},
 'system_acl_ACTION': {'num_fields': 7, 'type': 'action'},
 'system_acl_MATCH': {'key_width': 153, 'type': 'match'},
 'traffic_class_ACTION': {'num_fields': 2, 'type': 'action'},
 'traffic_class_MATCH': {'key_width': 13, 'type': 'match'},
 'tunnel_ACTION': {'num_fields': 14, 'type': 'action'},
 'tunnel_MATCH': {'key_width': 31, 'type': 'match'},
 'tunnel_lookup_miss_ACTION': {'num_fields': 8, 'type': 'action'},
 'tunnel_lookup_miss_MATCH': {'key_width': 2, 'type': 'match'},
 'urpf_bd_ACTION': {'num_fields': 1, 'type': 'action'},
 'urpf_bd_MATCH': {'key_width': 32, 'type': 'match'},
 'validate_mpls_packet_ACTION': {'num_fields': 2, 'type': 'action'},
 'validate_mpls_packet_MATCH': {'key_width': 66, 'type': 'match'},
 'validate_outer_ethernet_ACTION': {'num_fields': 3, 'type': 'action'},
 'validate_outer_ethernet_MATCH': {'key_width': 98, 'type': 'match'},
 'validate_outer_ipv4_packet_ACTION': {'num_fields': 3, 'type': 'action'},
 'validate_outer_ipv4_packet_MATCH': {'key_width': 20, 'type': 'match'},
 'validate_outer_ipv6_packet_ACTION': {'num_fields': 3, 'type': 'action'},
 'validate_outer_ipv6_packet_MATCH': {'key_width': 28, 'type': 'match'},
 'validate_packet_ACTION': {'num_fields': 3, 'type': 'action'},
 'validate_packet_MATCH': {'key_width': 134, 'type': 'match'}}

edges = \
{('_condition_0', '_condition_1'): {'delay': dS},
 ('_condition_0', 'validate_outer_ipv4_packet_ACTION'): {'delay': dS},
 ('_condition_1', '_condition_2'): {'delay': dS},
 ('_condition_1', 'validate_outer_ipv6_packet_ACTION'): {'delay': dS},
 ('_condition_10', '_condition_11'): {'delay': dS},
 ('_condition_10', '_condition_12'): {'delay': dS},
 ('_condition_11', 'fabric_ingress_src_lkp_ACTION'): {'delay': dS},
 ('_condition_12', 'ipv4_dest_vtep_ACTION'): {'delay': dS},
 ('_condition_12', 'ipv6_dest_vtep_ACTION'): {'delay': dS},
 ('_condition_12', 'mpls_ACTION'): {'delay': dS},
 ('_condition_12', 'native_packet_over_fabric_ACTION'): {'delay': dS},
 ('_condition_12', 'outer_ipv4_multicast_ACTION'): {'delay': dS},
 ('_condition_12', 'outer_ipv4_multicast_star_g_ACTION'): {'delay': dS},
 ('_condition_12', 'outer_ipv6_multicast_ACTION'): {'delay': dS},
 ('_condition_12', 'outer_ipv6_multicast_star_g_ACTION'): {'delay': dS},
 ('_condition_12', 'tunnel_ACTION'): {'delay': dS},
 ('_condition_13', 'mpls_ACTION'): {'delay': dS},
 ('_condition_13', 'outer_rmac_ACTION'): {'delay': dS},
 ('_condition_14', '_condition_15'): {'delay': dS},
 ('_condition_14', 'outer_ipv4_multicast_ACTION'): {'delay': dS},
 ('_condition_15', 'outer_ipv6_multicast_ACTION'): {'delay': dS},
 ('_condition_16', '_condition_17'): {'delay': dS},
 ('_condition_16', 'ipv4_src_vtep_ACTION'): {'delay': dS},
 ('_condition_17', '_condition_18'): {'delay': dS},
 ('_condition_17', 'ipv6_src_vtep_ACTION'): {'delay': dS},
 ('_condition_18', 'mpls_ACTION'): {'delay': dS},
 ('_condition_19', 'adjust_lkp_fields_ACTION'): {'delay': dS},
 ('_condition_19', 'ipv4_multicast_route_ACTION'): {'delay': dS},
 ('_condition_19', 'ipv4_multicast_route_star_g_ACTION'): {'delay': dS},
 ('_condition_19', 'ipv6_multicast_route_ACTION'): {'delay': dS},
 ('_condition_19', 'ipv6_multicast_route_star_g_ACTION'): {'delay': dS},
 ('_condition_19', 'tunnel_ACTION'): {'delay': dS},
 ('_condition_2', 'validate_mpls_packet_ACTION'): {'delay': dS},
 ('_condition_20', 'storm_control_ACTION'): {'delay': dS},
 ('_condition_21', '_condition_22'): {'delay': dS},
 ('_condition_22', '_condition_23'): {'delay': dS},
 ('_condition_22', '_condition_24'): {'delay': dS},
 ('_condition_22', '_condition_25'): {'delay': dS},
 ('_condition_22', '_condition_26'): {'delay': dS},
 ('_condition_22', 'ingress_l4_dst_port_ACTION'): {'delay': dS},
 ('_condition_22', 'ingress_l4_src_port_ACTION'): {'delay': dS},
 ('_condition_22', 'ipv4_fib_ACTION'): {'delay': dS},
 ('_condition_22', 'ipv4_fib_lpm_ACTION'): {'delay': dS},
 ('_condition_22', 'ipv6_fib_ACTION'): {'delay': dS},
 ('_condition_22', 'ipv6_fib_lpm_ACTION'): {'delay': dS},
 ('_condition_22', 'nat_twice_ACTION'): {'delay': dS},
 ('_condition_22', 'rmac_ACTION'): {'delay': dS},
 ('_condition_23', 'fwd_result_ACTION'): {'delay': dS},
 ('_condition_23', 'validate_packet_ACTION'): {'delay': dS},
 ('_condition_24', 'smac_ACTION'): {'delay': dS},
 ('_condition_25', 'dmac_ACTION'): {'delay': dS},
 ('_condition_26', '_condition_27'): {'delay': dS},
 ('_condition_26', '_condition_28'): {'delay': dS},
 ('_condition_27', 'mac_acl_ACTION'): {'delay': dS},
 ('_condition_28', '_condition_29'): {'delay': dS},
 ('_condition_29', '_condition_30'): {'delay': dS},
 ('_condition_29', 'ip_acl_ACTION'): {'delay': dS},
 ('_condition_3', 'spanning_tree_ACTION'): {'delay': dS},
 ('_condition_30', 'ipv6_acl_ACTION'): {'delay': dS},
 ('_condition_31', '_condition_32'): {'delay': dS},
 ('_condition_31', '_condition_33'): {'delay': dS},
 ('_condition_31', '_condition_34'): {'delay': dS},
 ('_condition_32', 'ipv4_multicast_bridge_ACTION'): {'delay': dS},
 ('_condition_33', 'ipv4_multicast_route_ACTION'): {'delay': dS},
 ('_condition_34', '_condition_35'): {'delay': dS},
 ('_condition_34', '_condition_36'): {'delay': dS},
 ('_condition_35', 'ipv6_multicast_bridge_ACTION'): {'delay': dS},
 ('_condition_36', 'ipv6_multicast_route_ACTION'): {'delay': dS},
 ('_condition_37', '_condition_38'): {'delay': dS},
 ('_condition_37', '_condition_42'): {'delay': dS},
 ('_condition_38', '_condition_39'): {'delay': dS},
 ('_condition_38', '_condition_40'): {'delay': dS},
 ('_condition_38', 'ipv4_fib_ACTION'): {'delay': dS},
 ('_condition_38', 'ipv4_racl_ACTION'): {'delay': dS},
 ('_condition_39', 'ipv4_urpf_ACTION'): {'delay': dS},
 ('_condition_4', '_condition_5'): {'delay': dS},
 ('_condition_40', '_condition_41'): {'delay': dS},
 ('_condition_40', 'ipv6_fib_ACTION'): {'delay': dS},
 ('_condition_40', 'ipv6_racl_ACTION'): {'delay': dS},
 ('_condition_41', 'ipv6_urpf_ACTION'): {'delay': dS},
 ('_condition_42', 'urpf_bd_ACTION'): {'delay': dS},
 ('_condition_43', 'meter_index_ACTION'): {'delay': dS},
 ('_condition_44', '_condition_45'): {'delay': dS},
 ('_condition_44', 'compute_ipv4_hashes_ACTION'): {'delay': dS},
 ('_condition_45', 'compute_ipv6_hashes_ACTION'): {'delay': dS},
 ('_condition_45', 'compute_non_ip_hashes_ACTION'): {'delay': dS},
 ('_condition_46', 'meter_action_ACTION'): {'delay': dS},
 ('_condition_47', '_condition_48'): {'delay': dS},
 ('_condition_47', '_condition_49'): {'delay': dS},
 ('_condition_47', '_condition_50'): {'delay': dS},
 ('_condition_47', '_condition_51'): {'delay': dS},
 ('_condition_47', 'acl_stats_ACTION'): {'delay': dS},
 ('_condition_47', 'ingress_bd_stats_ACTION'): {'delay': dS},
 ('_condition_47', 'storm_control_stats_ACTION'): {'delay': dS},
 ('_condition_48', 'fwd_result_ACTION'): {'delay': dS},
 ('_condition_49', 'ecmp_group_ACTION'): {'delay': dS},
 ('_condition_49', 'nexthop_ACTION'): {'delay': dS},
 ('_condition_5', '_condition_6'): {'delay': dS},
 ('_condition_5', 'ingress_qos_map_dscp_ACTION'): {'delay': dS},
 ('_condition_50', 'bd_flood_ACTION'): {'delay': dS},
 ('_condition_50', 'lag_group_ACTION'): {'delay': dS},
 ('_condition_51', 'learn_notify_ACTION'): {'delay': dS},
 ('_condition_52', '_condition_53'): {'delay': dS},
 ('_condition_53', '_condition_54'): {'delay': dS},
 ('_condition_53', 'system_acl_ACTION'): {'delay': dS},
 ('_condition_54', 'drop_stats_ACTION'): {'delay': dS},
 ('_condition_6', 'ingress_qos_map_pcp_ACTION'): {'delay': dS},
 ('_condition_7', 'ipsg_ACTION'): {'delay': dS},
 ('_condition_7', 'ipsg_permit_special_ACTION'): {'delay': dS},
 ('_condition_8', 'int_sink_update_outer_ACTION'): {'delay': dS},
 ('_condition_8', 'int_source_ACTION'): {'delay': dS},
 ('_condition_8', 'int_terminate_ACTION'): {'delay': dS},
 ('_condition_9', '_condition_10'): {'delay': dS},
 ('_condition_9', 'fabric_ingress_dst_lkp_ACTION'): {'delay': dS},
 ('adjust_lkp_fields_ACTION', 'compute_ipv4_hashes_ACTION'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'compute_ipv6_hashes_ACTION'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'compute_non_ip_hashes_ACTION'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'dmac_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'ingress_l4_dst_port_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'ingress_l4_src_port_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'ip_acl_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'ipv4_fib_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'ipv4_fib_lpm_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'ipv4_multicast_bridge_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'ipv4_multicast_bridge_star_g_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'ipv4_multicast_route_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'ipv4_multicast_route_star_g_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'ipv4_racl_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'ipv4_urpf_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'ipv4_urpf_lpm_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'ipv6_acl_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'ipv6_fib_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'ipv6_fib_lpm_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'ipv6_multicast_bridge_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'ipv6_multicast_bridge_star_g_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'ipv6_multicast_route_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'ipv6_multicast_route_star_g_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'ipv6_racl_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'ipv6_urpf_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'ipv6_urpf_lpm_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'learn_notify_ACTION'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'mac_acl_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'nat_dst_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'nat_flow_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'nat_src_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'nat_twice_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'rmac_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'smac_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_ACTION', 'validate_packet_MATCH'): {'delay': dA},
 ('adjust_lkp_fields_MATCH', 'adjust_lkp_fields_ACTION'): {'delay': dM},
 ('bd_flood_ACTION', 'fabric_lag_ACTION'): {'delay': dA},
 ('bd_flood_MATCH', 'bd_flood_ACTION'): {'delay': dM},
 ('compute_ipv4_hashes_ACTION', 'compute_other_hashes_MATCH'): {'delay': dA},
 ('compute_ipv4_hashes_ACTION', 'ecmp_group_MATCH'): {'delay': dA},
 ('compute_ipv4_hashes_ACTION', 'fabric_lag_MATCH'): {'delay': dA},
 ('compute_ipv4_hashes_ACTION', 'fwd_result_ACTION'): {'delay': dS},
 ('compute_ipv4_hashes_ACTION', 'lag_group_MATCH'): {'delay': dA},
 ('compute_ipv4_hashes_MATCH', 'compute_ipv4_hashes_ACTION'): {'delay': dM},
 ('compute_ipv6_hashes_ACTION', 'compute_other_hashes_MATCH'): {'delay': dA},
 ('compute_ipv6_hashes_ACTION', 'ecmp_group_MATCH'): {'delay': dA},
 ('compute_ipv6_hashes_ACTION', 'fabric_lag_MATCH'): {'delay': dA},
 ('compute_ipv6_hashes_ACTION', 'fwd_result_ACTION'): {'delay': dS},
 ('compute_ipv6_hashes_ACTION', 'lag_group_MATCH'): {'delay': dA},
 ('compute_ipv6_hashes_MATCH', 'compute_ipv6_hashes_ACTION'): {'delay': dM},
 ('compute_non_ip_hashes_ACTION', 'compute_other_hashes_ACTION'): {'delay': dA},
 ('compute_non_ip_hashes_ACTION', 'fabric_lag_MATCH'): {'delay': dA},
 ('compute_non_ip_hashes_ACTION', 'fwd_result_ACTION'): {'delay': dS},
 ('compute_non_ip_hashes_ACTION', 'lag_group_MATCH'): {'delay': dA},
 ('compute_non_ip_hashes_MATCH', 'compute_non_ip_hashes_ACTION'): {'delay': dM},
 ('compute_other_hashes_ACTION', 'ecmp_group_MATCH'): {'delay': dA},
 ('compute_other_hashes_MATCH', 'compute_other_hashes_ACTION'): {'delay': dM},
 ('dmac_ACTION', '_condition_50'): {'delay': dA},
 ('dmac_ACTION', 'bd_flood_ACTION'): {'delay': dA},
 ('dmac_ACTION', 'ecmp_group_ACTION'): {'delay': dA},
 ('dmac_ACTION', 'fabric_lag_MATCH'): {'delay': dA},
 ('dmac_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('dmac_ACTION', 'lag_group_MATCH'): {'delay': dA},
 ('dmac_ACTION', 'nexthop_ACTION'): {'delay': dA},
 ('dmac_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('dmac_MATCH', 'dmac_ACTION'): {'delay': dM},
 ('ecmp_group_ACTION', '_condition_50'): {'delay': dA},
 ('ecmp_group_ACTION', 'bd_flood_ACTION'): {'delay': dA},
 ('ecmp_group_ACTION', 'fabric_lag_MATCH'): {'delay': dA},
 ('ecmp_group_ACTION', 'lag_group_MATCH'): {'delay': dA},
 ('ecmp_group_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('ecmp_group_MATCH', 'ecmp_group_ACTION'): {'delay': dM},
 ('fabric_ingress_dst_lkp_ACTION', '_condition_11'): {'delay': dA},
 ('fabric_ingress_dst_lkp_ACTION', '_condition_12'): {'delay': dA},
 ('fabric_ingress_dst_lkp_ACTION', '_condition_13'): {'delay': dA},
 ('fabric_ingress_dst_lkp_ACTION', '_condition_19'): {'delay': dA},
 ('fabric_ingress_dst_lkp_ACTION', '_condition_44'): {'delay': dA},
 ('fabric_ingress_dst_lkp_ACTION', '_condition_45'): {'delay': dA},
 ('fabric_ingress_dst_lkp_ACTION', 'bd_flood_ACTION'): {'delay': dA},
 ('fabric_ingress_dst_lkp_ACTION', 'dmac_ACTION'): {'delay': dA},
 ('fabric_ingress_dst_lkp_ACTION', 'ecmp_group_MATCH'): {'delay': dA},
 ('fabric_ingress_dst_lkp_ACTION', 'fabric_ingress_src_lkp_MATCH'): {'delay': dA},
 ('fabric_ingress_dst_lkp_ACTION', 'fabric_lag_MATCH'): {'delay': dA},
 ('fabric_ingress_dst_lkp_ACTION', 'fwd_result_ACTION'): {'delay': dA},
 ('fabric_ingress_dst_lkp_ACTION', 'ipv4_dest_vtep_MATCH'): {'delay': dA},
 ('fabric_ingress_dst_lkp_ACTION', 'ipv4_src_vtep_MATCH'): {'delay': dA},
 ('fabric_ingress_dst_lkp_ACTION', 'ipv6_dest_vtep_MATCH'): {'delay': dA},
 ('fabric_ingress_dst_lkp_ACTION', 'ipv6_src_vtep_MATCH'): {'delay': dA},
 ('fabric_ingress_dst_lkp_ACTION', 'lag_group_ACTION'): {'delay': dA},
 ('fabric_ingress_dst_lkp_ACTION', 'mpls_ACTION'): {'delay': dA},
 ('fabric_ingress_dst_lkp_ACTION', 'native_packet_over_fabric_ACTION'): {'delay': dA},
 ('fabric_ingress_dst_lkp_ACTION', 'nexthop_MATCH'): {'delay': dA},
 ('fabric_ingress_dst_lkp_ACTION', 'outer_ipv4_multicast_ACTION'): {'delay': dA},
 ('fabric_ingress_dst_lkp_ACTION', 'outer_ipv4_multicast_star_g_ACTION'): {'delay': dA},
 ('fabric_ingress_dst_lkp_ACTION', 'outer_ipv6_multicast_ACTION'): {'delay': dA},
 ('fabric_ingress_dst_lkp_ACTION', 'outer_ipv6_multicast_star_g_ACTION'): {'delay': dA},
 ('fabric_ingress_dst_lkp_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('fabric_ingress_dst_lkp_ACTION', 'tunnel_MATCH'): {'delay': dA},
 ('fabric_ingress_dst_lkp_MATCH', 'fabric_ingress_dst_lkp_ACTION'): {'delay': dM},
 ('fabric_ingress_src_lkp_MATCH', 'fabric_ingress_src_lkp_ACTION'): {'delay': dM},
 ('fabric_lag_ACTION', 'system_acl_ACTION'): {'delay': dS},
 ('fabric_lag_MATCH', 'fabric_lag_ACTION'): {'delay': dM},
 ('fwd_result_ACTION', '_condition_49'): {'delay': dA},
 ('fwd_result_ACTION', '_condition_50'): {'delay': dA},
 ('fwd_result_ACTION', '_condition_54'): {'delay': dA},
 ('fwd_result_ACTION', 'bd_flood_ACTION'): {'delay': dA},
 ('fwd_result_ACTION', 'drop_stats_ACTION'): {'delay': dA},
 ('fwd_result_ACTION', 'ecmp_group_MATCH'): {'delay': dA},
 ('fwd_result_ACTION', 'fabric_lag_MATCH'): {'delay': dA},
 ('fwd_result_ACTION', 'lag_group_MATCH'): {'delay': dA},
 ('fwd_result_ACTION', 'nexthop_MATCH'): {'delay': dA},
 ('fwd_result_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('fwd_result_MATCH', 'fwd_result_ACTION'): {'delay': dM},
 ('ingress_l4_dst_port_ACTION', 'ip_acl_MATCH'): {'delay': dA},
 ('ingress_l4_dst_port_ACTION', 'ipv4_racl_MATCH'): {'delay': dA},
 ('ingress_l4_dst_port_ACTION', 'ipv6_acl_MATCH'): {'delay': dA},
 ('ingress_l4_dst_port_ACTION', 'ipv6_racl_MATCH'): {'delay': dA},
 ('ingress_l4_dst_port_MATCH', 'ingress_l4_dst_port_ACTION'): {'delay': dM},
 ('ingress_l4_src_port_ACTION', 'ip_acl_MATCH'): {'delay': dA},
 ('ingress_l4_src_port_ACTION', 'ipv4_racl_MATCH'): {'delay': dA},
 ('ingress_l4_src_port_ACTION', 'ipv6_acl_MATCH'): {'delay': dA},
 ('ingress_l4_src_port_ACTION', 'ipv6_racl_MATCH'): {'delay': dA},
 ('ingress_l4_src_port_MATCH', 'ingress_l4_src_port_ACTION'): {'delay': dM},
 ('ingress_port_mapping_ACTION', '_condition_10'): {'delay': dA},
 ('ingress_port_mapping_ACTION', '_condition_20'): {'delay': dA},
 ('ingress_port_mapping_ACTION', '_condition_21'): {'delay': dA},
 ('ingress_port_mapping_ACTION', '_condition_24'): {'delay': dA},
 ('ingress_port_mapping_ACTION', '_condition_3'): {'delay': dA},
 ('ingress_port_mapping_ACTION', '_condition_47'): {'delay': dA},
 ('ingress_port_mapping_ACTION', '_condition_52'): {'delay': dA},
 ('ingress_port_mapping_ACTION', '_condition_7'): {'delay': dA},
 ('ingress_port_mapping_ACTION', '_condition_9'): {'delay': dA},
 ('ingress_port_mapping_ACTION', 'compute_non_ip_hashes_ACTION'): {'delay': dA},
 ('ingress_port_mapping_ACTION', 'ipsg_MATCH'): {'delay': dA},
 ('ingress_port_mapping_ACTION', 'ipv4_src_vtep_ACTION'): {'delay': dA},
 ('ingress_port_mapping_ACTION', 'ipv6_src_vtep_ACTION'): {'delay': dA},
 ('ingress_port_mapping_ACTION', 'learn_notify_ACTION'): {'delay': dA},
 ('ingress_port_mapping_ACTION', 'port_vlan_mapping_MATCH'): {'delay': dA},
 ('ingress_port_mapping_ACTION', 'sflow_ing_take_sample_ACTION'): {'delay': dA},
 ('ingress_port_mapping_ACTION', 'sflow_ingress_MATCH'): {'delay': dA},
 ('ingress_port_mapping_ACTION', 'smac_ACTION'): {'delay': dA},
 ('ingress_port_mapping_ACTION', 'spanning_tree_MATCH'): {'delay': dA},
 ('ingress_port_mapping_ACTION', 'switch_config_params_ACTION'): {'delay': dA},
 ('ingress_port_mapping_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('ingress_port_mapping_MATCH', 'ingress_port_mapping_ACTION'): {'delay': dM},
 ('ingress_port_properties_ACTION', '_condition_5'): {'delay': dA},
 ('ingress_port_properties_ACTION', '_condition_6'): {'delay': dA},
 ('ingress_port_properties_ACTION', 'ingress_qos_map_dscp_MATCH'): {'delay': dA},
 ('ingress_port_properties_ACTION', 'ingress_qos_map_pcp_MATCH'): {'delay': dA},
 ('ingress_port_properties_ACTION', 'ip_acl_MATCH'): {'delay': dA},
 ('ingress_port_properties_ACTION', 'ipv4_racl_ACTION'): {'delay': dA},
 ('ingress_port_properties_ACTION', 'ipv6_acl_MATCH'): {'delay': dA},
 ('ingress_port_properties_ACTION', 'ipv6_racl_ACTION'): {'delay': dA},
 ('ingress_port_properties_ACTION', 'mac_acl_MATCH'): {'delay': dA},
 ('ingress_port_properties_ACTION', 'meter_action_MATCH'): {'delay': dA},
 ('ingress_port_properties_ACTION', 'meter_index_ACTION'): {'delay': dA},
 ('ingress_port_properties_ACTION', 'storm_control_ACTION'): {'delay': dA},
 ('ingress_port_properties_ACTION', 'storm_control_stats_MATCH'): {'delay': dA},
 ('ingress_port_properties_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('ingress_port_properties_ACTION', 'traffic_class_MATCH'): {'delay': dA},
 ('ingress_port_properties_MATCH', 'ingress_port_properties_ACTION'): {'delay': dM},
 ('ingress_qos_map_dscp_ACTION', 'ip_acl_ACTION'): {'delay': dA},
 ('ingress_qos_map_dscp_ACTION', 'ipv4_racl_ACTION'): {'delay': dA},
 ('ingress_qos_map_dscp_ACTION', 'ipv6_acl_ACTION'): {'delay': dA},
 ('ingress_qos_map_dscp_ACTION', 'ipv6_racl_ACTION'): {'delay': dA},
 ('ingress_qos_map_dscp_ACTION', 'mac_acl_ACTION'): {'delay': dA},
 ('ingress_qos_map_dscp_ACTION', 'meter_action_MATCH'): {'delay': dA},
 ('ingress_qos_map_dscp_ACTION', 'meter_index_ACTION'): {'delay': dA},
 ('ingress_qos_map_dscp_ACTION', 'storm_control_ACTION'): {'delay': dA},
 ('ingress_qos_map_dscp_ACTION', 'storm_control_stats_MATCH'): {'delay': dA},
 ('ingress_qos_map_dscp_ACTION', 'traffic_class_MATCH'): {'delay': dA},
 ('ingress_qos_map_dscp_MATCH', 'ingress_qos_map_dscp_ACTION'): {'delay': dM},
 ('ingress_qos_map_pcp_ACTION', 'ip_acl_ACTION'): {'delay': dA},
 ('ingress_qos_map_pcp_ACTION', 'ipv4_racl_ACTION'): {'delay': dA},
 ('ingress_qos_map_pcp_ACTION', 'ipv6_acl_ACTION'): {'delay': dA},
 ('ingress_qos_map_pcp_ACTION', 'ipv6_racl_ACTION'): {'delay': dA},
 ('ingress_qos_map_pcp_ACTION', 'mac_acl_ACTION'): {'delay': dA},
 ('ingress_qos_map_pcp_ACTION', 'meter_action_MATCH'): {'delay': dA},
 ('ingress_qos_map_pcp_ACTION', 'meter_index_ACTION'): {'delay': dA},
 ('ingress_qos_map_pcp_ACTION', 'storm_control_ACTION'): {'delay': dA},
 ('ingress_qos_map_pcp_ACTION', 'storm_control_stats_MATCH'): {'delay': dA},
 ('ingress_qos_map_pcp_ACTION', 'traffic_class_MATCH'): {'delay': dA},
 ('ingress_qos_map_pcp_MATCH', 'ingress_qos_map_pcp_ACTION'): {'delay': dM},
 ('int_sink_update_outer_MATCH', 'int_sink_update_outer_ACTION'): {'delay': dM},
 ('int_source_ACTION', 'adjust_lkp_fields_ACTION'): {'delay': dS},
 ('int_source_ACTION', 'native_packet_over_fabric_ACTION'): {'delay': dS},
 ('int_source_ACTION', 'tunnel_lookup_miss_ACTION'): {'delay': dS},
 ('int_source_MATCH', 'int_source_ACTION'): {'delay': dM},
 ('int_terminate_ACTION', 'adjust_lkp_fields_ACTION'): {'delay': dS},
 ('int_terminate_ACTION', 'int_sink_update_outer_MATCH'): {'delay': dA},
 ('int_terminate_ACTION', 'ip_acl_ACTION'): {'delay': dA},
 ('int_terminate_ACTION', 'ipv6_acl_ACTION'): {'delay': dA},
 ('int_terminate_ACTION', 'mac_acl_ACTION'): {'delay': dA},
 ('int_terminate_ACTION', 'native_packet_over_fabric_ACTION'): {'delay': dS},
 ('int_terminate_ACTION', 'sflow_ing_take_sample_ACTION'): {'delay': dA},
 ('int_terminate_ACTION', 'tunnel_lookup_miss_ACTION'): {'delay': dS},
 ('int_terminate_MATCH', 'int_terminate_ACTION'): {'delay': dM},
 ('ip_acl_ACTION', 'acl_stats_ACTION'): {'delay': dA},
 ('ip_acl_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('ip_acl_ACTION', 'ipv4_racl_ACTION'): {'delay': dA},
 ('ip_acl_ACTION', 'ipv6_racl_ACTION'): {'delay': dA},
 ('ip_acl_ACTION', 'meter_action_MATCH'): {'delay': dA},
 ('ip_acl_ACTION', 'meter_index_MATCH'): {'delay': dA},
 ('ip_acl_ACTION', 'storm_control_stats_MATCH'): {'delay': dA},
 ('ip_acl_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('ip_acl_ACTION', 'traffic_class_MATCH'): {'delay': dA},
 ('ip_acl_MATCH', 'ip_acl_ACTION'): {'delay': dM},
 ('ipsg_ACTION', 'adjust_lkp_fields_ACTION'): {'delay': dS},
 ('ipsg_ACTION', 'ipv4_src_vtep_ACTION'): {'delay': dS},
 ('ipsg_ACTION', 'ipv6_src_vtep_ACTION'): {'delay': dS},
 ('ipsg_ACTION', 'mpls_ACTION'): {'delay': dS},
 ('ipsg_ACTION', 'native_packet_over_fabric_ACTION'): {'delay': dS},
 ('ipsg_ACTION', 'tunnel_ACTION'): {'delay': dS},
 ('ipsg_ACTION', 'tunnel_lookup_miss_ACTION'): {'delay': dS},
 ('ipsg_MATCH', 'ipsg_ACTION'): {'delay': dM},
 ('ipsg_permit_special_ACTION', 'adjust_lkp_fields_ACTION'): {'delay': dS},
 ('ipsg_permit_special_ACTION', 'native_packet_over_fabric_ACTION'): {'delay': dS},
 ('ipsg_permit_special_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('ipsg_permit_special_ACTION', 'tunnel_lookup_miss_ACTION'): {'delay': dS},
 ('ipsg_permit_special_MATCH', 'ipsg_permit_special_ACTION'): {'delay': dM},
 ('ipv4_dest_vtep_ACTION', '_condition_19'): {'delay': dA},
 ('ipv4_dest_vtep_ACTION', '_condition_44'): {'delay': dA},
 ('ipv4_dest_vtep_ACTION', '_condition_45'): {'delay': dA},
 ('ipv4_dest_vtep_ACTION', 'ecmp_group_ACTION'): {'delay': dA},
 ('ipv4_dest_vtep_ACTION', 'nexthop_ACTION'): {'delay': dA},
 ('ipv4_dest_vtep_ACTION', 'tunnel_MATCH'): {'delay': dA},
 ('ipv4_dest_vtep_MATCH', 'ipv4_dest_vtep_ACTION'): {'delay': dM},
 ('ipv4_fib_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('ipv4_fib_MATCH', 'ipv4_fib_ACTION'): {'delay': dM},
 ('ipv4_fib_MATCH', 'ipv4_fib_lpm_ACTION'): {'delay': dM},
 ('ipv4_fib_lpm_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('ipv4_fib_lpm_MATCH', 'ipv4_fib_lpm_ACTION'): {'delay': dM},
 ('ipv4_multicast_bridge_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('ipv4_multicast_bridge_MATCH', 'ipv4_multicast_bridge_ACTION'): {'delay': dM},
 ('ipv4_multicast_bridge_MATCH', 'ipv4_multicast_bridge_star_g_ACTION'): {'delay': dM},
 ('ipv4_multicast_bridge_star_g_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('ipv4_multicast_bridge_star_g_MATCH', 'ipv4_multicast_bridge_star_g_ACTION'): {'delay': dM},
 ('ipv4_multicast_route_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('ipv4_multicast_route_MATCH', 'ipv4_multicast_route_ACTION'): {'delay': dM},
 ('ipv4_multicast_route_MATCH', 'ipv4_multicast_route_star_g_ACTION'): {'delay': dM},
 ('ipv4_multicast_route_star_g_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('ipv4_multicast_route_star_g_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('ipv4_multicast_route_star_g_MATCH', 'ipv4_multicast_route_star_g_ACTION'): {'delay': dM},
 ('ipv4_racl_ACTION', 'acl_stats_ACTION'): {'delay': dA},
 ('ipv4_racl_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('ipv4_racl_ACTION', 'meter_action_MATCH'): {'delay': dA},
 ('ipv4_racl_ACTION', 'meter_index_ACTION'): {'delay': dA},
 ('ipv4_racl_ACTION', 'storm_control_stats_MATCH'): {'delay': dA},
 ('ipv4_racl_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('ipv4_racl_ACTION', 'traffic_class_MATCH'): {'delay': dA},
 ('ipv4_racl_MATCH', 'ipv4_racl_ACTION'): {'delay': dM},
 ('ipv4_src_vtep_ACTION', 'compute_non_ip_hashes_ACTION'): {'delay': dA},
 ('ipv4_src_vtep_ACTION', 'learn_notify_ACTION'): {'delay': dA},
 ('ipv4_src_vtep_ACTION', 'smac_ACTION'): {'delay': dA},
 ('ipv4_src_vtep_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('ipv4_src_vtep_ACTION', 'tunnel_ACTION'): {'delay': dS},
 ('ipv4_src_vtep_MATCH', 'ipv4_dest_vtep_ACTION'): {'delay': dM},
 ('ipv4_src_vtep_MATCH', 'ipv4_src_vtep_ACTION'): {'delay': dM},
 ('ipv4_urpf_ACTION', '_condition_42'): {'delay': dA},
 ('ipv4_urpf_ACTION', 'urpf_bd_MATCH'): {'delay': dA},
 ('ipv4_urpf_MATCH', 'ipv4_urpf_ACTION'): {'delay': dM},
 ('ipv4_urpf_MATCH', 'ipv4_urpf_lpm_ACTION'): {'delay': dM},
 ('ipv4_urpf_lpm_ACTION', '_condition_42'): {'delay': dA},
 ('ipv4_urpf_lpm_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('ipv4_urpf_lpm_ACTION', 'urpf_bd_MATCH'): {'delay': dA},
 ('ipv4_urpf_lpm_MATCH', 'ipv4_urpf_lpm_ACTION'): {'delay': dM},
 ('ipv6_acl_ACTION', 'acl_stats_ACTION'): {'delay': dA},
 ('ipv6_acl_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('ipv6_acl_ACTION', 'ipv4_racl_ACTION'): {'delay': dA},
 ('ipv6_acl_ACTION', 'ipv6_racl_ACTION'): {'delay': dA},
 ('ipv6_acl_ACTION', 'meter_action_MATCH'): {'delay': dA},
 ('ipv6_acl_ACTION', 'meter_index_MATCH'): {'delay': dA},
 ('ipv6_acl_ACTION', 'storm_control_stats_MATCH'): {'delay': dA},
 ('ipv6_acl_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('ipv6_acl_ACTION', 'traffic_class_MATCH'): {'delay': dA},
 ('ipv6_acl_MATCH', 'ipv6_acl_ACTION'): {'delay': dM},
 ('ipv6_dest_vtep_ACTION', '_condition_19'): {'delay': dA},
 ('ipv6_dest_vtep_ACTION', '_condition_44'): {'delay': dA},
 ('ipv6_dest_vtep_ACTION', '_condition_45'): {'delay': dA},
 ('ipv6_dest_vtep_ACTION', 'ecmp_group_ACTION'): {'delay': dA},
 ('ipv6_dest_vtep_ACTION', 'nexthop_ACTION'): {'delay': dA},
 ('ipv6_dest_vtep_ACTION', 'tunnel_MATCH'): {'delay': dA},
 ('ipv6_dest_vtep_MATCH', 'ipv6_dest_vtep_ACTION'): {'delay': dM},
 ('ipv6_fib_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('ipv6_fib_MATCH', 'ipv6_fib_ACTION'): {'delay': dM},
 ('ipv6_fib_MATCH', 'ipv6_fib_lpm_ACTION'): {'delay': dM},
 ('ipv6_fib_lpm_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('ipv6_fib_lpm_MATCH', 'ipv6_fib_lpm_ACTION'): {'delay': dM},
 ('ipv6_multicast_bridge_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('ipv6_multicast_bridge_MATCH', 'ipv6_multicast_bridge_ACTION'): {'delay': dM},
 ('ipv6_multicast_bridge_MATCH', 'ipv6_multicast_bridge_star_g_ACTION'): {'delay': dM},
 ('ipv6_multicast_bridge_star_g_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('ipv6_multicast_bridge_star_g_MATCH', 'ipv6_multicast_bridge_star_g_ACTION'): {'delay': dM},
 ('ipv6_multicast_route_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('ipv6_multicast_route_MATCH', 'ipv6_multicast_route_ACTION'): {'delay': dM},
 ('ipv6_multicast_route_MATCH', 'ipv6_multicast_route_star_g_ACTION'): {'delay': dM},
 ('ipv6_multicast_route_star_g_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('ipv6_multicast_route_star_g_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('ipv6_multicast_route_star_g_MATCH', 'ipv6_multicast_route_star_g_ACTION'): {'delay': dM},
 ('ipv6_racl_ACTION', 'acl_stats_ACTION'): {'delay': dA},
 ('ipv6_racl_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('ipv6_racl_ACTION', 'meter_action_MATCH'): {'delay': dA},
 ('ipv6_racl_ACTION', 'meter_index_ACTION'): {'delay': dA},
 ('ipv6_racl_ACTION', 'storm_control_stats_MATCH'): {'delay': dA},
 ('ipv6_racl_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('ipv6_racl_ACTION', 'traffic_class_MATCH'): {'delay': dA},
 ('ipv6_racl_MATCH', 'ipv6_racl_ACTION'): {'delay': dM},
 ('ipv6_src_vtep_ACTION', 'compute_non_ip_hashes_ACTION'): {'delay': dA},
 ('ipv6_src_vtep_ACTION', 'learn_notify_ACTION'): {'delay': dA},
 ('ipv6_src_vtep_ACTION', 'smac_ACTION'): {'delay': dA},
 ('ipv6_src_vtep_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('ipv6_src_vtep_ACTION', 'tunnel_ACTION'): {'delay': dS},
 ('ipv6_src_vtep_MATCH', 'ipv6_dest_vtep_ACTION'): {'delay': dM},
 ('ipv6_src_vtep_MATCH', 'ipv6_src_vtep_ACTION'): {'delay': dM},
 ('ipv6_urpf_ACTION', '_condition_42'): {'delay': dA},
 ('ipv6_urpf_ACTION', 'urpf_bd_MATCH'): {'delay': dA},
 ('ipv6_urpf_MATCH', 'ipv6_urpf_ACTION'): {'delay': dM},
 ('ipv6_urpf_MATCH', 'ipv6_urpf_lpm_ACTION'): {'delay': dM},
 ('ipv6_urpf_lpm_ACTION', '_condition_42'): {'delay': dA},
 ('ipv6_urpf_lpm_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('ipv6_urpf_lpm_ACTION', 'urpf_bd_MATCH'): {'delay': dA},
 ('ipv6_urpf_lpm_MATCH', 'ipv6_urpf_lpm_ACTION'): {'delay': dM},
 ('lag_group_ACTION', 'fabric_lag_MATCH'): {'delay': dA},
 ('lag_group_ACTION', 'system_acl_ACTION'): {'delay': dA},
 ('lag_group_MATCH', 'lag_group_ACTION'): {'delay': dM},
 ('learn_notify_MATCH', 'learn_notify_ACTION'): {'delay': dM},
 ('mac_acl_ACTION', 'acl_stats_ACTION'): {'delay': dA},
 ('mac_acl_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('mac_acl_ACTION', 'ipv4_racl_ACTION'): {'delay': dA},
 ('mac_acl_ACTION', 'ipv6_racl_ACTION'): {'delay': dA},
 ('mac_acl_ACTION', 'meter_action_MATCH'): {'delay': dA},
 ('mac_acl_ACTION', 'meter_index_MATCH'): {'delay': dA},
 ('mac_acl_ACTION', 'storm_control_stats_MATCH'): {'delay': dA},
 ('mac_acl_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('mac_acl_ACTION', 'traffic_class_MATCH'): {'delay': dA},
 ('mac_acl_MATCH', 'mac_acl_ACTION'): {'delay': dM},
 ('meter_action_MATCH', 'meter_action_ACTION'): {'delay': dM},
 ('meter_index_ACTION', 'meter_action_MATCH'): {'delay': dA},
 ('meter_index_ACTION', 'storm_control_stats_MATCH'): {'delay': dA},
 ('meter_index_MATCH', 'meter_index_ACTION'): {'delay': dM},
 ('mpls_ACTION', '_condition_19'): {'delay': dA},
 ('mpls_ACTION', '_condition_22'): {'delay': dA},
 ('mpls_ACTION', '_condition_26'): {'delay': dA},
 ('mpls_ACTION', '_condition_29'): {'delay': dA},
 ('mpls_ACTION', '_condition_30'): {'delay': dA},
 ('mpls_ACTION', '_condition_31'): {'delay': dA},
 ('mpls_ACTION', '_condition_34'): {'delay': dA},
 ('mpls_ACTION', '_condition_38'): {'delay': dA},
 ('mpls_ACTION', '_condition_40'): {'delay': dA},
 ('mpls_ACTION', '_condition_44'): {'delay': dA},
 ('mpls_ACTION', '_condition_45'): {'delay': dA},
 ('mpls_ACTION', '_condition_50'): {'delay': dA},
 ('mpls_ACTION', 'adjust_lkp_fields_ACTION'): {'delay': dA},
 ('mpls_ACTION', 'bd_flood_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'compute_ipv4_hashes_ACTION'): {'delay': dA},
 ('mpls_ACTION', 'compute_ipv6_hashes_ACTION'): {'delay': dA},
 ('mpls_ACTION', 'compute_non_ip_hashes_ACTION'): {'delay': dA},
 ('mpls_ACTION', 'dmac_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'ecmp_group_ACTION'): {'delay': dA},
 ('mpls_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'ipv4_fib_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'ipv4_fib_lpm_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'ipv4_multicast_bridge_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'ipv4_multicast_bridge_star_g_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'ipv4_multicast_route_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'ipv4_multicast_route_star_g_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'ipv4_urpf_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'ipv4_urpf_lpm_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'ipv6_fib_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'ipv6_fib_lpm_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'ipv6_multicast_bridge_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'ipv6_multicast_bridge_star_g_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'ipv6_multicast_route_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'ipv6_multicast_route_star_g_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'ipv6_urpf_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'ipv6_urpf_lpm_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'lag_group_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'learn_notify_ACTION'): {'delay': dA},
 ('mpls_ACTION', 'mac_acl_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'nat_dst_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'nat_flow_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'nat_src_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'nat_twice_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'nexthop_ACTION'): {'delay': dA},
 ('mpls_ACTION', 'rmac_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'smac_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'tunnel_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'tunnel_lookup_miss_ACTION'): {'delay': dA},
 ('mpls_ACTION', 'urpf_bd_MATCH'): {'delay': dA},
 ('mpls_ACTION', 'validate_packet_MATCH'): {'delay': dA},
 ('mpls_MATCH', 'mpls_ACTION'): {'delay': dM},
 ('nat_dst_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('nat_dst_MATCH', 'nat_dst_ACTION'): {'delay': dM},
 ('nat_dst_MATCH', 'nat_src_ACTION'): {'delay': dM},
 ('nat_flow_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('nat_flow_MATCH', 'nat_flow_ACTION'): {'delay': dM},
 ('nat_src_MATCH', 'nat_flow_ACTION'): {'delay': dM},
 ('nat_src_MATCH', 'nat_src_ACTION'): {'delay': dM},
 ('nat_twice_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('nat_twice_MATCH', 'nat_dst_ACTION'): {'delay': dM},
 ('nat_twice_MATCH', 'nat_twice_ACTION'): {'delay': dM},
 ('native_packet_over_fabric_ACTION', 'adjust_lkp_fields_ACTION'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'compute_ipv4_hashes_ACTION'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'compute_ipv6_hashes_ACTION'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'compute_non_ip_hashes_ACTION'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'dmac_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'ingress_l4_dst_port_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'ingress_l4_src_port_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'ip_acl_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'ipv4_fib_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'ipv4_fib_lpm_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'ipv4_multicast_bridge_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'ipv4_multicast_bridge_star_g_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'ipv4_multicast_route_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'ipv4_multicast_route_star_g_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'ipv4_racl_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'ipv4_urpf_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'ipv4_urpf_lpm_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'ipv6_acl_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'ipv6_fib_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'ipv6_fib_lpm_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'ipv6_multicast_bridge_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'ipv6_multicast_bridge_star_g_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'ipv6_multicast_route_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'ipv6_multicast_route_star_g_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'ipv6_racl_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'ipv6_urpf_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'ipv6_urpf_lpm_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'learn_notify_ACTION'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'mac_acl_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'mpls_ACTION'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'nat_dst_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'nat_flow_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'nat_src_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'nat_twice_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'rmac_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'smac_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'tunnel_ACTION'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'tunnel_lookup_miss_ACTION'): {'delay': dA},
 ('native_packet_over_fabric_ACTION', 'validate_packet_MATCH'): {'delay': dA},
 ('native_packet_over_fabric_MATCH', 'native_packet_over_fabric_ACTION'): {'delay': dM},
 ('nexthop_ACTION', '_condition_50'): {'delay': dA},
 ('nexthop_ACTION', 'bd_flood_ACTION'): {'delay': dA},
 ('nexthop_ACTION', 'fabric_lag_MATCH'): {'delay': dA},
 ('nexthop_ACTION', 'lag_group_MATCH'): {'delay': dA},
 ('nexthop_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('nexthop_MATCH', 'nexthop_ACTION'): {'delay': dM},
 ('outer_ipv4_multicast_ACTION', '_condition_19'): {'delay': dA},
 ('outer_ipv4_multicast_ACTION', '_condition_44'): {'delay': dA},
 ('outer_ipv4_multicast_ACTION', '_condition_45'): {'delay': dA},
 ('outer_ipv4_multicast_ACTION', 'bd_flood_ACTION'): {'delay': dA},
 ('outer_ipv4_multicast_ACTION', 'dmac_ACTION'): {'delay': dA},
 ('outer_ipv4_multicast_ACTION', 'ecmp_group_ACTION'): {'delay': dA},
 ('outer_ipv4_multicast_ACTION', 'fabric_lag_MATCH'): {'delay': dA},
 ('outer_ipv4_multicast_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('outer_ipv4_multicast_ACTION', 'ipv4_multicast_route_ACTION'): {'delay': dA},
 ('outer_ipv4_multicast_ACTION', 'ipv4_multicast_route_star_g_ACTION'): {'delay': dA},
 ('outer_ipv4_multicast_ACTION', 'ipv6_multicast_route_ACTION'): {'delay': dA},
 ('outer_ipv4_multicast_ACTION', 'ipv6_multicast_route_star_g_ACTION'): {'delay': dA},
 ('outer_ipv4_multicast_ACTION', 'lag_group_ACTION'): {'delay': dA},
 ('outer_ipv4_multicast_ACTION', 'nexthop_ACTION'): {'delay': dA},
 ('outer_ipv4_multicast_ACTION', 'system_acl_ACTION'): {'delay': dA},
 ('outer_ipv4_multicast_ACTION', 'tunnel_ACTION'): {'delay': dA},
 ('outer_ipv4_multicast_MATCH', 'outer_ipv4_multicast_ACTION'): {'delay': dM},
 ('outer_ipv4_multicast_MATCH', 'outer_ipv4_multicast_star_g_ACTION'): {'delay': dM},
 ('outer_ipv4_multicast_star_g_ACTION', '_condition_19'): {'delay': dA},
 ('outer_ipv4_multicast_star_g_ACTION', '_condition_44'): {'delay': dA},
 ('outer_ipv4_multicast_star_g_ACTION', '_condition_45'): {'delay': dA},
 ('outer_ipv4_multicast_star_g_ACTION', 'bd_flood_ACTION'): {'delay': dA},
 ('outer_ipv4_multicast_star_g_ACTION', 'dmac_ACTION'): {'delay': dA},
 ('outer_ipv4_multicast_star_g_ACTION', 'ecmp_group_ACTION'): {'delay': dA},
 ('outer_ipv4_multicast_star_g_ACTION', 'fabric_lag_MATCH'): {'delay': dA},
 ('outer_ipv4_multicast_star_g_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('outer_ipv4_multicast_star_g_ACTION', 'ipv4_multicast_route_ACTION'): {'delay': dA},
 ('outer_ipv4_multicast_star_g_ACTION', 'ipv4_multicast_route_star_g_ACTION'): {'delay': dA},
 ('outer_ipv4_multicast_star_g_ACTION', 'ipv6_multicast_route_ACTION'): {'delay': dA},
 ('outer_ipv4_multicast_star_g_ACTION', 'ipv6_multicast_route_star_g_ACTION'): {'delay': dA},
 ('outer_ipv4_multicast_star_g_ACTION', 'lag_group_ACTION'): {'delay': dA},
 ('outer_ipv4_multicast_star_g_ACTION', 'nexthop_ACTION'): {'delay': dA},
 ('outer_ipv4_multicast_star_g_ACTION', 'system_acl_ACTION'): {'delay': dA},
 ('outer_ipv4_multicast_star_g_ACTION', 'tunnel_ACTION'): {'delay': dA},
 ('outer_ipv4_multicast_star_g_MATCH', 'outer_ipv4_multicast_star_g_ACTION'): {'delay': dM},
 ('outer_ipv6_multicast_ACTION', '_condition_19'): {'delay': dA},
 ('outer_ipv6_multicast_ACTION', '_condition_44'): {'delay': dA},
 ('outer_ipv6_multicast_ACTION', '_condition_45'): {'delay': dA},
 ('outer_ipv6_multicast_ACTION', 'bd_flood_ACTION'): {'delay': dA},
 ('outer_ipv6_multicast_ACTION', 'dmac_ACTION'): {'delay': dA},
 ('outer_ipv6_multicast_ACTION', 'ecmp_group_ACTION'): {'delay': dA},
 ('outer_ipv6_multicast_ACTION', 'fabric_lag_MATCH'): {'delay': dA},
 ('outer_ipv6_multicast_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('outer_ipv6_multicast_ACTION', 'ipv4_multicast_route_ACTION'): {'delay': dA},
 ('outer_ipv6_multicast_ACTION', 'ipv4_multicast_route_star_g_ACTION'): {'delay': dA},
 ('outer_ipv6_multicast_ACTION', 'ipv6_multicast_route_ACTION'): {'delay': dA},
 ('outer_ipv6_multicast_ACTION', 'ipv6_multicast_route_star_g_ACTION'): {'delay': dA},
 ('outer_ipv6_multicast_ACTION', 'lag_group_ACTION'): {'delay': dA},
 ('outer_ipv6_multicast_ACTION', 'nexthop_ACTION'): {'delay': dA},
 ('outer_ipv6_multicast_ACTION', 'system_acl_ACTION'): {'delay': dA},
 ('outer_ipv6_multicast_ACTION', 'tunnel_ACTION'): {'delay': dA},
 ('outer_ipv6_multicast_MATCH', 'outer_ipv6_multicast_ACTION'): {'delay': dM},
 ('outer_ipv6_multicast_MATCH', 'outer_ipv6_multicast_star_g_ACTION'): {'delay': dM},
 ('outer_ipv6_multicast_star_g_ACTION', '_condition_19'): {'delay': dA},
 ('outer_ipv6_multicast_star_g_ACTION', '_condition_44'): {'delay': dA},
 ('outer_ipv6_multicast_star_g_ACTION', '_condition_45'): {'delay': dA},
 ('outer_ipv6_multicast_star_g_ACTION', 'bd_flood_ACTION'): {'delay': dA},
 ('outer_ipv6_multicast_star_g_ACTION', 'dmac_ACTION'): {'delay': dA},
 ('outer_ipv6_multicast_star_g_ACTION', 'ecmp_group_ACTION'): {'delay': dA},
 ('outer_ipv6_multicast_star_g_ACTION', 'fabric_lag_MATCH'): {'delay': dA},
 ('outer_ipv6_multicast_star_g_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('outer_ipv6_multicast_star_g_ACTION', 'ipv4_multicast_route_ACTION'): {'delay': dA},
 ('outer_ipv6_multicast_star_g_ACTION', 'ipv4_multicast_route_star_g_ACTION'): {'delay': dA},
 ('outer_ipv6_multicast_star_g_ACTION', 'ipv6_multicast_route_ACTION'): {'delay': dA},
 ('outer_ipv6_multicast_star_g_ACTION', 'ipv6_multicast_route_star_g_ACTION'): {'delay': dA},
 ('outer_ipv6_multicast_star_g_ACTION', 'lag_group_ACTION'): {'delay': dA},
 ('outer_ipv6_multicast_star_g_ACTION', 'nexthop_ACTION'): {'delay': dA},
 ('outer_ipv6_multicast_star_g_ACTION', 'system_acl_ACTION'): {'delay': dA},
 ('outer_ipv6_multicast_star_g_ACTION', 'tunnel_ACTION'): {'delay': dA},
 ('outer_ipv6_multicast_star_g_MATCH', 'outer_ipv6_multicast_star_g_ACTION'): {'delay': dM},
 ('outer_rmac_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('outer_rmac_ACTION', 'rmac_ACTION'): {'delay': dA},
 ('outer_rmac_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('outer_rmac_ACTION', 'tunnel_ACTION'): {'delay': dS},
 ('outer_rmac_MATCH', '_condition_14'): {'delay': dM},
 ('outer_rmac_MATCH', '_condition_16'): {'delay': dM},
 ('outer_rmac_MATCH', 'outer_rmac_ACTION'): {'delay': dM},
 ('port_vlan_mapping_ACTION', '_condition_3'): {'delay': dA},
 ('port_vlan_mapping_ACTION', '_condition_33'): {'delay': dA},
 ('port_vlan_mapping_ACTION', '_condition_36'): {'delay': dA},
 ('port_vlan_mapping_ACTION', '_condition_38'): {'delay': dA},
 ('port_vlan_mapping_ACTION', '_condition_39'): {'delay': dA},
 ('port_vlan_mapping_ACTION', '_condition_40'): {'delay': dA},
 ('port_vlan_mapping_ACTION', '_condition_41'): {'delay': dA},
 ('port_vlan_mapping_ACTION', '_condition_51'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'bd_flood_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'dmac_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ecmp_group_ACTION'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ingress_bd_stats_ACTION'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ip_acl_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ipsg_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ipv4_dest_vtep_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ipv4_fib_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ipv4_fib_lpm_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ipv4_multicast_bridge_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ipv4_multicast_bridge_star_g_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ipv4_multicast_route_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ipv4_multicast_route_star_g_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ipv4_racl_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ipv4_src_vtep_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ipv4_urpf_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ipv4_urpf_lpm_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ipv6_acl_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ipv6_dest_vtep_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ipv6_fib_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ipv6_fib_lpm_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ipv6_multicast_bridge_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ipv6_multicast_bridge_star_g_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ipv6_multicast_route_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ipv6_multicast_route_star_g_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ipv6_racl_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ipv6_src_vtep_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ipv6_urpf_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'ipv6_urpf_lpm_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'learn_notify_ACTION'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'mac_acl_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'mpls_ACTION'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'nat_dst_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'nat_flow_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'nat_src_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'nat_twice_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'nexthop_ACTION'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'outer_ipv4_multicast_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'outer_ipv4_multicast_star_g_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'outer_ipv6_multicast_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'outer_ipv6_multicast_star_g_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'outer_rmac_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'rmac_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'sflow_ing_take_sample_ACTION'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'smac_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'spanning_tree_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'tunnel_ACTION'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'urpf_bd_MATCH'): {'delay': dA},
 ('port_vlan_mapping_ACTION', 'validate_packet_ACTION'): {'delay': dA},
 ('port_vlan_mapping_MATCH', 'port_vlan_mapping_ACTION'): {'delay': dM},
 ('rmac_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('rmac_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('rmac_MATCH', '_condition_31'): {'delay': dM},
 ('rmac_MATCH', '_condition_37'): {'delay': dM},
 ('rmac_MATCH', 'rmac_ACTION'): {'delay': dM},
 ('sflow_ing_take_sample_ACTION', 'dmac_ACTION'): {'delay': dS},
 ('sflow_ing_take_sample_ACTION', 'ecmp_group_ACTION'): {'delay': dS},
 ('sflow_ing_take_sample_ACTION', 'fwd_result_ACTION'): {'delay': dS},
 ('sflow_ing_take_sample_ACTION', 'ip_acl_ACTION'): {'delay': dA},
 ('sflow_ing_take_sample_ACTION', 'ipv4_racl_ACTION'): {'delay': dS},
 ('sflow_ing_take_sample_ACTION', 'ipv4_src_vtep_ACTION'): {'delay': dS},
 ('sflow_ing_take_sample_ACTION', 'ipv6_acl_ACTION'): {'delay': dA},
 ('sflow_ing_take_sample_ACTION', 'ipv6_racl_ACTION'): {'delay': dS},
 ('sflow_ing_take_sample_ACTION', 'ipv6_src_vtep_ACTION'): {'delay': dS},
 ('sflow_ing_take_sample_ACTION', 'mac_acl_ACTION'): {'delay': dA},
 ('sflow_ing_take_sample_ACTION', 'mpls_ACTION'): {'delay': dS},
 ('sflow_ing_take_sample_ACTION', 'nexthop_ACTION'): {'delay': dS},
 ('sflow_ing_take_sample_ACTION', 'system_acl_ACTION'): {'delay': dS},
 ('sflow_ing_take_sample_ACTION', 'tunnel_ACTION'): {'delay': dS},
 ('sflow_ing_take_sample_MATCH', 'sflow_ing_take_sample_ACTION'): {'delay': dM},
 ('sflow_ingress_ACTION', 'adjust_lkp_fields_ACTION'): {'delay': dS},
 ('sflow_ingress_ACTION', 'ipv4_src_vtep_ACTION'): {'delay': dS},
 ('sflow_ingress_ACTION', 'ipv6_src_vtep_ACTION'): {'delay': dS},
 ('sflow_ingress_ACTION', 'native_packet_over_fabric_ACTION'): {'delay': dS},
 ('sflow_ingress_ACTION', 'sflow_ing_take_sample_MATCH'): {'delay': dA},
 ('sflow_ingress_ACTION', 'tunnel_lookup_miss_ACTION'): {'delay': dS},
 ('sflow_ingress_MATCH', 'sflow_ingress_ACTION'): {'delay': dM},
 ('smac_ACTION', 'learn_notify_MATCH'): {'delay': dA},
 ('smac_MATCH', 'smac_ACTION'): {'delay': dM},
 ('spanning_tree_ACTION', 'ipv4_src_vtep_ACTION'): {'delay': dS},
 ('spanning_tree_ACTION', 'ipv6_src_vtep_ACTION'): {'delay': dS},
 ('spanning_tree_ACTION', 'learn_notify_MATCH'): {'delay': dA},
 ('spanning_tree_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('spanning_tree_MATCH', 'spanning_tree_ACTION'): {'delay': dM},
 ('storm_control_ACTION', 'ip_acl_ACTION'): {'delay': dA},
 ('storm_control_ACTION', 'ipv4_racl_ACTION'): {'delay': dA},
 ('storm_control_ACTION', 'ipv6_acl_ACTION'): {'delay': dA},
 ('storm_control_ACTION', 'ipv6_racl_ACTION'): {'delay': dA},
 ('storm_control_ACTION', 'mac_acl_ACTION'): {'delay': dA},
 ('storm_control_ACTION', 'meter_action_MATCH'): {'delay': dA},
 ('storm_control_ACTION', 'meter_index_MATCH'): {'delay': dA},
 ('storm_control_ACTION', 'storm_control_stats_MATCH'): {'delay': dA},
 ('storm_control_ACTION', 'validate_packet_ACTION'): {'delay': dS},
 ('storm_control_MATCH', 'storm_control_ACTION'): {'delay': dM},
 ('storm_control_stats_MATCH', 'storm_control_stats_ACTION'): {'delay': dM},
 ('switch_config_params_ACTION', 'dmac_ACTION'): {'delay': dA},
 ('switch_config_params_ACTION', 'ecmp_group_ACTION'): {'delay': dA},
 ('switch_config_params_ACTION', 'fabric_ingress_dst_lkp_ACTION'): {'delay': dA},
 ('switch_config_params_ACTION', 'fabric_lag_ACTION'): {'delay': dA},
 ('switch_config_params_ACTION', 'fwd_result_ACTION'): {'delay': dA},
 ('switch_config_params_ACTION', 'ip_acl_ACTION'): {'delay': dA},
 ('switch_config_params_ACTION', 'ipv4_src_vtep_ACTION'): {'delay': dS},
 ('switch_config_params_ACTION', 'ipv6_acl_ACTION'): {'delay': dA},
 ('switch_config_params_ACTION', 'ipv6_src_vtep_ACTION'): {'delay': dS},
 ('switch_config_params_ACTION', 'lag_group_ACTION'): {'delay': dA},
 ('switch_config_params_ACTION', 'mac_acl_ACTION'): {'delay': dA},
 ('switch_config_params_ACTION', 'nexthop_ACTION'): {'delay': dA},
 ('switch_config_params_ACTION', 'sflow_ing_take_sample_MATCH'): {'delay': dA},
 ('switch_config_params_ACTION', 'sflow_ingress_ACTION'): {'delay': dA},
 ('switch_config_params_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('switch_config_params_MATCH', 'switch_config_params_ACTION'): {'delay': dM},
 ('system_acl_MATCH', 'system_acl_ACTION'): {'delay': dM},
 ('traffic_class_ACTION', 'system_acl_ACTION'): {'delay': dA},
 ('traffic_class_MATCH', 'traffic_class_ACTION'): {'delay': dM},
 ('tunnel_ACTION', '_condition_26'): {'delay': dA},
 ('tunnel_ACTION', '_condition_29'): {'delay': dA},
 ('tunnel_ACTION', '_condition_30'): {'delay': dA},
 ('tunnel_ACTION', '_condition_31'): {'delay': dA},
 ('tunnel_ACTION', '_condition_33'): {'delay': dA},
 ('tunnel_ACTION', '_condition_34'): {'delay': dA},
 ('tunnel_ACTION', '_condition_36'): {'delay': dA},
 ('tunnel_ACTION', '_condition_38'): {'delay': dA},
 ('tunnel_ACTION', '_condition_39'): {'delay': dA},
 ('tunnel_ACTION', '_condition_40'): {'delay': dA},
 ('tunnel_ACTION', '_condition_41'): {'delay': dA},
 ('tunnel_ACTION', '_condition_44'): {'delay': dA},
 ('tunnel_ACTION', '_condition_45'): {'delay': dA},
 ('tunnel_ACTION', 'bd_flood_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'compute_ipv4_hashes_ACTION'): {'delay': dA},
 ('tunnel_ACTION', 'compute_ipv6_hashes_ACTION'): {'delay': dA},
 ('tunnel_ACTION', 'compute_non_ip_hashes_ACTION'): {'delay': dA},
 ('tunnel_ACTION', 'dmac_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'ecmp_group_ACTION'): {'delay': dA},
 ('tunnel_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'ingress_bd_stats_ACTION'): {'delay': dA},
 ('tunnel_ACTION', 'ip_acl_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'ipv4_fib_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'ipv4_fib_lpm_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'ipv4_multicast_bridge_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'ipv4_multicast_bridge_star_g_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'ipv4_multicast_route_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'ipv4_multicast_route_star_g_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'ipv4_racl_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'ipv4_urpf_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'ipv4_urpf_lpm_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'ipv6_acl_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'ipv6_fib_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'ipv6_fib_lpm_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'ipv6_multicast_bridge_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'ipv6_multicast_bridge_star_g_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'ipv6_multicast_route_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'ipv6_multicast_route_star_g_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'ipv6_racl_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'ipv6_urpf_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'ipv6_urpf_lpm_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'learn_notify_ACTION'): {'delay': dA},
 ('tunnel_ACTION', 'mac_acl_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'nat_dst_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'nat_flow_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'nat_src_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'nat_twice_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'nexthop_ACTION'): {'delay': dA},
 ('tunnel_ACTION', 'rmac_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'smac_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'urpf_bd_MATCH'): {'delay': dA},
 ('tunnel_ACTION', 'validate_packet_MATCH'): {'delay': dA},
 ('tunnel_MATCH', 'tunnel_ACTION'): {'delay': dM},
 ('tunnel_MATCH', 'tunnel_lookup_miss_ACTION'): {'delay': dM},
 ('tunnel_lookup_miss_ACTION', 'compute_ipv4_hashes_ACTION'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'compute_ipv6_hashes_ACTION'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'compute_non_ip_hashes_ACTION'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'dmac_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'ingress_l4_dst_port_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'ingress_l4_src_port_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'ip_acl_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'ipv4_fib_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'ipv4_fib_lpm_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'ipv4_multicast_bridge_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'ipv4_multicast_bridge_star_g_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'ipv4_multicast_route_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'ipv4_multicast_route_star_g_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'ipv4_racl_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'ipv4_urpf_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'ipv4_urpf_lpm_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'ipv6_acl_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'ipv6_fib_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'ipv6_fib_lpm_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'ipv6_multicast_bridge_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'ipv6_multicast_bridge_star_g_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'ipv6_multicast_route_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'ipv6_multicast_route_star_g_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'ipv6_racl_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'ipv6_urpf_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'ipv6_urpf_lpm_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'learn_notify_ACTION'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'mac_acl_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'nat_dst_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'nat_flow_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'nat_src_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'nat_twice_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'rmac_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'smac_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_ACTION', 'validate_packet_MATCH'): {'delay': dA},
 ('tunnel_lookup_miss_MATCH', 'tunnel_lookup_miss_ACTION'): {'delay': dM},
 ('urpf_bd_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('urpf_bd_MATCH', 'urpf_bd_ACTION'): {'delay': dM},
 ('validate_mpls_packet_ACTION', 'mpls_MATCH'): {'delay': dA},
 ('validate_mpls_packet_MATCH', 'validate_mpls_packet_ACTION'): {'delay': dM},
 ('validate_outer_ethernet_ACTION', '_condition_23'): {'delay': dA},
 ('validate_outer_ethernet_ACTION', '_condition_54'): {'delay': dA},
 ('validate_outer_ethernet_ACTION', 'bd_flood_MATCH'): {'delay': dA},
 ('validate_outer_ethernet_ACTION', 'compute_ipv4_hashes_MATCH'): {'delay': dA},
 ('validate_outer_ethernet_ACTION', 'compute_ipv6_hashes_MATCH'): {'delay': dA},
 ('validate_outer_ethernet_ACTION', 'compute_non_ip_hashes_MATCH'): {'delay': dA},
 ('validate_outer_ethernet_ACTION', 'drop_stats_ACTION'): {'delay': dA},
 ('validate_outer_ethernet_ACTION', 'fabric_ingress_dst_lkp_ACTION'): {'delay': dS},
 ('validate_outer_ethernet_ACTION', 'fwd_result_ACTION'): {'delay': dA},
 ('validate_outer_ethernet_ACTION', 'ingress_qos_map_pcp_MATCH'): {'delay': dA},
 ('validate_outer_ethernet_ACTION', 'mac_acl_MATCH'): {'delay': dA},
 ('validate_outer_ethernet_ACTION', 'mpls_ACTION'): {'delay': dA},
 ('validate_outer_ethernet_ACTION', 'native_packet_over_fabric_ACTION'): {'delay': dA},
 ('validate_outer_ethernet_ACTION', 'storm_control_MATCH'): {'delay': dA},
 ('validate_outer_ethernet_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('validate_outer_ethernet_ACTION', 'tunnel_ACTION'): {'delay': dA},
 ('validate_outer_ethernet_ACTION', 'validate_packet_ACTION'): {'delay': dA},
 ('validate_outer_ethernet_MATCH', '_condition_0'): {'delay': dM},
 ('validate_outer_ethernet_MATCH', 'validate_outer_ethernet_ACTION'): {'delay': dM},
 ('validate_outer_ipv4_packet_ACTION', '_condition_23'): {'delay': dA},
 ('validate_outer_ipv4_packet_ACTION', '_condition_26'): {'delay': dA},
 ('validate_outer_ipv4_packet_ACTION', '_condition_29'): {'delay': dA},
 ('validate_outer_ipv4_packet_ACTION', '_condition_30'): {'delay': dA},
 ('validate_outer_ipv4_packet_ACTION', '_condition_31'): {'delay': dA},
 ('validate_outer_ipv4_packet_ACTION', '_condition_34'): {'delay': dA},
 ('validate_outer_ipv4_packet_ACTION', '_condition_38'): {'delay': dA},
 ('validate_outer_ipv4_packet_ACTION', '_condition_40'): {'delay': dA},
 ('validate_outer_ipv4_packet_ACTION', '_condition_54'): {'delay': dA},
 ('validate_outer_ipv4_packet_ACTION', 'compute_ipv4_hashes_MATCH'): {'delay': dA},
 ('validate_outer_ipv4_packet_ACTION', 'compute_ipv6_hashes_MATCH'): {'delay': dA},
 ('validate_outer_ipv4_packet_ACTION', 'compute_non_ip_hashes_MATCH'): {'delay': dA},
 ('validate_outer_ipv4_packet_ACTION', 'drop_stats_ACTION'): {'delay': dA},
 ('validate_outer_ipv4_packet_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('validate_outer_ipv4_packet_ACTION', 'ingress_qos_map_dscp_MATCH'): {'delay': dA},
 ('validate_outer_ipv4_packet_ACTION', 'mpls_ACTION'): {'delay': dA},
 ('validate_outer_ipv4_packet_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('validate_outer_ipv4_packet_ACTION', 'tunnel_ACTION'): {'delay': dA},
 ('validate_outer_ipv4_packet_ACTION', 'validate_packet_MATCH'): {'delay': dA},
 ('validate_outer_ipv4_packet_MATCH', 'validate_outer_ipv4_packet_ACTION'): {'delay': dM},
 ('validate_outer_ipv6_packet_ACTION', '_condition_23'): {'delay': dA},
 ('validate_outer_ipv6_packet_ACTION', '_condition_26'): {'delay': dA},
 ('validate_outer_ipv6_packet_ACTION', '_condition_29'): {'delay': dA},
 ('validate_outer_ipv6_packet_ACTION', '_condition_30'): {'delay': dA},
 ('validate_outer_ipv6_packet_ACTION', '_condition_31'): {'delay': dA},
 ('validate_outer_ipv6_packet_ACTION', '_condition_34'): {'delay': dA},
 ('validate_outer_ipv6_packet_ACTION', '_condition_38'): {'delay': dA},
 ('validate_outer_ipv6_packet_ACTION', '_condition_40'): {'delay': dA},
 ('validate_outer_ipv6_packet_ACTION', '_condition_54'): {'delay': dA},
 ('validate_outer_ipv6_packet_ACTION', 'compute_ipv4_hashes_MATCH'): {'delay': dA},
 ('validate_outer_ipv6_packet_ACTION', 'compute_ipv6_hashes_MATCH'): {'delay': dA},
 ('validate_outer_ipv6_packet_ACTION', 'compute_non_ip_hashes_MATCH'): {'delay': dA},
 ('validate_outer_ipv6_packet_ACTION', 'drop_stats_ACTION'): {'delay': dA},
 ('validate_outer_ipv6_packet_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('validate_outer_ipv6_packet_ACTION', 'ingress_qos_map_dscp_MATCH'): {'delay': dA},
 ('validate_outer_ipv6_packet_ACTION', 'mpls_ACTION'): {'delay': dA},
 ('validate_outer_ipv6_packet_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('validate_outer_ipv6_packet_ACTION', 'tunnel_ACTION'): {'delay': dA},
 ('validate_outer_ipv6_packet_ACTION', 'validate_packet_MATCH'): {'delay': dA},
 ('validate_outer_ipv6_packet_MATCH', 'validate_outer_ipv6_packet_ACTION'): {'delay': dM},
 ('validate_packet_ACTION', '_condition_54'): {'delay': dA},
 ('validate_packet_ACTION', 'bd_flood_MATCH'): {'delay': dA},
 ('validate_packet_ACTION', 'compute_ipv4_hashes_MATCH'): {'delay': dA},
 ('validate_packet_ACTION', 'compute_ipv6_hashes_MATCH'): {'delay': dA},
 ('validate_packet_ACTION', 'compute_non_ip_hashes_MATCH'): {'delay': dA},
 ('validate_packet_ACTION', 'drop_stats_ACTION'): {'delay': dA},
 ('validate_packet_ACTION', 'fwd_result_MATCH'): {'delay': dA},
 ('validate_packet_ACTION', 'ingress_bd_stats_ACTION'): {'delay': dA},
 ('validate_packet_ACTION', 'system_acl_MATCH'): {'delay': dA},
 ('validate_packet_MATCH', 'validate_packet_ACTION'): {'delay': dM}}

# Number of processors in system
num_procs = 24

# Throughput required
throughput = 1.0
