nodes = \
{'_condition_41': {'num_fields': 0, 'type': 'condition'},
 '_condition_42': {'num_fields': 0, 'type': 'condition'},
 '_condition_43': {'num_fields': 0, 'type': 'condition'},
 '_condition_44': {'num_fields': 0, 'type': 'condition'},
 '_condition_45': {'num_fields': 0, 'type': 'condition'},
 '_condition_46': {'num_fields': 0, 'type': 'condition'},
 '_condition_47': {'num_fields': 0, 'type': 'condition'},
 '_condition_48': {'num_fields': 0, 'type': 'condition'},
 '_condition_49': {'num_fields': 0, 'type': 'condition'},
 '_condition_50': {'num_fields': 0, 'type': 'condition'},
 '_condition_51': {'num_fields': 0, 'type': 'condition'},
 '_condition_52': {'num_fields': 0, 'type': 'condition'},
 'egress_bd_map_ACTION': {'num_fields': 3, 'type': 'action'},
 'egress_bd_map_MATCH': {'key_width': 16, 'type': 'match'},
 'egress_bd_stats_ACTION': {'num_fields': 0, 'type': 'action'},
 'egress_bd_stats_MATCH': {'key_width': 19, 'type': 'match'},
 'egress_filter_ACTION': {'num_fields': 3, 'type': 'action'},
 'egress_filter_drop_ACTION': {'num_fields': 1, 'type': 'action'},
 'egress_nat_ACTION': {'num_fields': 6, 'type': 'action'},
 'egress_nat_MATCH': {'key_width': 14, 'type': 'match'},
 'egress_port_mapping_ACTION': {'num_fields': 4, 'type': 'action'},
 'egress_port_mapping_MATCH': {'key_width': 9, 'type': 'match'},
 'egress_qos_map_ACTION': {'num_fields': 1, 'type': 'action'},
 'egress_qos_map_MATCH': {'key_width': 13, 'type': 'match'},
 'egress_system_acl_ACTION': {'num_fields': 3, 'type': 'action'},
 'egress_system_acl_MATCH': {'key_width': 43, 'type': 'match'},
 'egress_vlan_xlate_ACTION': {'num_fields': 7, 'type': 'action'},
 'egress_vlan_xlate_MATCH': {'key_width': 32, 'type': 'match'},
 'l3_rewrite_ACTION': {'num_fields': 3, 'type': 'action'},
 'l3_rewrite_MATCH': {'key_width': 5, 'type': 'match'},
 'mirror_ACTION': {'num_fields': 1, 'type': 'action'},
 'mirror_MATCH': {'key_width': 16, 'type': 'match'},
 'mtu_ACTION': {'num_fields': 1, 'type': 'action'},
 'mtu_MATCH': {'key_width': 10, 'type': 'match'},
 'replica_type_ACTION': {'num_fields': 1, 'type': 'action'},
 'replica_type_MATCH': {'key_width': 17, 'type': 'match'},
 'rewrite_ACTION': {'num_fields': 6, 'type': 'action'},
 'rewrite_MATCH': {'key_width': 16, 'type': 'match'},
 'rewrite_multicast_ACTION': {'num_fields': 1, 'type': 'action'},
 'rewrite_multicast_MATCH': {'key_width': 6, 'type': 'match'},
 'rid_ACTION': {'num_fields': 8, 'type': 'action'},
 'rid_MATCH': {'key_width': 16, 'type': 'match'},
 'smac_rewrite_ACTION': {'num_fields': 1, 'type': 'action'},
 'smac_rewrite_MATCH': {'key_width': 9, 'type': 'match'},
 'vlan_decap_ACTION': {'num_fields': 3, 'type': 'action'},
 'vlan_decap_MATCH': {'key_width': 2, 'type': 'match'}}

edges = \
{('_condition_41', '_condition_42'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_41', '_condition_49'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_41', '_condition_50'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_41', 'egress_filter_ACTION'): {'delay': 0,
                                             'dep_type': 'rmt_successor'},
 ('_condition_41', 'egress_port_mapping_ACTION'): {'delay': 0,
                                                   'dep_type': 'rmt_successor'},
 ('_condition_42', '_condition_43'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_42', 'mirror_ACTION'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_43', 'replica_type_ACTION'): {'delay': 0,
                                            'dep_type': 'rmt_successor'},
 ('_condition_43', 'rid_ACTION'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_44', 'vlan_decap_ACTION'): {'delay': 0,
                                          'dep_type': 'rmt_successor'},
 ('_condition_45', 'rewrite_ACTION'): {'delay': 0,
                                       'dep_type': 'rmt_successor'},
 ('_condition_45', 'rewrite_multicast_ACTION'): {'delay': 0,
                                                 'dep_type': 'rmt_successor'},
 ('_condition_46', 'egress_qos_map_ACTION'): {'delay': 0,
                                              'dep_type': 'rmt_successor'},
 ('_condition_47', 'l3_rewrite_ACTION'): {'delay': 0,
                                          'dep_type': 'rmt_successor'},
 ('_condition_47', 'smac_rewrite_ACTION'): {'delay': 0,
                                            'dep_type': 'rmt_successor'},
 ('_condition_48', 'egress_nat_ACTION'): {'delay': 0,
                                          'dep_type': 'rmt_successor'},
 ('_condition_49', 'egress_vlan_xlate_ACTION'): {'delay': 0,
                                                 'dep_type': 'rmt_successor'},
 ('_condition_50', '_condition_51'): {'delay': 0, 'dep_type': 'rmt_successor'},
 ('_condition_51', 'egress_filter_drop_ACTION'): {'delay': 0,
                                                  'dep_type': 'rmt_successor'},
 ('_condition_52', 'egress_system_acl_ACTION'): {'delay': 0,
                                                 'dep_type': 'rmt_successor'},
 ('egress_bd_map_ACTION', '_condition_48'): {'delay': 1,
                                             'dep_type': 'rmt_match'},
 ('egress_bd_map_ACTION', 'smac_rewrite_MATCH'): {'delay': 1,
                                                  'dep_type': 'rmt_match'},
 ('egress_bd_map_MATCH', 'egress_bd_map_ACTION'): {'delay': 9,
                                                   'dep_type': 'new_match_to_action'},
 ('egress_bd_stats_MATCH', 'egress_bd_stats_ACTION'): {'delay': 9,
                                                       'dep_type': 'new_match_to_action'},
 ('egress_filter_ACTION', '_condition_51'): {'delay': 1,
                                             'dep_type': 'rmt_match'},
 ('egress_nat_MATCH', 'egress_nat_ACTION'): {'delay': 9,
                                             'dep_type': 'new_match_to_action'},
 ('egress_port_mapping_ACTION', '_condition_49'): {'delay': 1,
                                                   'dep_type': 'rmt_match'},
 ('egress_port_mapping_ACTION', '_condition_51'): {'delay': 1,
                                                   'dep_type': 'rmt_match'},
 ('egress_port_mapping_ACTION', 'egress_filter_ACTION'): {'delay': 1,
                                                          'dep_type': 'rmt_action'},
 ('egress_port_mapping_ACTION', 'egress_qos_map_MATCH'): {'delay': 1,
                                                          'dep_type': 'rmt_match'},
 ('egress_port_mapping_ACTION', 'egress_vlan_xlate_MATCH'): {'delay': 1,
                                                             'dep_type': 'rmt_match'},
 ('egress_port_mapping_MATCH', '_condition_44'): {'delay': 9,
                                                  'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('egress_port_mapping_MATCH', '_condition_45'): {'delay': 9,
                                                  'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('egress_port_mapping_MATCH', '_condition_46'): {'delay': 9,
                                                  'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('egress_port_mapping_MATCH', '_condition_47'): {'delay': 9,
                                                  'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('egress_port_mapping_MATCH', '_condition_48'): {'delay': 9,
                                                  'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('egress_port_mapping_MATCH', 'egress_bd_map_ACTION'): {'delay': 9,
                                                         'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('egress_port_mapping_MATCH', 'egress_bd_stats_ACTION'): {'delay': 9,
                                                           'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('egress_port_mapping_MATCH', 'egress_port_mapping_ACTION'): {'delay': 9,
                                                               'dep_type': 'new_match_to_action'},
 ('egress_port_mapping_MATCH', 'mtu_ACTION'): {'delay': 9,
                                               'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('egress_qos_map_ACTION', 'l3_rewrite_ACTION'): {'delay': 1,
                                                  'dep_type': 'rmt_action'},
 ('egress_qos_map_MATCH', 'egress_qos_map_ACTION'): {'delay': 9,
                                                     'dep_type': 'new_match_to_action'},
 ('egress_system_acl_MATCH', 'egress_system_acl_ACTION'): {'delay': 9,
                                                           'dep_type': 'new_match_to_action'},
 ('egress_vlan_xlate_MATCH', 'egress_vlan_xlate_ACTION'): {'delay': 9,
                                                           'dep_type': 'new_match_to_action'},
 ('l3_rewrite_ACTION', 'egress_nat_ACTION'): {'delay': 0,
                                              'dep_type': 'rmt_reverse_read'},
 ('l3_rewrite_MATCH', 'l3_rewrite_ACTION'): {'delay': 9,
                                             'dep_type': 'new_match_to_action'},
 ('mirror_ACTION', '_condition_45'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('mirror_ACTION', 'egress_bd_map_MATCH'): {'delay': 1,
                                            'dep_type': 'rmt_match'},
 ('mirror_ACTION', 'egress_bd_stats_MATCH'): {'delay': 1,
                                              'dep_type': 'rmt_match'},
 ('mirror_ACTION', 'egress_filter_ACTION'): {'delay': 1,
                                             'dep_type': 'rmt_action'},
 ('mirror_ACTION', 'egress_system_acl_ACTION'): {'delay': 0,
                                                 'dep_type': 'rmt_reverse_read'},
 ('mirror_ACTION', 'egress_vlan_xlate_MATCH'): {'delay': 1,
                                                'dep_type': 'rmt_match'},
 ('mirror_ACTION', 'rewrite_MATCH'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('mirror_MATCH', 'mirror_ACTION'): {'delay': 9,
                                     'dep_type': 'new_match_to_action'},
 ('mtu_ACTION', 'egress_system_acl_MATCH'): {'delay': 1,
                                             'dep_type': 'rmt_match'},
 ('mtu_MATCH', 'mtu_ACTION'): {'delay': 9, 'dep_type': 'new_match_to_action'},
 ('replica_type_ACTION', '_condition_45'): {'delay': 1,
                                            'dep_type': 'rmt_match'},
 ('replica_type_ACTION', '_condition_47'): {'delay': 1,
                                            'dep_type': 'rmt_match'},
 ('replica_type_ACTION', 'rewrite_ACTION'): {'delay': 1,
                                             'dep_type': 'rmt_action'},
 ('replica_type_MATCH', 'replica_type_ACTION'): {'delay': 9,
                                                 'dep_type': 'new_match_to_action'},
 ('rewrite_ACTION', '_condition_47'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('rewrite_ACTION', '_condition_51'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('rewrite_ACTION', 'egress_bd_map_MATCH'): {'delay': 1,
                                             'dep_type': 'rmt_match'},
 ('rewrite_ACTION', 'egress_bd_stats_MATCH'): {'delay': 1,
                                               'dep_type': 'rmt_match'},
 ('rewrite_ACTION', 'egress_filter_ACTION'): {'delay': 1,
                                              'dep_type': 'rmt_action'},
 ('rewrite_ACTION', 'egress_vlan_xlate_MATCH'): {'delay': 1,
                                                 'dep_type': 'rmt_match'},
 ('rewrite_ACTION', 'l3_rewrite_ACTION'): {'delay': 1,
                                           'dep_type': 'rmt_action'},
 ('rewrite_ACTION', 'mtu_MATCH'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('rewrite_MATCH', 'rewrite_ACTION'): {'delay': 9,
                                       'dep_type': 'new_match_to_action'},
 ('rewrite_multicast_ACTION', 'egress_nat_ACTION'): {'delay': 0,
                                                     'dep_type': 'rmt_reverse_read'},
 ('rewrite_multicast_ACTION', 'l3_rewrite_ACTION'): {'delay': 1,
                                                     'dep_type': 'rmt_action'},
 ('rewrite_multicast_MATCH', 'rewrite_multicast_ACTION'): {'delay': 9,
                                                           'dep_type': 'new_match_to_action'},
 ('rid_ACTION', '_condition_45'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('rid_ACTION', '_condition_47'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('rid_ACTION', '_condition_50'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('rid_ACTION', '_condition_51'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('rid_ACTION', 'egress_bd_map_MATCH'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('rid_ACTION', 'egress_bd_stats_MATCH'): {'delay': 1,
                                           'dep_type': 'rmt_match'},
 ('rid_ACTION', 'egress_filter_ACTION'): {'delay': 1,
                                          'dep_type': 'rmt_action'},
 ('rid_ACTION', 'egress_port_mapping_ACTION'): {'delay': 1,
                                                'dep_type': 'rmt_action'},
 ('rid_ACTION', 'egress_vlan_xlate_MATCH'): {'delay': 1,
                                             'dep_type': 'rmt_match'},
 ('rid_ACTION', 'replica_type_MATCH'): {'delay': 1, 'dep_type': 'rmt_match'},
 ('rid_ACTION', 'rewrite_ACTION'): {'delay': 1, 'dep_type': 'rmt_action'},
 ('rid_MATCH', 'rid_ACTION'): {'delay': 9, 'dep_type': 'new_match_to_action'},
 ('smac_rewrite_MATCH', 'smac_rewrite_ACTION'): {'delay': 9,
                                                 'dep_type': 'new_match_to_action'},
 ('vlan_decap_ACTION', 'egress_vlan_xlate_ACTION'): {'delay': 1,
                                                     'dep_type': 'rmt_action'},
 ('vlan_decap_MATCH', 'vlan_decap_ACTION'): {'delay': 9,
                                             'dep_type': 'new_match_to_action'}}
