nodes = \
{'_condition_egr_41': {'num_fields': 0, 'type': 'condition'},
 '_condition_egr_42': {'num_fields': 0, 'type': 'condition'},
 '_condition_egr_43': {'num_fields': 0, 'type': 'condition'},
 '_condition_egr_44': {'num_fields': 0, 'type': 'condition'},
 '_condition_egr_45': {'num_fields': 0, 'type': 'condition'},
 '_condition_egr_46': {'num_fields': 0, 'type': 'condition'},
 '_condition_egr_47': {'num_fields': 0, 'type': 'condition'},
 '_condition_egr_48': {'num_fields': 0, 'type': 'condition'},
 '_condition_egr_49': {'num_fields': 0, 'type': 'condition'},
 '_condition_egr_50': {'num_fields': 0, 'type': 'condition'},
 '_condition_egr_51': {'num_fields': 0, 'type': 'condition'},
 '_condition_egr_52': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_0': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_10': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_11': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_12': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_13': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_14': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_15': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_16': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_17': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_18': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_19': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_2': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_21': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_22': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_23': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_25': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_26': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_27': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_29': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_3': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_30': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_31': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_32': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_33': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_34': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_35': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_36': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_37': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_38': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_39': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_4': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_40': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_5': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_6': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_7': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_8': {'num_fields': 0, 'type': 'condition'},
 '_condition_ing_9': {'num_fields': 0, 'type': 'condition'},
 'egr_egress_bd_map_ACTION': {'num_fields': 3, 'type': 'action'},
 'egr_egress_bd_map_MATCH': {'key_width': 16, 'type': 'match'},
 'egr_egress_bd_stats_ACTION': {'num_fields': 0, 'type': 'action'},
 'egr_egress_bd_stats_MATCH': {'key_width': 19, 'type': 'match'},
 'egr_egress_filter_ACTION': {'num_fields': 3, 'type': 'action'},
 'egr_egress_filter_drop_ACTION': {'num_fields': 1, 'type': 'action'},
 'egr_egress_nat_ACTION': {'num_fields': 6, 'type': 'action'},
 'egr_egress_nat_MATCH': {'key_width': 14, 'type': 'match'},
 'egr_egress_port_mapping_ACTION': {'num_fields': 4, 'type': 'action'},
 'egr_egress_port_mapping_MATCH': {'key_width': 9, 'type': 'match'},
 'egr_egress_qos_map_ACTION': {'num_fields': 1, 'type': 'action'},
 'egr_egress_qos_map_MATCH': {'key_width': 13, 'type': 'match'},
 'egr_egress_system_acl_ACTION': {'num_fields': 3, 'type': 'action'},
 'egr_egress_system_acl_MATCH': {'key_width': 43, 'type': 'match'},
 'egr_egress_vlan_xlate_ACTION': {'num_fields': 7, 'type': 'action'},
 'egr_egress_vlan_xlate_MATCH': {'key_width': 32, 'type': 'match'},
 'egr_l3_rewrite_ACTION': {'num_fields': 3, 'type': 'action'},
 'egr_l3_rewrite_MATCH': {'key_width': 5, 'type': 'match'},
 'egr_mirror_ACTION': {'num_fields': 1, 'type': 'action'},
 'egr_mirror_MATCH': {'key_width': 16, 'type': 'match'},
 'egr_mtu_ACTION': {'num_fields': 1, 'type': 'action'},
 'egr_mtu_MATCH': {'key_width': 10, 'type': 'match'},
 'egr_replica_type_ACTION': {'num_fields': 1, 'type': 'action'},
 'egr_replica_type_MATCH': {'key_width': 17, 'type': 'match'},
 'egr_rewrite_ACTION': {'num_fields': 6, 'type': 'action'},
 'egr_rewrite_MATCH': {'key_width': 16, 'type': 'match'},
 'egr_rewrite_multicast_ACTION': {'num_fields': 1, 'type': 'action'},
 'egr_rewrite_multicast_MATCH': {'key_width': 6, 'type': 'match'},
 'egr_rid_ACTION': {'num_fields': 8, 'type': 'action'},
 'egr_rid_MATCH': {'key_width': 16, 'type': 'match'},
 'egr_smac_rewrite_ACTION': {'num_fields': 1, 'type': 'action'},
 'egr_smac_rewrite_MATCH': {'key_width': 9, 'type': 'match'},
 'egr_vlan_decap_ACTION': {'num_fields': 3, 'type': 'action'},
 'egr_vlan_decap_MATCH': {'key_width': 2, 'type': 'match'},
 'ing_acl_stats_ACTION': {'num_fields': 1, 'type': 'action'},
 'ing_adjust_lkp_fields_ACTION': {'num_fields': 8, 'type': 'action'},
 'ing_adjust_lkp_fields_MATCH': {'key_width': 2, 'type': 'match'},
 'ing_bd_flood_ACTION': {'num_fields': 1, 'type': 'action'},
 'ing_bd_flood_MATCH': {'key_width': 19, 'type': 'match'},
 'ing_compute_ipv4_hashes_ACTION': {'num_fields': 2, 'type': 'action'},
 'ing_compute_ipv4_hashes_MATCH': {'key_width': 1, 'type': 'match'},
 'ing_compute_non_ip_hashes_ACTION': {'num_fields': 1, 'type': 'action'},
 'ing_compute_non_ip_hashes_MATCH': {'key_width': 1, 'type': 'match'},
 'ing_compute_other_hashes_ACTION': {'num_fields': 3, 'type': 'action'},
 'ing_compute_other_hashes_MATCH': {'key_width': 16, 'type': 'match'},
 'ing_dmac_ACTION': {'num_fields': 3, 'type': 'action'},
 'ing_dmac_MATCH': {'key_width': 64, 'type': 'match'},
 'ing_drop_stats_ACTION': {'num_fields': 1, 'type': 'action'},
 'ing_ecmp_group_ACTION': {'num_fields': 5, 'type': 'action'},
 'ing_ecmp_group_MATCH': {'key_width': 16, 'type': 'match'},
 'ing_fabric_ingress_dst_lkp_ACTION': {'num_fields': 10, 'type': 'action'},
 'ing_fabric_ingress_dst_lkp_MATCH': {'key_width': 8, 'type': 'match'},
 'ing_fabric_ingress_src_lkp_ACTION': {'num_fields': 0, 'type': 'action'},
 'ing_fabric_ingress_src_lkp_MATCH': {'key_width': 16, 'type': 'match'},
 'ing_fabric_lag_ACTION': {'num_fields': 1, 'type': 'action'},
 'ing_fabric_lag_MATCH': {'key_width': 8, 'type': 'match'},
 'ing_fwd_result_ACTION': {'num_fields': 6, 'type': 'action'},
 'ing_fwd_result_MATCH': {'key_width': 33, 'type': 'match'},
 'ing_ingress_bd_stats_ACTION': {'num_fields': 1, 'type': 'action'},
 'ing_ingress_l4_dst_port_ACTION': {'num_fields': 1, 'type': 'action'},
 'ing_ingress_l4_dst_port_MATCH': {'key_width': 16, 'type': 'match'},
 'ing_ingress_l4_src_port_ACTION': {'num_fields': 1, 'type': 'action'},
 'ing_ingress_l4_src_port_MATCH': {'key_width': 16, 'type': 'match'},
 'ing_ingress_port_mapping_ACTION': {'num_fields': 2, 'type': 'action'},
 'ing_ingress_port_mapping_MATCH': {'key_width': 9, 'type': 'match'},
 'ing_ingress_port_properties_ACTION': {'num_fields': 7, 'type': 'action'},
 'ing_ingress_port_properties_MATCH': {'key_width': 9, 'type': 'match'},
 'ing_ingress_qos_map_dscp_ACTION': {'num_fields': 2, 'type': 'action'},
 'ing_ingress_qos_map_dscp_MATCH': {'key_width': 13, 'type': 'match'},
 'ing_ingress_qos_map_pcp_ACTION': {'num_fields': 2, 'type': 'action'},
 'ing_ingress_qos_map_pcp_MATCH': {'key_width': 8, 'type': 'match'},
 'ing_ip_acl_ACTION': {'num_fields': 10, 'type': 'action'},
 'ing_ip_acl_MATCH': {'key_width': 136, 'type': 'match'},
 'ing_ipsg_ACTION': {'num_fields': 0, 'type': 'action'},
 'ing_ipsg_MATCH': {'key_width': 112, 'type': 'match'},
 'ing_ipsg_permit_special_ACTION': {'num_fields': 1, 'type': 'action'},
 'ing_ipsg_permit_special_MATCH': {'key_width': 56, 'type': 'match'},
 'ing_ipv4_fib_ACTION': {'num_fields': 3, 'type': 'action'},
 'ing_ipv4_fib_MATCH': {'key_width': 48, 'type': 'match'},
 'ing_ipv4_fib_lpm_ACTION': {'num_fields': 3, 'type': 'action'},
 'ing_ipv4_fib_lpm_MATCH': {'key_width': 48, 'type': 'match'},
 'ing_ipv4_multicast_bridge_ACTION': {'num_fields': 2, 'type': 'action'},
 'ing_ipv4_multicast_bridge_MATCH': {'key_width': 80, 'type': 'match'},
 'ing_ipv4_multicast_bridge_star_g_ACTION': {'num_fields': 2,
                                             'type': 'action'},
 'ing_ipv4_multicast_bridge_star_g_MATCH': {'key_width': 48, 'type': 'match'},
 'ing_ipv4_multicast_route_ACTION': {'num_fields': 4, 'type': 'action'},
 'ing_ipv4_multicast_route_MATCH': {'key_width': 80, 'type': 'match'},
 'ing_ipv4_multicast_route_star_g_ACTION': {'num_fields': 4, 'type': 'action'},
 'ing_ipv4_multicast_route_star_g_MATCH': {'key_width': 48, 'type': 'match'},
 'ing_ipv4_racl_ACTION': {'num_fields': 8, 'type': 'action'},
 'ing_ipv4_racl_MATCH': {'key_width': 104, 'type': 'match'},
 'ing_ipv4_urpf_ACTION': {'num_fields': 3, 'type': 'action'},
 'ing_ipv4_urpf_MATCH': {'key_width': 48, 'type': 'match'},
 'ing_ipv4_urpf_lpm_ACTION': {'num_fields': 3, 'type': 'action'},
 'ing_ipv4_urpf_lpm_MATCH': {'key_width': 48, 'type': 'match'},
 'ing_lag_group_ACTION': {'num_fields': 2, 'type': 'action'},
 'ing_lag_group_MATCH': {'key_width': 16, 'type': 'match'},
 'ing_learn_notify_ACTION': {'num_fields': 1, 'type': 'action'},
 'ing_learn_notify_MATCH': {'key_width': 20, 'type': 'match'},
 'ing_mac_acl_ACTION': {'num_fields': 10, 'type': 'action'},
 'ing_mac_acl_MATCH': {'key_width': 144, 'type': 'match'},
 'ing_meter_action_ACTION': {'num_fields': 1, 'type': 'action'},
 'ing_meter_action_MATCH': {'key_width': 18, 'type': 'match'},
 'ing_meter_index_ACTION': {'num_fields': 0, 'type': 'action'},
 'ing_meter_index_MATCH': {'key_width': 16, 'type': 'match'},
 'ing_nat_dst_ACTION': {'num_fields': 4, 'type': 'action'},
 'ing_nat_dst_MATCH': {'key_width': 72, 'type': 'match'},
 'ing_nat_flow_ACTION': {'num_fields': 4, 'type': 'action'},
 'ing_nat_flow_MATCH': {'key_width': 120, 'type': 'match'},
 'ing_nat_src_ACTION': {'num_fields': 1, 'type': 'action'},
 'ing_nat_src_MATCH': {'key_width': 72, 'type': 'match'},
 'ing_nat_twice_ACTION': {'num_fields': 4, 'type': 'action'},
 'ing_nat_twice_MATCH': {'key_width': 120, 'type': 'match'},
 'ing_native_packet_over_fabric_ACTION': {'num_fields': 7, 'type': 'action'},
 'ing_native_packet_over_fabric_MATCH': {'key_width': 2, 'type': 'match'},
 'ing_nexthop_ACTION': {'num_fields': 4, 'type': 'action'},
 'ing_nexthop_MATCH': {'key_width': 16, 'type': 'match'},
 'ing_port_vlan_mapping_ACTION': {'num_fields': 21, 'type': 'action'},
 'ing_port_vlan_mapping_MATCH': {'key_width': 42, 'type': 'match'},
 'ing_rmac_ACTION': {'num_fields': 1, 'type': 'action'},
 'ing_rmac_MATCH': {'key_width': 58, 'type': 'match'},
 'ing_smac_ACTION': {'num_fields': 1, 'type': 'action'},
 'ing_smac_MATCH': {'key_width': 64, 'type': 'match'},
 'ing_spanning_tree_ACTION': {'num_fields': 1, 'type': 'action'},
 'ing_spanning_tree_MATCH': {'key_width': 26, 'type': 'match'},
 'ing_storm_control_ACTION': {'num_fields': 2, 'type': 'action'},
 'ing_storm_control_MATCH': {'key_width': 12, 'type': 'match'},
 'ing_storm_control_stats_ACTION': {'num_fields': 0, 'type': 'action'},
 'ing_storm_control_stats_MATCH': {'key_width': 11, 'type': 'match'},
 'ing_switch_config_params_ACTION': {'num_fields': 5, 'type': 'action'},
 'ing_switch_config_params_MATCH': {'key_width': 1, 'type': 'match'},
 'ing_system_acl_ACTION': {'num_fields': 7, 'type': 'action'},
 'ing_system_acl_MATCH': {'key_width': 153, 'type': 'match'},
 'ing_traffic_class_ACTION': {'num_fields': 2, 'type': 'action'},
 'ing_traffic_class_MATCH': {'key_width': 13, 'type': 'match'},
 'ing_urpf_bd_ACTION': {'num_fields': 1, 'type': 'action'},
 'ing_urpf_bd_MATCH': {'key_width': 32, 'type': 'match'},
 'ing_validate_outer_ethernet_ACTION': {'num_fields': 3, 'type': 'action'},
 'ing_validate_outer_ethernet_MATCH': {'key_width': 98, 'type': 'match'},
 'ing_validate_outer_ipv4_packet_ACTION': {'num_fields': 3, 'type': 'action'},
 'ing_validate_outer_ipv4_packet_MATCH': {'key_width': 20, 'type': 'match'},
 'ing_validate_packet_ACTION': {'num_fields': 3, 'type': 'action'},
 'ing_validate_packet_MATCH': {'key_width': 118, 'type': 'match'}}

edges = \
{('_condition_egr_41', '_condition_egr_42'): {'delay': 0,
                                              'dep_type': 'rmt_successor'},
 ('_condition_egr_41', '_condition_egr_49'): {'delay': 0,
                                              'dep_type': 'rmt_successor'},
 ('_condition_egr_41', '_condition_egr_50'): {'delay': 0,
                                              'dep_type': 'rmt_successor'},
 ('_condition_egr_41', 'egr_egress_filter_ACTION'): {'delay': 0,
                                                     'dep_type': 'rmt_successor'},
 ('_condition_egr_41', 'egr_egress_port_mapping_ACTION'): {'delay': 0,
                                                           'dep_type': 'rmt_successor'},
 ('_condition_egr_42', '_condition_egr_43'): {'delay': 0,
                                              'dep_type': 'rmt_successor'},
 ('_condition_egr_42', 'egr_mirror_ACTION'): {'delay': 0,
                                              'dep_type': 'rmt_successor'},
 ('_condition_egr_43', 'egr_replica_type_ACTION'): {'delay': 0,
                                                    'dep_type': 'rmt_successor'},
 ('_condition_egr_43', 'egr_rid_ACTION'): {'delay': 0,
                                           'dep_type': 'rmt_successor'},
 ('_condition_egr_44', 'egr_vlan_decap_ACTION'): {'delay': 0,
                                                  'dep_type': 'rmt_successor'},
 ('_condition_egr_45', 'egr_rewrite_ACTION'): {'delay': 0,
                                               'dep_type': 'rmt_successor'},
 ('_condition_egr_45', 'egr_rewrite_multicast_ACTION'): {'delay': 0,
                                                         'dep_type': 'rmt_successor'},
 ('_condition_egr_46', 'egr_egress_qos_map_ACTION'): {'delay': 0,
                                                      'dep_type': 'rmt_successor'},
 ('_condition_egr_47', 'egr_l3_rewrite_ACTION'): {'delay': 0,
                                                  'dep_type': 'rmt_successor'},
 ('_condition_egr_47', 'egr_smac_rewrite_ACTION'): {'delay': 0,
                                                    'dep_type': 'rmt_successor'},
 ('_condition_egr_48', 'egr_egress_nat_ACTION'): {'delay': 0,
                                                  'dep_type': 'rmt_successor'},
 ('_condition_egr_49', 'egr_egress_vlan_xlate_ACTION'): {'delay': 0,
                                                         'dep_type': 'rmt_successor'},
 ('_condition_egr_50', '_condition_egr_51'): {'delay': 0,
                                              'dep_type': 'rmt_successor'},
 ('_condition_egr_51', 'egr_egress_filter_drop_ACTION'): {'delay': 0,
                                                          'dep_type': 'rmt_successor'},
 ('_condition_egr_52', 'egr_egress_system_acl_ACTION'): {'delay': 0,
                                                         'dep_type': 'rmt_successor'},
 ('_condition_ing_0', 'ing_validate_outer_ipv4_packet_ACTION'): {'delay': 0,
                                                                 'dep_type': 'rmt_successor'},
 ('_condition_ing_10', 'ing_native_packet_over_fabric_ACTION'): {'delay': 0,
                                                                 'dep_type': 'rmt_successor'},
 ('_condition_ing_11', 'ing_storm_control_ACTION'): {'delay': 0,
                                                     'dep_type': 'rmt_successor'},
 ('_condition_ing_12', '_condition_ing_13'): {'delay': 0,
                                              'dep_type': 'rmt_successor'},
 ('_condition_ing_12', '_condition_ing_14'): {'delay': 0,
                                              'dep_type': 'rmt_successor'},
 ('_condition_ing_12', '_condition_ing_15'): {'delay': 0,
                                              'dep_type': 'rmt_successor'},
 ('_condition_ing_12', '_condition_ing_16'): {'delay': 0,
                                              'dep_type': 'rmt_successor'},
 ('_condition_ing_12', 'ing_ingress_l4_dst_port_ACTION'): {'delay': 0,
                                                           'dep_type': 'rmt_successor'},
 ('_condition_ing_12', 'ing_ingress_l4_src_port_ACTION'): {'delay': 0,
                                                           'dep_type': 'rmt_successor'},
 ('_condition_ing_12', 'ing_nat_twice_ACTION'): {'delay': 0,
                                                 'dep_type': 'rmt_successor'},
 ('_condition_ing_12', 'ing_rmac_ACTION'): {'delay': 0,
                                            'dep_type': 'rmt_successor'},
 ('_condition_ing_13', 'ing_fwd_result_ACTION'): {'delay': 0,
                                                  'dep_type': 'rmt_reverse_read'},
 ('_condition_ing_13', 'ing_validate_packet_ACTION'): {'delay': 0,
                                                       'dep_type': 'rmt_successor'},
 ('_condition_ing_14', 'ing_smac_ACTION'): {'delay': 0,
                                            'dep_type': 'rmt_successor'},
 ('_condition_ing_15', 'ing_dmac_ACTION'): {'delay': 0,
                                            'dep_type': 'rmt_successor'},
 ('_condition_ing_16', '_condition_ing_17'): {'delay': 0,
                                              'dep_type': 'rmt_successor'},
 ('_condition_ing_16', '_condition_ing_18'): {'delay': 0,
                                              'dep_type': 'rmt_successor'},
 ('_condition_ing_17', 'ing_mac_acl_ACTION'): {'delay': 0,
                                               'dep_type': 'rmt_successor'},
 ('_condition_ing_18', '_condition_ing_19'): {'delay': 0,
                                              'dep_type': 'rmt_successor'},
 ('_condition_ing_19', 'ing_ip_acl_ACTION'): {'delay': 0,
                                              'dep_type': 'rmt_successor'},
 ('_condition_ing_2', 'ing_spanning_tree_ACTION'): {'delay': 0,
                                                    'dep_type': 'rmt_successor'},
 ('_condition_ing_21', '_condition_ing_22'): {'delay': 0,
                                              'dep_type': 'rmt_successor'},
 ('_condition_ing_21', '_condition_ing_23'): {'delay': 0,
                                              'dep_type': 'rmt_successor'},
 ('_condition_ing_22', 'ing_ipv4_multicast_bridge_ACTION'): {'delay': 0,
                                                             'dep_type': 'rmt_successor'},
 ('_condition_ing_23', 'ing_ipv4_multicast_route_ACTION'): {'delay': 0,
                                                            'dep_type': 'rmt_successor'},
 ('_condition_ing_25', '_condition_ing_26'): {'delay': 0,
                                              'dep_type': 'rmt_successor'},
 ('_condition_ing_25', '_condition_ing_29'): {'delay': 0,
                                              'dep_type': 'rmt_successor'},
 ('_condition_ing_26', '_condition_ing_27'): {'delay': 0,
                                              'dep_type': 'rmt_successor'},
 ('_condition_ing_26', 'ing_ipv4_fib_ACTION'): {'delay': 0,
                                                'dep_type': 'rmt_successor'},
 ('_condition_ing_26', 'ing_ipv4_racl_ACTION'): {'delay': 0,
                                                 'dep_type': 'rmt_successor'},
 ('_condition_ing_27', 'ing_ipv4_urpf_ACTION'): {'delay': 0,
                                                 'dep_type': 'rmt_successor'},
 ('_condition_ing_29', 'ing_urpf_bd_ACTION'): {'delay': 0,
                                               'dep_type': 'rmt_successor'},
 ('_condition_ing_3', '_condition_ing_4'): {'delay': 0,
                                            'dep_type': 'rmt_successor'},
 ('_condition_ing_30', 'ing_meter_index_ACTION'): {'delay': 0,
                                                   'dep_type': 'rmt_successor'},
 ('_condition_ing_31', 'ing_compute_ipv4_hashes_ACTION'): {'delay': 0,
                                                           'dep_type': 'rmt_successor'},
 ('_condition_ing_31', 'ing_compute_non_ip_hashes_ACTION'): {'delay': 0,
                                                             'dep_type': 'rmt_successor'},
 ('_condition_ing_32', 'ing_meter_action_ACTION'): {'delay': 0,
                                                    'dep_type': 'rmt_successor'},
 ('_condition_ing_33', '_condition_ing_34'): {'delay': 0,
                                              'dep_type': 'rmt_successor'},
 ('_condition_ing_33', '_condition_ing_35'): {'delay': 0,
                                              'dep_type': 'rmt_successor'},
 ('_condition_ing_33', '_condition_ing_36'): {'delay': 0,
                                              'dep_type': 'rmt_successor'},
 ('_condition_ing_33', '_condition_ing_37'): {'delay': 0,
                                              'dep_type': 'rmt_successor'},
 ('_condition_ing_33', 'ing_acl_stats_ACTION'): {'delay': 0,
                                                 'dep_type': 'rmt_successor'},
 ('_condition_ing_33', 'ing_ingress_bd_stats_ACTION'): {'delay': 0,
                                                        'dep_type': 'rmt_successor'},
 ('_condition_ing_33', 'ing_storm_control_stats_ACTION'): {'delay': 0,
                                                           'dep_type': 'rmt_successor'},
 ('_condition_ing_34', 'ing_fwd_result_ACTION'): {'delay': 0,
                                                  'dep_type': 'rmt_successor'},
 ('_condition_ing_35', 'ing_ecmp_group_ACTION'): {'delay': 0,
                                                  'dep_type': 'rmt_successor'},
 ('_condition_ing_35', 'ing_nexthop_ACTION'): {'delay': 0,
                                               'dep_type': 'rmt_successor'},
 ('_condition_ing_36', 'ing_bd_flood_ACTION'): {'delay': 0,
                                                'dep_type': 'rmt_successor'},
 ('_condition_ing_36', 'ing_lag_group_ACTION'): {'delay': 0,
                                                 'dep_type': 'rmt_successor'},
 ('_condition_ing_37', 'ing_learn_notify_ACTION'): {'delay': 0,
                                                    'dep_type': 'rmt_successor'},
 ('_condition_ing_38', '_condition_ing_39'): {'delay': 0,
                                              'dep_type': 'rmt_successor'},
 ('_condition_ing_39', '_condition_ing_40'): {'delay': 0,
                                              'dep_type': 'rmt_successor'},
 ('_condition_ing_39', 'ing_system_acl_ACTION'): {'delay': 0,
                                                  'dep_type': 'rmt_successor'},
 ('_condition_ing_4', '_condition_ing_5'): {'delay': 0,
                                            'dep_type': 'rmt_successor'},
 ('_condition_ing_4', 'ing_ingress_qos_map_dscp_ACTION'): {'delay': 0,
                                                           'dep_type': 'rmt_successor'},
 ('_condition_ing_40', 'ing_drop_stats_ACTION'): {'delay': 0,
                                                  'dep_type': 'rmt_successor'},
 ('_condition_ing_5', 'ing_ingress_qos_map_pcp_ACTION'): {'delay': 0,
                                                          'dep_type': 'rmt_successor'},
 ('_condition_ing_6', 'ing_ipsg_ACTION'): {'delay': 0,
                                           'dep_type': 'rmt_successor'},
 ('_condition_ing_6', 'ing_ipsg_permit_special_ACTION'): {'delay': 0,
                                                          'dep_type': 'rmt_successor'},
 ('_condition_ing_7', '_condition_ing_8'): {'delay': 0,
                                            'dep_type': 'rmt_successor'},
 ('_condition_ing_7', 'ing_fabric_ingress_dst_lkp_ACTION'): {'delay': 0,
                                                             'dep_type': 'rmt_successor'},
 ('_condition_ing_8', '_condition_ing_10'): {'delay': 0,
                                             'dep_type': 'rmt_successor'},
 ('_condition_ing_8', '_condition_ing_9'): {'delay': 0,
                                            'dep_type': 'rmt_successor'},
 ('_condition_ing_9', 'ing_fabric_ingress_src_lkp_ACTION'): {'delay': 0,
                                                             'dep_type': 'rmt_successor'},
 ('egr_egress_bd_map_ACTION', '_condition_egr_48'): {'delay': 1,
                                                     'dep_type': 'rmt_match'},
 ('egr_egress_bd_map_ACTION', 'egr_smac_rewrite_MATCH'): {'delay': 1,
                                                          'dep_type': 'rmt_match'},
 ('egr_egress_bd_map_MATCH', 'egr_egress_bd_map_ACTION'): {'delay': 9,
                                                           'dep_type': 'new_match_to_action'},
 ('egr_egress_bd_stats_MATCH', 'egr_egress_bd_stats_ACTION'): {'delay': 9,
                                                               'dep_type': 'new_match_to_action'},
 ('egr_egress_filter_ACTION', '_condition_egr_51'): {'delay': 1,
                                                     'dep_type': 'rmt_match'},
 ('egr_egress_nat_MATCH', 'egr_egress_nat_ACTION'): {'delay': 9,
                                                     'dep_type': 'new_match_to_action'},
 ('egr_egress_port_mapping_ACTION', '_condition_egr_49'): {'delay': 1,
                                                           'dep_type': 'rmt_match'},
 ('egr_egress_port_mapping_ACTION', '_condition_egr_51'): {'delay': 1,
                                                           'dep_type': 'rmt_match'},
 ('egr_egress_port_mapping_ACTION', 'egr_egress_filter_ACTION'): {'delay': 1,
                                                                  'dep_type': 'rmt_action'},
 ('egr_egress_port_mapping_ACTION', 'egr_egress_qos_map_MATCH'): {'delay': 1,
                                                                  'dep_type': 'rmt_match'},
 ('egr_egress_port_mapping_ACTION', 'egr_egress_vlan_xlate_MATCH'): {'delay': 1,
                                                                     'dep_type': 'rmt_match'},
 ('egr_egress_port_mapping_MATCH', '_condition_egr_44'): {'delay': 9,
                                                          'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('egr_egress_port_mapping_MATCH', '_condition_egr_45'): {'delay': 9,
                                                          'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('egr_egress_port_mapping_MATCH', '_condition_egr_46'): {'delay': 9,
                                                          'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('egr_egress_port_mapping_MATCH', '_condition_egr_47'): {'delay': 9,
                                                          'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('egr_egress_port_mapping_MATCH', '_condition_egr_48'): {'delay': 9,
                                                          'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('egr_egress_port_mapping_MATCH', 'egr_egress_bd_map_ACTION'): {'delay': 9,
                                                                 'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('egr_egress_port_mapping_MATCH', 'egr_egress_bd_stats_ACTION'): {'delay': 9,
                                                                   'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('egr_egress_port_mapping_MATCH', 'egr_egress_port_mapping_ACTION'): {'delay': 9,
                                                                       'dep_type': 'new_match_to_action'},
 ('egr_egress_port_mapping_MATCH', 'egr_mtu_ACTION'): {'delay': 9,
                                                       'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('egr_egress_qos_map_ACTION', 'egr_l3_rewrite_ACTION'): {'delay': 1,
                                                          'dep_type': 'rmt_action'},
 ('egr_egress_qos_map_MATCH', 'egr_egress_qos_map_ACTION'): {'delay': 9,
                                                             'dep_type': 'new_match_to_action'},
 ('egr_egress_system_acl_MATCH', 'egr_egress_system_acl_ACTION'): {'delay': 9,
                                                                   'dep_type': 'new_match_to_action'},
 ('egr_egress_vlan_xlate_MATCH', 'egr_egress_vlan_xlate_ACTION'): {'delay': 9,
                                                                   'dep_type': 'new_match_to_action'},
 ('egr_l3_rewrite_ACTION', 'egr_egress_nat_ACTION'): {'delay': 0,
                                                      'dep_type': 'rmt_reverse_read'},
 ('egr_l3_rewrite_MATCH', 'egr_l3_rewrite_ACTION'): {'delay': 9,
                                                     'dep_type': 'new_match_to_action'},
 ('egr_mirror_ACTION', '_condition_egr_45'): {'delay': 1,
                                              'dep_type': 'rmt_match'},
 ('egr_mirror_ACTION', 'egr_egress_bd_map_MATCH'): {'delay': 1,
                                                    'dep_type': 'rmt_match'},
 ('egr_mirror_ACTION', 'egr_egress_bd_stats_MATCH'): {'delay': 1,
                                                      'dep_type': 'rmt_match'},
 ('egr_mirror_ACTION', 'egr_egress_filter_ACTION'): {'delay': 1,
                                                     'dep_type': 'rmt_action'},
 ('egr_mirror_ACTION', 'egr_egress_system_acl_ACTION'): {'delay': 0,
                                                         'dep_type': 'rmt_reverse_read'},
 ('egr_mirror_ACTION', 'egr_egress_vlan_xlate_MATCH'): {'delay': 1,
                                                        'dep_type': 'rmt_match'},
 ('egr_mirror_ACTION', 'egr_rewrite_MATCH'): {'delay': 1,
                                              'dep_type': 'rmt_match'},
 ('egr_mirror_MATCH', 'egr_mirror_ACTION'): {'delay': 9,
                                             'dep_type': 'new_match_to_action'},
 ('egr_mtu_ACTION', 'egr_egress_system_acl_MATCH'): {'delay': 1,
                                                     'dep_type': 'rmt_match'},
 ('egr_mtu_MATCH', 'egr_mtu_ACTION'): {'delay': 9,
                                       'dep_type': 'new_match_to_action'},
 ('egr_replica_type_ACTION', '_condition_egr_45'): {'delay': 1,
                                                    'dep_type': 'rmt_match'},
 ('egr_replica_type_ACTION', '_condition_egr_47'): {'delay': 1,
                                                    'dep_type': 'rmt_match'},
 ('egr_replica_type_ACTION', 'egr_rewrite_ACTION'): {'delay': 1,
                                                     'dep_type': 'rmt_action'},
 ('egr_replica_type_MATCH', 'egr_replica_type_ACTION'): {'delay': 9,
                                                         'dep_type': 'new_match_to_action'},
 ('egr_rewrite_ACTION', '_condition_egr_47'): {'delay': 1,
                                               'dep_type': 'rmt_match'},
 ('egr_rewrite_ACTION', '_condition_egr_51'): {'delay': 1,
                                               'dep_type': 'rmt_match'},
 ('egr_rewrite_ACTION', 'egr_egress_bd_map_MATCH'): {'delay': 1,
                                                     'dep_type': 'rmt_match'},
 ('egr_rewrite_ACTION', 'egr_egress_bd_stats_MATCH'): {'delay': 1,
                                                       'dep_type': 'rmt_match'},
 ('egr_rewrite_ACTION', 'egr_egress_filter_ACTION'): {'delay': 1,
                                                      'dep_type': 'rmt_action'},
 ('egr_rewrite_ACTION', 'egr_egress_vlan_xlate_MATCH'): {'delay': 1,
                                                         'dep_type': 'rmt_match'},
 ('egr_rewrite_ACTION', 'egr_l3_rewrite_ACTION'): {'delay': 1,
                                                   'dep_type': 'rmt_action'},
 ('egr_rewrite_ACTION', 'egr_mtu_MATCH'): {'delay': 1,
                                           'dep_type': 'rmt_match'},
 ('egr_rewrite_MATCH', 'egr_rewrite_ACTION'): {'delay': 9,
                                               'dep_type': 'new_match_to_action'},
 ('egr_rewrite_multicast_ACTION', 'egr_egress_nat_ACTION'): {'delay': 0,
                                                             'dep_type': 'rmt_reverse_read'},
 ('egr_rewrite_multicast_ACTION', 'egr_l3_rewrite_ACTION'): {'delay': 1,
                                                             'dep_type': 'rmt_action'},
 ('egr_rewrite_multicast_MATCH', 'egr_rewrite_multicast_ACTION'): {'delay': 9,
                                                                   'dep_type': 'new_match_to_action'},
 ('egr_rid_ACTION', '_condition_egr_45'): {'delay': 1,
                                           'dep_type': 'rmt_match'},
 ('egr_rid_ACTION', '_condition_egr_47'): {'delay': 1,
                                           'dep_type': 'rmt_match'},
 ('egr_rid_ACTION', '_condition_egr_50'): {'delay': 1,
                                           'dep_type': 'rmt_match'},
 ('egr_rid_ACTION', '_condition_egr_51'): {'delay': 1,
                                           'dep_type': 'rmt_match'},
 ('egr_rid_ACTION', 'egr_egress_bd_map_MATCH'): {'delay': 1,
                                                 'dep_type': 'rmt_match'},
 ('egr_rid_ACTION', 'egr_egress_bd_stats_MATCH'): {'delay': 1,
                                                   'dep_type': 'rmt_match'},
 ('egr_rid_ACTION', 'egr_egress_filter_ACTION'): {'delay': 1,
                                                  'dep_type': 'rmt_action'},
 ('egr_rid_ACTION', 'egr_egress_port_mapping_ACTION'): {'delay': 1,
                                                        'dep_type': 'rmt_action'},
 ('egr_rid_ACTION', 'egr_egress_vlan_xlate_MATCH'): {'delay': 1,
                                                     'dep_type': 'rmt_match'},
 ('egr_rid_ACTION', 'egr_replica_type_MATCH'): {'delay': 1,
                                                'dep_type': 'rmt_match'},
 ('egr_rid_ACTION', 'egr_rewrite_ACTION'): {'delay': 1,
                                            'dep_type': 'rmt_action'},
 ('egr_rid_MATCH', 'egr_rid_ACTION'): {'delay': 9,
                                       'dep_type': 'new_match_to_action'},
 ('egr_smac_rewrite_MATCH', 'egr_smac_rewrite_ACTION'): {'delay': 9,
                                                         'dep_type': 'new_match_to_action'},
 ('egr_vlan_decap_ACTION', 'egr_egress_vlan_xlate_ACTION'): {'delay': 1,
                                                             'dep_type': 'rmt_action'},
 ('egr_vlan_decap_MATCH', 'egr_vlan_decap_ACTION'): {'delay': 9,
                                                     'dep_type': 'new_match_to_action'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_compute_ipv4_hashes_ACTION'): {'delay': 1,
                                                                      'dep_type': 'rmt_action'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_compute_non_ip_hashes_ACTION'): {'delay': 1,
                                                                        'dep_type': 'rmt_action'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_dmac_MATCH'): {'delay': 1,
                                                      'dep_type': 'rmt_match'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_ingress_l4_dst_port_MATCH'): {'delay': 1,
                                                                     'dep_type': 'rmt_match'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_ingress_l4_src_port_MATCH'): {'delay': 1,
                                                                     'dep_type': 'rmt_match'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_ip_acl_MATCH'): {'delay': 1,
                                                        'dep_type': 'rmt_match'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_ipsg_MATCH'): {'delay': 1,
                                                      'dep_type': 'rmt_match'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_ipsg_permit_special_MATCH'): {'delay': 1,
                                                                     'dep_type': 'rmt_match'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_ipv4_fib_MATCH'): {'delay': 1,
                                                          'dep_type': 'rmt_match'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_ipv4_fib_lpm_MATCH'): {'delay': 1,
                                                              'dep_type': 'rmt_match'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_ipv4_multicast_bridge_MATCH'): {'delay': 1,
                                                                       'dep_type': 'rmt_match'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_ipv4_multicast_bridge_star_g_MATCH'): {'delay': 1,
                                                                              'dep_type': 'rmt_match'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_ipv4_multicast_route_MATCH'): {'delay': 1,
                                                                      'dep_type': 'rmt_match'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_ipv4_multicast_route_star_g_MATCH'): {'delay': 1,
                                                                             'dep_type': 'rmt_match'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_ipv4_racl_MATCH'): {'delay': 1,
                                                           'dep_type': 'rmt_match'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_ipv4_urpf_MATCH'): {'delay': 1,
                                                           'dep_type': 'rmt_match'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_ipv4_urpf_lpm_MATCH'): {'delay': 1,
                                                               'dep_type': 'rmt_match'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_learn_notify_ACTION'): {'delay': 1,
                                                               'dep_type': 'rmt_action'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_mac_acl_MATCH'): {'delay': 1,
                                                         'dep_type': 'rmt_match'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_nat_dst_MATCH'): {'delay': 1,
                                                         'dep_type': 'rmt_match'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_nat_flow_MATCH'): {'delay': 1,
                                                          'dep_type': 'rmt_match'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_nat_src_MATCH'): {'delay': 1,
                                                         'dep_type': 'rmt_match'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_nat_twice_MATCH'): {'delay': 1,
                                                           'dep_type': 'rmt_match'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_native_packet_over_fabric_ACTION'): {'delay': 1,
                                                                            'dep_type': 'rmt_action'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_rmac_MATCH'): {'delay': 1,
                                                      'dep_type': 'rmt_match'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_smac_MATCH'): {'delay': 1,
                                                      'dep_type': 'rmt_match'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_system_acl_MATCH'): {'delay': 1,
                                                            'dep_type': 'rmt_match'},
 ('ing_adjust_lkp_fields_ACTION', 'ing_validate_packet_MATCH'): {'delay': 1,
                                                                 'dep_type': 'rmt_match'},
 ('ing_adjust_lkp_fields_MATCH', 'ing_adjust_lkp_fields_ACTION'): {'delay': 9,
                                                                   'dep_type': 'new_match_to_action'},
 ('ing_bd_flood_ACTION', 'ing_fabric_lag_ACTION'): {'delay': 1,
                                                    'dep_type': 'rmt_action'},
 ('ing_bd_flood_MATCH', 'ing_bd_flood_ACTION'): {'delay': 9,
                                                 'dep_type': 'new_match_to_action'},
 ('ing_compute_ipv4_hashes_ACTION', 'ing_compute_other_hashes_MATCH'): {'delay': 1,
                                                                        'dep_type': 'rmt_match'},
 ('ing_compute_ipv4_hashes_ACTION', 'ing_ecmp_group_MATCH'): {'delay': 1,
                                                              'dep_type': 'rmt_match'},
 ('ing_compute_ipv4_hashes_ACTION', 'ing_fabric_lag_MATCH'): {'delay': 1,
                                                              'dep_type': 'rmt_match'},
 ('ing_compute_ipv4_hashes_ACTION', 'ing_fwd_result_ACTION'): {'delay': 0,
                                                               'dep_type': 'rmt_reverse_read'},
 ('ing_compute_ipv4_hashes_ACTION', 'ing_lag_group_MATCH'): {'delay': 1,
                                                             'dep_type': 'rmt_match'},
 ('ing_compute_ipv4_hashes_MATCH', 'ing_compute_ipv4_hashes_ACTION'): {'delay': 9,
                                                                       'dep_type': 'new_match_to_action'},
 ('ing_compute_non_ip_hashes_ACTION', 'ing_compute_other_hashes_ACTION'): {'delay': 1,
                                                                           'dep_type': 'rmt_action'},
 ('ing_compute_non_ip_hashes_ACTION', 'ing_fabric_lag_MATCH'): {'delay': 1,
                                                                'dep_type': 'rmt_match'},
 ('ing_compute_non_ip_hashes_ACTION', 'ing_fwd_result_ACTION'): {'delay': 0,
                                                                 'dep_type': 'rmt_reverse_read'},
 ('ing_compute_non_ip_hashes_ACTION', 'ing_lag_group_MATCH'): {'delay': 1,
                                                               'dep_type': 'rmt_match'},
 ('ing_compute_non_ip_hashes_MATCH', 'ing_compute_non_ip_hashes_ACTION'): {'delay': 9,
                                                                           'dep_type': 'new_match_to_action'},
 ('ing_compute_other_hashes_ACTION', 'ing_ecmp_group_MATCH'): {'delay': 1,
                                                               'dep_type': 'rmt_match'},
 ('ing_compute_other_hashes_MATCH', 'ing_compute_other_hashes_ACTION'): {'delay': 9,
                                                                         'dep_type': 'new_match_to_action'},
 ('ing_dmac_ACTION', '_condition_ing_36'): {'delay': 1,
                                            'dep_type': 'rmt_match'},
 ('ing_dmac_ACTION', 'ing_bd_flood_ACTION'): {'delay': 1,
                                              'dep_type': 'rmt_action'},
 ('ing_dmac_ACTION', 'ing_ecmp_group_ACTION'): {'delay': 1,
                                                'dep_type': 'rmt_action'},
 ('ing_dmac_ACTION', 'ing_fabric_lag_MATCH'): {'delay': 1,
                                               'dep_type': 'rmt_match'},
 ('ing_dmac_ACTION', 'ing_fwd_result_MATCH'): {'delay': 1,
                                               'dep_type': 'rmt_match'},
 ('ing_dmac_ACTION', 'ing_lag_group_MATCH'): {'delay': 1,
                                              'dep_type': 'rmt_match'},
 ('ing_dmac_ACTION', 'ing_nexthop_ACTION'): {'delay': 1,
                                             'dep_type': 'rmt_action'},
 ('ing_dmac_ACTION', 'ing_system_acl_MATCH'): {'delay': 1,
                                               'dep_type': 'rmt_match'},
 ('ing_dmac_MATCH', 'ing_dmac_ACTION'): {'delay': 9,
                                         'dep_type': 'new_match_to_action'},
 ('ing_ecmp_group_ACTION', '_condition_ing_36'): {'delay': 1,
                                                  'dep_type': 'rmt_match'},
 ('ing_ecmp_group_ACTION', 'ing_bd_flood_ACTION'): {'delay': 1,
                                                    'dep_type': 'rmt_action'},
 ('ing_ecmp_group_ACTION', 'ing_fabric_lag_MATCH'): {'delay': 1,
                                                     'dep_type': 'rmt_match'},
 ('ing_ecmp_group_ACTION', 'ing_lag_group_MATCH'): {'delay': 1,
                                                    'dep_type': 'rmt_match'},
 ('ing_ecmp_group_ACTION', 'ing_system_acl_MATCH'): {'delay': 1,
                                                     'dep_type': 'rmt_match'},
 ('ing_ecmp_group_MATCH', 'ing_ecmp_group_ACTION'): {'delay': 9,
                                                     'dep_type': 'new_match_to_action'},
 ('ing_fabric_ingress_dst_lkp_ACTION', '_condition_ing_10'): {'delay': 1,
                                                              'dep_type': 'rmt_match'},
 ('ing_fabric_ingress_dst_lkp_ACTION', '_condition_ing_31'): {'delay': 1,
                                                              'dep_type': 'rmt_match'},
 ('ing_fabric_ingress_dst_lkp_ACTION', '_condition_ing_9'): {'delay': 1,
                                                             'dep_type': 'rmt_match'},
 ('ing_fabric_ingress_dst_lkp_ACTION', 'ing_bd_flood_ACTION'): {'delay': 1,
                                                                'dep_type': 'rmt_action'},
 ('ing_fabric_ingress_dst_lkp_ACTION', 'ing_dmac_ACTION'): {'delay': 1,
                                                            'dep_type': 'rmt_action'},
 ('ing_fabric_ingress_dst_lkp_ACTION', 'ing_ecmp_group_MATCH'): {'delay': 1,
                                                                 'dep_type': 'rmt_match'},
 ('ing_fabric_ingress_dst_lkp_ACTION', 'ing_fabric_ingress_src_lkp_MATCH'): {'delay': 1,
                                                                             'dep_type': 'rmt_match'},
 ('ing_fabric_ingress_dst_lkp_ACTION', 'ing_fabric_lag_MATCH'): {'delay': 1,
                                                                 'dep_type': 'rmt_match'},
 ('ing_fabric_ingress_dst_lkp_ACTION', 'ing_fwd_result_ACTION'): {'delay': 1,
                                                                  'dep_type': 'rmt_action'},
 ('ing_fabric_ingress_dst_lkp_ACTION', 'ing_lag_group_ACTION'): {'delay': 1,
                                                                 'dep_type': 'rmt_action'},
 ('ing_fabric_ingress_dst_lkp_ACTION', 'ing_native_packet_over_fabric_ACTION'): {'delay': 1,
                                                                                 'dep_type': 'rmt_action'},
 ('ing_fabric_ingress_dst_lkp_ACTION', 'ing_nexthop_MATCH'): {'delay': 1,
                                                              'dep_type': 'rmt_match'},
 ('ing_fabric_ingress_dst_lkp_ACTION', 'ing_system_acl_MATCH'): {'delay': 1,
                                                                 'dep_type': 'rmt_match'},
 ('ing_fabric_ingress_dst_lkp_MATCH', 'ing_fabric_ingress_dst_lkp_ACTION'): {'delay': 9,
                                                                             'dep_type': 'new_match_to_action'},
 ('ing_fabric_ingress_src_lkp_MATCH', 'ing_fabric_ingress_src_lkp_ACTION'): {'delay': 9,
                                                                             'dep_type': 'new_match_to_action'},
 ('ing_fabric_lag_ACTION', 'ing_system_acl_ACTION'): {'delay': 0,
                                                      'dep_type': 'rmt_reverse_read'},
 ('ing_fabric_lag_MATCH', 'ing_fabric_lag_ACTION'): {'delay': 9,
                                                     'dep_type': 'new_match_to_action'},
 ('ing_fwd_result_ACTION', '_condition_ing_35'): {'delay': 1,
                                                  'dep_type': 'rmt_match'},
 ('ing_fwd_result_ACTION', '_condition_ing_36'): {'delay': 1,
                                                  'dep_type': 'rmt_match'},
 ('ing_fwd_result_ACTION', '_condition_ing_40'): {'delay': 1,
                                                  'dep_type': 'rmt_match'},
 ('ing_fwd_result_ACTION', 'ing_bd_flood_ACTION'): {'delay': 1,
                                                    'dep_type': 'rmt_action'},
 ('ing_fwd_result_ACTION', 'ing_drop_stats_ACTION'): {'delay': 1,
                                                      'dep_type': 'rmt_action'},
 ('ing_fwd_result_ACTION', 'ing_ecmp_group_MATCH'): {'delay': 1,
                                                     'dep_type': 'rmt_match'},
 ('ing_fwd_result_ACTION', 'ing_fabric_lag_MATCH'): {'delay': 1,
                                                     'dep_type': 'rmt_match'},
 ('ing_fwd_result_ACTION', 'ing_lag_group_MATCH'): {'delay': 1,
                                                    'dep_type': 'rmt_match'},
 ('ing_fwd_result_ACTION', 'ing_nexthop_MATCH'): {'delay': 1,
                                                  'dep_type': 'rmt_match'},
 ('ing_fwd_result_ACTION', 'ing_system_acl_MATCH'): {'delay': 1,
                                                     'dep_type': 'rmt_match'},
 ('ing_fwd_result_MATCH', 'ing_fwd_result_ACTION'): {'delay': 9,
                                                     'dep_type': 'new_match_to_action'},
 ('ing_ingress_l4_dst_port_ACTION', 'ing_ip_acl_MATCH'): {'delay': 1,
                                                          'dep_type': 'rmt_match'},
 ('ing_ingress_l4_dst_port_ACTION', 'ing_ipv4_racl_MATCH'): {'delay': 1,
                                                             'dep_type': 'rmt_match'},
 ('ing_ingress_l4_dst_port_MATCH', 'ing_ingress_l4_dst_port_ACTION'): {'delay': 9,
                                                                       'dep_type': 'new_match_to_action'},
 ('ing_ingress_l4_src_port_ACTION', 'ing_ip_acl_MATCH'): {'delay': 1,
                                                          'dep_type': 'rmt_match'},
 ('ing_ingress_l4_src_port_ACTION', 'ing_ipv4_racl_MATCH'): {'delay': 1,
                                                             'dep_type': 'rmt_match'},
 ('ing_ingress_l4_src_port_MATCH', 'ing_ingress_l4_src_port_ACTION'): {'delay': 9,
                                                                       'dep_type': 'new_match_to_action'},
 ('ing_ingress_port_mapping_ACTION', '_condition_ing_11'): {'delay': 1,
                                                            'dep_type': 'rmt_match'},
 ('ing_ingress_port_mapping_ACTION', '_condition_ing_12'): {'delay': 1,
                                                            'dep_type': 'rmt_match'},
 ('ing_ingress_port_mapping_ACTION', '_condition_ing_14'): {'delay': 1,
                                                            'dep_type': 'rmt_match'},
 ('ing_ingress_port_mapping_ACTION', '_condition_ing_2'): {'delay': 1,
                                                           'dep_type': 'rmt_match'},
 ('ing_ingress_port_mapping_ACTION', '_condition_ing_33'): {'delay': 1,
                                                            'dep_type': 'rmt_match'},
 ('ing_ingress_port_mapping_ACTION', '_condition_ing_38'): {'delay': 1,
                                                            'dep_type': 'rmt_match'},
 ('ing_ingress_port_mapping_ACTION', '_condition_ing_6'): {'delay': 1,
                                                           'dep_type': 'rmt_match'},
 ('ing_ingress_port_mapping_ACTION', '_condition_ing_7'): {'delay': 1,
                                                           'dep_type': 'rmt_match'},
 ('ing_ingress_port_mapping_ACTION', '_condition_ing_8'): {'delay': 1,
                                                           'dep_type': 'rmt_match'},
 ('ing_ingress_port_mapping_ACTION', 'ing_compute_non_ip_hashes_ACTION'): {'delay': 1,
                                                                           'dep_type': 'rmt_action'},
 ('ing_ingress_port_mapping_ACTION', 'ing_ipsg_MATCH'): {'delay': 1,
                                                         'dep_type': 'rmt_match'},
 ('ing_ingress_port_mapping_ACTION', 'ing_learn_notify_ACTION'): {'delay': 1,
                                                                  'dep_type': 'rmt_action'},
 ('ing_ingress_port_mapping_ACTION', 'ing_port_vlan_mapping_MATCH'): {'delay': 1,
                                                                      'dep_type': 'rmt_match'},
 ('ing_ingress_port_mapping_ACTION', 'ing_smac_ACTION'): {'delay': 1,
                                                          'dep_type': 'rmt_action'},
 ('ing_ingress_port_mapping_ACTION', 'ing_spanning_tree_MATCH'): {'delay': 1,
                                                                  'dep_type': 'rmt_match'},
 ('ing_ingress_port_mapping_ACTION', 'ing_switch_config_params_ACTION'): {'delay': 1,
                                                                          'dep_type': 'rmt_action'},
 ('ing_ingress_port_mapping_ACTION', 'ing_system_acl_MATCH'): {'delay': 1,
                                                               'dep_type': 'rmt_match'},
 ('ing_ingress_port_mapping_MATCH', 'ing_ingress_port_mapping_ACTION'): {'delay': 9,
                                                                         'dep_type': 'new_match_to_action'},
 ('ing_ingress_port_properties_ACTION', '_condition_ing_4'): {'delay': 1,
                                                              'dep_type': 'rmt_match'},
 ('ing_ingress_port_properties_ACTION', '_condition_ing_5'): {'delay': 1,
                                                              'dep_type': 'rmt_match'},
 ('ing_ingress_port_properties_ACTION', 'ing_ingress_qos_map_dscp_MATCH'): {'delay': 1,
                                                                            'dep_type': 'rmt_match'},
 ('ing_ingress_port_properties_ACTION', 'ing_ingress_qos_map_pcp_MATCH'): {'delay': 1,
                                                                           'dep_type': 'rmt_match'},
 ('ing_ingress_port_properties_ACTION', 'ing_ip_acl_MATCH'): {'delay': 1,
                                                              'dep_type': 'rmt_match'},
 ('ing_ingress_port_properties_ACTION', 'ing_ipv4_racl_ACTION'): {'delay': 1,
                                                                  'dep_type': 'rmt_action'},
 ('ing_ingress_port_properties_ACTION', 'ing_mac_acl_MATCH'): {'delay': 1,
                                                               'dep_type': 'rmt_match'},
 ('ing_ingress_port_properties_ACTION', 'ing_meter_action_MATCH'): {'delay': 1,
                                                                    'dep_type': 'rmt_match'},
 ('ing_ingress_port_properties_ACTION', 'ing_meter_index_ACTION'): {'delay': 1,
                                                                    'dep_type': 'rmt_action'},
 ('ing_ingress_port_properties_ACTION', 'ing_storm_control_ACTION'): {'delay': 1,
                                                                      'dep_type': 'rmt_action'},
 ('ing_ingress_port_properties_ACTION', 'ing_storm_control_stats_MATCH'): {'delay': 1,
                                                                           'dep_type': 'rmt_match'},
 ('ing_ingress_port_properties_ACTION', 'ing_system_acl_MATCH'): {'delay': 1,
                                                                  'dep_type': 'rmt_match'},
 ('ing_ingress_port_properties_ACTION', 'ing_traffic_class_MATCH'): {'delay': 1,
                                                                     'dep_type': 'rmt_match'},
 ('ing_ingress_port_properties_MATCH', 'ing_ingress_port_properties_ACTION'): {'delay': 9,
                                                                               'dep_type': 'new_match_to_action'},
 ('ing_ingress_qos_map_dscp_ACTION', 'ing_ip_acl_ACTION'): {'delay': 1,
                                                            'dep_type': 'rmt_action'},
 ('ing_ingress_qos_map_dscp_ACTION', 'ing_ipv4_racl_ACTION'): {'delay': 1,
                                                               'dep_type': 'rmt_action'},
 ('ing_ingress_qos_map_dscp_ACTION', 'ing_mac_acl_ACTION'): {'delay': 1,
                                                             'dep_type': 'rmt_action'},
 ('ing_ingress_qos_map_dscp_ACTION', 'ing_meter_action_MATCH'): {'delay': 1,
                                                                 'dep_type': 'rmt_match'},
 ('ing_ingress_qos_map_dscp_ACTION', 'ing_meter_index_ACTION'): {'delay': 1,
                                                                 'dep_type': 'rmt_action'},
 ('ing_ingress_qos_map_dscp_ACTION', 'ing_storm_control_ACTION'): {'delay': 1,
                                                                   'dep_type': 'rmt_action'},
 ('ing_ingress_qos_map_dscp_ACTION', 'ing_storm_control_stats_MATCH'): {'delay': 1,
                                                                        'dep_type': 'rmt_match'},
 ('ing_ingress_qos_map_dscp_ACTION', 'ing_traffic_class_MATCH'): {'delay': 1,
                                                                  'dep_type': 'rmt_match'},
 ('ing_ingress_qos_map_dscp_MATCH', 'ing_ingress_qos_map_dscp_ACTION'): {'delay': 9,
                                                                         'dep_type': 'new_match_to_action'},
 ('ing_ingress_qos_map_pcp_ACTION', 'ing_ip_acl_ACTION'): {'delay': 1,
                                                           'dep_type': 'rmt_action'},
 ('ing_ingress_qos_map_pcp_ACTION', 'ing_ipv4_racl_ACTION'): {'delay': 1,
                                                              'dep_type': 'rmt_action'},
 ('ing_ingress_qos_map_pcp_ACTION', 'ing_mac_acl_ACTION'): {'delay': 1,
                                                            'dep_type': 'rmt_action'},
 ('ing_ingress_qos_map_pcp_ACTION', 'ing_meter_action_MATCH'): {'delay': 1,
                                                                'dep_type': 'rmt_match'},
 ('ing_ingress_qos_map_pcp_ACTION', 'ing_meter_index_ACTION'): {'delay': 1,
                                                                'dep_type': 'rmt_action'},
 ('ing_ingress_qos_map_pcp_ACTION', 'ing_storm_control_ACTION'): {'delay': 1,
                                                                  'dep_type': 'rmt_action'},
 ('ing_ingress_qos_map_pcp_ACTION', 'ing_storm_control_stats_MATCH'): {'delay': 1,
                                                                       'dep_type': 'rmt_match'},
 ('ing_ingress_qos_map_pcp_ACTION', 'ing_traffic_class_MATCH'): {'delay': 1,
                                                                 'dep_type': 'rmt_match'},
 ('ing_ingress_qos_map_pcp_MATCH', 'ing_ingress_qos_map_pcp_ACTION'): {'delay': 9,
                                                                       'dep_type': 'new_match_to_action'},
 ('ing_ip_acl_ACTION', 'ing_acl_stats_ACTION'): {'delay': 1,
                                                 'dep_type': 'rmt_action'},
 ('ing_ip_acl_ACTION', 'ing_fwd_result_MATCH'): {'delay': 1,
                                                 'dep_type': 'rmt_match'},
 ('ing_ip_acl_ACTION', 'ing_ipv4_racl_ACTION'): {'delay': 1,
                                                 'dep_type': 'rmt_action'},
 ('ing_ip_acl_ACTION', 'ing_meter_action_MATCH'): {'delay': 1,
                                                   'dep_type': 'rmt_match'},
 ('ing_ip_acl_ACTION', 'ing_meter_index_MATCH'): {'delay': 1,
                                                  'dep_type': 'rmt_match'},
 ('ing_ip_acl_ACTION', 'ing_storm_control_stats_MATCH'): {'delay': 1,
                                                          'dep_type': 'rmt_match'},
 ('ing_ip_acl_ACTION', 'ing_system_acl_MATCH'): {'delay': 1,
                                                 'dep_type': 'rmt_match'},
 ('ing_ip_acl_ACTION', 'ing_traffic_class_MATCH'): {'delay': 1,
                                                    'dep_type': 'rmt_match'},
 ('ing_ip_acl_MATCH', 'ing_ip_acl_ACTION'): {'delay': 9,
                                             'dep_type': 'new_match_to_action'},
 ('ing_ipsg_ACTION', 'ing_native_packet_over_fabric_ACTION'): {'delay': 0,
                                                               'dep_type': 'rmt_reverse_read'},
 ('ing_ipsg_MATCH', 'ing_ipsg_ACTION'): {'delay': 9,
                                         'dep_type': 'new_match_to_action'},
 ('ing_ipsg_permit_special_ACTION', 'ing_native_packet_over_fabric_ACTION'): {'delay': 0,
                                                                              'dep_type': 'rmt_reverse_read'},
 ('ing_ipsg_permit_special_ACTION', 'ing_system_acl_MATCH'): {'delay': 1,
                                                              'dep_type': 'rmt_match'},
 ('ing_ipsg_permit_special_MATCH', 'ing_ipsg_permit_special_ACTION'): {'delay': 9,
                                                                       'dep_type': 'new_match_to_action'},
 ('ing_ipv4_fib_ACTION', 'ing_fwd_result_MATCH'): {'delay': 1,
                                                   'dep_type': 'rmt_match'},
 ('ing_ipv4_fib_MATCH', 'ing_ipv4_fib_ACTION'): {'delay': 9,
                                                 'dep_type': 'new_match_to_action'},
 ('ing_ipv4_fib_MATCH', 'ing_ipv4_fib_lpm_ACTION'): {'delay': 9,
                                                     'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('ing_ipv4_fib_lpm_ACTION', 'ing_fwd_result_MATCH'): {'delay': 1,
                                                       'dep_type': 'rmt_match'},
 ('ing_ipv4_fib_lpm_MATCH', 'ing_ipv4_fib_lpm_ACTION'): {'delay': 9,
                                                         'dep_type': 'new_match_to_action'},
 ('ing_ipv4_multicast_bridge_ACTION', 'ing_fwd_result_MATCH'): {'delay': 1,
                                                                'dep_type': 'rmt_match'},
 ('ing_ipv4_multicast_bridge_MATCH', 'ing_ipv4_multicast_bridge_ACTION'): {'delay': 9,
                                                                           'dep_type': 'new_match_to_action'},
 ('ing_ipv4_multicast_bridge_MATCH', 'ing_ipv4_multicast_bridge_star_g_ACTION'): {'delay': 9,
                                                                                  'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('ing_ipv4_multicast_bridge_star_g_ACTION', 'ing_fwd_result_MATCH'): {'delay': 1,
                                                                       'dep_type': 'rmt_match'},
 ('ing_ipv4_multicast_bridge_star_g_MATCH', 'ing_ipv4_multicast_bridge_star_g_ACTION'): {'delay': 9,
                                                                                         'dep_type': 'new_match_to_action'},
 ('ing_ipv4_multicast_route_ACTION', 'ing_fwd_result_MATCH'): {'delay': 1,
                                                               'dep_type': 'rmt_match'},
 ('ing_ipv4_multicast_route_MATCH', 'ing_ipv4_multicast_route_ACTION'): {'delay': 9,
                                                                         'dep_type': 'new_match_to_action'},
 ('ing_ipv4_multicast_route_MATCH', 'ing_ipv4_multicast_route_star_g_ACTION'): {'delay': 9,
                                                                                'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('ing_ipv4_multicast_route_star_g_ACTION', 'ing_fwd_result_MATCH'): {'delay': 1,
                                                                      'dep_type': 'rmt_match'},
 ('ing_ipv4_multicast_route_star_g_ACTION', 'ing_system_acl_MATCH'): {'delay': 1,
                                                                      'dep_type': 'rmt_match'},
 ('ing_ipv4_multicast_route_star_g_MATCH', 'ing_ipv4_multicast_route_star_g_ACTION'): {'delay': 9,
                                                                                       'dep_type': 'new_match_to_action'},
 ('ing_ipv4_racl_ACTION', 'ing_acl_stats_ACTION'): {'delay': 1,
                                                    'dep_type': 'rmt_action'},
 ('ing_ipv4_racl_ACTION', 'ing_fwd_result_MATCH'): {'delay': 1,
                                                    'dep_type': 'rmt_match'},
 ('ing_ipv4_racl_ACTION', 'ing_meter_action_MATCH'): {'delay': 1,
                                                      'dep_type': 'rmt_match'},
 ('ing_ipv4_racl_ACTION', 'ing_meter_index_ACTION'): {'delay': 1,
                                                      'dep_type': 'rmt_action'},
 ('ing_ipv4_racl_ACTION', 'ing_storm_control_stats_MATCH'): {'delay': 1,
                                                             'dep_type': 'rmt_match'},
 ('ing_ipv4_racl_ACTION', 'ing_system_acl_MATCH'): {'delay': 1,
                                                    'dep_type': 'rmt_match'},
 ('ing_ipv4_racl_ACTION', 'ing_traffic_class_MATCH'): {'delay': 1,
                                                       'dep_type': 'rmt_match'},
 ('ing_ipv4_racl_MATCH', 'ing_ipv4_racl_ACTION'): {'delay': 9,
                                                   'dep_type': 'new_match_to_action'},
 ('ing_ipv4_urpf_ACTION', '_condition_ing_29'): {'delay': 1,
                                                 'dep_type': 'rmt_match'},
 ('ing_ipv4_urpf_ACTION', 'ing_urpf_bd_MATCH'): {'delay': 1,
                                                 'dep_type': 'rmt_match'},
 ('ing_ipv4_urpf_MATCH', 'ing_ipv4_urpf_ACTION'): {'delay': 9,
                                                   'dep_type': 'new_match_to_action'},
 ('ing_ipv4_urpf_MATCH', 'ing_ipv4_urpf_lpm_ACTION'): {'delay': 9,
                                                       'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('ing_ipv4_urpf_lpm_ACTION', '_condition_ing_29'): {'delay': 1,
                                                     'dep_type': 'rmt_match'},
 ('ing_ipv4_urpf_lpm_ACTION', 'ing_system_acl_MATCH'): {'delay': 1,
                                                        'dep_type': 'rmt_match'},
 ('ing_ipv4_urpf_lpm_ACTION', 'ing_urpf_bd_MATCH'): {'delay': 1,
                                                     'dep_type': 'rmt_match'},
 ('ing_ipv4_urpf_lpm_MATCH', 'ing_ipv4_urpf_lpm_ACTION'): {'delay': 9,
                                                           'dep_type': 'new_match_to_action'},
 ('ing_lag_group_ACTION', 'ing_fabric_lag_MATCH'): {'delay': 1,
                                                    'dep_type': 'rmt_match'},
 ('ing_lag_group_ACTION', 'ing_system_acl_ACTION'): {'delay': 1,
                                                     'dep_type': 'rmt_action'},
 ('ing_lag_group_MATCH', 'ing_lag_group_ACTION'): {'delay': 9,
                                                   'dep_type': 'new_match_to_action'},
 ('ing_learn_notify_MATCH', 'ing_learn_notify_ACTION'): {'delay': 9,
                                                         'dep_type': 'new_match_to_action'},
 ('ing_mac_acl_ACTION', 'ing_acl_stats_ACTION'): {'delay': 1,
                                                  'dep_type': 'rmt_action'},
 ('ing_mac_acl_ACTION', 'ing_fwd_result_MATCH'): {'delay': 1,
                                                  'dep_type': 'rmt_match'},
 ('ing_mac_acl_ACTION', 'ing_ipv4_racl_ACTION'): {'delay': 1,
                                                  'dep_type': 'rmt_action'},
 ('ing_mac_acl_ACTION', 'ing_meter_action_MATCH'): {'delay': 1,
                                                    'dep_type': 'rmt_match'},
 ('ing_mac_acl_ACTION', 'ing_meter_index_MATCH'): {'delay': 1,
                                                   'dep_type': 'rmt_match'},
 ('ing_mac_acl_ACTION', 'ing_storm_control_stats_MATCH'): {'delay': 1,
                                                           'dep_type': 'rmt_match'},
 ('ing_mac_acl_ACTION', 'ing_system_acl_MATCH'): {'delay': 1,
                                                  'dep_type': 'rmt_match'},
 ('ing_mac_acl_ACTION', 'ing_traffic_class_MATCH'): {'delay': 1,
                                                     'dep_type': 'rmt_match'},
 ('ing_mac_acl_MATCH', 'ing_mac_acl_ACTION'): {'delay': 9,
                                               'dep_type': 'new_match_to_action'},
 ('ing_meter_action_MATCH', 'ing_meter_action_ACTION'): {'delay': 9,
                                                         'dep_type': 'new_match_to_action'},
 ('ing_meter_index_ACTION', 'ing_meter_action_MATCH'): {'delay': 1,
                                                        'dep_type': 'rmt_match'},
 ('ing_meter_index_ACTION', 'ing_storm_control_stats_MATCH'): {'delay': 1,
                                                               'dep_type': 'rmt_match'},
 ('ing_meter_index_MATCH', 'ing_meter_index_ACTION'): {'delay': 9,
                                                       'dep_type': 'new_match_to_action'},
 ('ing_nat_dst_ACTION', 'ing_fwd_result_MATCH'): {'delay': 1,
                                                  'dep_type': 'rmt_match'},
 ('ing_nat_dst_MATCH', 'ing_nat_dst_ACTION'): {'delay': 9,
                                               'dep_type': 'new_match_to_action'},
 ('ing_nat_dst_MATCH', 'ing_nat_src_ACTION'): {'delay': 9,
                                               'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('ing_nat_flow_ACTION', 'ing_fwd_result_MATCH'): {'delay': 1,
                                                   'dep_type': 'rmt_match'},
 ('ing_nat_flow_MATCH', 'ing_nat_flow_ACTION'): {'delay': 9,
                                                 'dep_type': 'new_match_to_action'},
 ('ing_nat_src_MATCH', 'ing_nat_flow_ACTION'): {'delay': 9,
                                                'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('ing_nat_src_MATCH', 'ing_nat_src_ACTION'): {'delay': 9,
                                               'dep_type': 'new_match_to_action'},
 ('ing_nat_twice_ACTION', 'ing_fwd_result_MATCH'): {'delay': 1,
                                                    'dep_type': 'rmt_match'},
 ('ing_nat_twice_MATCH', 'ing_nat_dst_ACTION'): {'delay': 9,
                                                 'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('ing_nat_twice_MATCH', 'ing_nat_twice_ACTION'): {'delay': 9,
                                                   'dep_type': 'new_match_to_action'},
 ('ing_native_packet_over_fabric_ACTION', 'ing_compute_ipv4_hashes_ACTION'): {'delay': 1,
                                                                              'dep_type': 'rmt_action'},
 ('ing_native_packet_over_fabric_ACTION', 'ing_compute_non_ip_hashes_ACTION'): {'delay': 1,
                                                                                'dep_type': 'rmt_action'},
 ('ing_native_packet_over_fabric_ACTION', 'ing_dmac_MATCH'): {'delay': 1,
                                                              'dep_type': 'rmt_match'},
 ('ing_native_packet_over_fabric_ACTION', 'ing_ingress_l4_dst_port_MATCH'): {'delay': 1,
                                                                             'dep_type': 'rmt_match'},
 ('ing_native_packet_over_fabric_ACTION', 'ing_ingress_l4_src_port_MATCH'): {'delay': 1,
                                                                             'dep_type': 'rmt_match'},
 ('ing_native_packet_over_fabric_ACTION', 'ing_ip_acl_MATCH'): {'delay': 1,
                                                                'dep_type': 'rmt_match'},
 ('ing_native_packet_over_fabric_ACTION', 'ing_ipv4_fib_MATCH'): {'delay': 1,
                                                                  'dep_type': 'rmt_match'},
 ('ing_native_packet_over_fabric_ACTION', 'ing_ipv4_fib_lpm_MATCH'): {'delay': 1,
                                                                      'dep_type': 'rmt_match'},
 ('ing_native_packet_over_fabric_ACTION', 'ing_ipv4_multicast_bridge_MATCH'): {'delay': 1,
                                                                               'dep_type': 'rmt_match'},
 ('ing_native_packet_over_fabric_ACTION', 'ing_ipv4_multicast_bridge_star_g_MATCH'): {'delay': 1,
                                                                                      'dep_type': 'rmt_match'},
 ('ing_native_packet_over_fabric_ACTION', 'ing_ipv4_multicast_route_MATCH'): {'delay': 1,
                                                                              'dep_type': 'rmt_match'},
 ('ing_native_packet_over_fabric_ACTION', 'ing_ipv4_multicast_route_star_g_MATCH'): {'delay': 1,
                                                                                     'dep_type': 'rmt_match'},
 ('ing_native_packet_over_fabric_ACTION', 'ing_ipv4_racl_MATCH'): {'delay': 1,
                                                                   'dep_type': 'rmt_match'},
 ('ing_native_packet_over_fabric_ACTION', 'ing_ipv4_urpf_MATCH'): {'delay': 1,
                                                                   'dep_type': 'rmt_match'},
 ('ing_native_packet_over_fabric_ACTION', 'ing_ipv4_urpf_lpm_MATCH'): {'delay': 1,
                                                                       'dep_type': 'rmt_match'},
 ('ing_native_packet_over_fabric_ACTION', 'ing_learn_notify_ACTION'): {'delay': 1,
                                                                       'dep_type': 'rmt_action'},
 ('ing_native_packet_over_fabric_ACTION', 'ing_mac_acl_MATCH'): {'delay': 1,
                                                                 'dep_type': 'rmt_match'},
 ('ing_native_packet_over_fabric_ACTION', 'ing_nat_dst_MATCH'): {'delay': 1,
                                                                 'dep_type': 'rmt_match'},
 ('ing_native_packet_over_fabric_ACTION', 'ing_nat_flow_MATCH'): {'delay': 1,
                                                                  'dep_type': 'rmt_match'},
 ('ing_native_packet_over_fabric_ACTION', 'ing_nat_src_MATCH'): {'delay': 1,
                                                                 'dep_type': 'rmt_match'},
 ('ing_native_packet_over_fabric_ACTION', 'ing_nat_twice_MATCH'): {'delay': 1,
                                                                   'dep_type': 'rmt_match'},
 ('ing_native_packet_over_fabric_ACTION', 'ing_rmac_MATCH'): {'delay': 1,
                                                              'dep_type': 'rmt_match'},
 ('ing_native_packet_over_fabric_ACTION', 'ing_smac_MATCH'): {'delay': 1,
                                                              'dep_type': 'rmt_match'},
 ('ing_native_packet_over_fabric_ACTION', 'ing_system_acl_MATCH'): {'delay': 1,
                                                                    'dep_type': 'rmt_match'},
 ('ing_native_packet_over_fabric_ACTION', 'ing_validate_packet_MATCH'): {'delay': 1,
                                                                         'dep_type': 'rmt_match'},
 ('ing_native_packet_over_fabric_MATCH', 'ing_native_packet_over_fabric_ACTION'): {'delay': 9,
                                                                                   'dep_type': 'new_match_to_action'},
 ('ing_nexthop_ACTION', '_condition_ing_36'): {'delay': 1,
                                               'dep_type': 'rmt_match'},
 ('ing_nexthop_ACTION', 'ing_bd_flood_ACTION'): {'delay': 1,
                                                 'dep_type': 'rmt_action'},
 ('ing_nexthop_ACTION', 'ing_fabric_lag_MATCH'): {'delay': 1,
                                                  'dep_type': 'rmt_match'},
 ('ing_nexthop_ACTION', 'ing_lag_group_MATCH'): {'delay': 1,
                                                 'dep_type': 'rmt_match'},
 ('ing_nexthop_ACTION', 'ing_system_acl_MATCH'): {'delay': 1,
                                                  'dep_type': 'rmt_match'},
 ('ing_nexthop_MATCH', 'ing_nexthop_ACTION'): {'delay': 9,
                                               'dep_type': 'new_match_to_action'},
 ('ing_port_vlan_mapping_ACTION', '_condition_ing_2'): {'delay': 1,
                                                        'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', '_condition_ing_23'): {'delay': 1,
                                                         'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', '_condition_ing_26'): {'delay': 1,
                                                         'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', '_condition_ing_27'): {'delay': 1,
                                                         'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', '_condition_ing_37'): {'delay': 1,
                                                         'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', 'ing_bd_flood_MATCH'): {'delay': 1,
                                                          'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', 'ing_dmac_MATCH'): {'delay': 1,
                                                      'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', 'ing_ecmp_group_ACTION'): {'delay': 1,
                                                             'dep_type': 'rmt_action'},
 ('ing_port_vlan_mapping_ACTION', 'ing_fwd_result_MATCH'): {'delay': 1,
                                                            'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', 'ing_ingress_bd_stats_ACTION'): {'delay': 1,
                                                                   'dep_type': 'rmt_action'},
 ('ing_port_vlan_mapping_ACTION', 'ing_ip_acl_MATCH'): {'delay': 1,
                                                        'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', 'ing_ipsg_MATCH'): {'delay': 1,
                                                      'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', 'ing_ipv4_fib_MATCH'): {'delay': 1,
                                                          'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', 'ing_ipv4_fib_lpm_MATCH'): {'delay': 1,
                                                              'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', 'ing_ipv4_multicast_bridge_MATCH'): {'delay': 1,
                                                                       'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', 'ing_ipv4_multicast_bridge_star_g_MATCH'): {'delay': 1,
                                                                              'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', 'ing_ipv4_multicast_route_MATCH'): {'delay': 1,
                                                                      'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', 'ing_ipv4_multicast_route_star_g_MATCH'): {'delay': 1,
                                                                             'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', 'ing_ipv4_racl_MATCH'): {'delay': 1,
                                                           'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', 'ing_ipv4_urpf_MATCH'): {'delay': 1,
                                                           'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', 'ing_ipv4_urpf_lpm_MATCH'): {'delay': 1,
                                                               'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', 'ing_learn_notify_ACTION'): {'delay': 1,
                                                               'dep_type': 'rmt_action'},
 ('ing_port_vlan_mapping_ACTION', 'ing_mac_acl_MATCH'): {'delay': 1,
                                                         'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', 'ing_nat_dst_MATCH'): {'delay': 1,
                                                         'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', 'ing_nat_flow_MATCH'): {'delay': 1,
                                                          'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', 'ing_nat_src_MATCH'): {'delay': 1,
                                                         'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', 'ing_nat_twice_MATCH'): {'delay': 1,
                                                           'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', 'ing_nexthop_ACTION'): {'delay': 1,
                                                          'dep_type': 'rmt_action'},
 ('ing_port_vlan_mapping_ACTION', 'ing_rmac_MATCH'): {'delay': 1,
                                                      'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', 'ing_smac_MATCH'): {'delay': 1,
                                                      'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', 'ing_spanning_tree_MATCH'): {'delay': 1,
                                                               'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', 'ing_system_acl_MATCH'): {'delay': 1,
                                                            'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', 'ing_urpf_bd_MATCH'): {'delay': 1,
                                                         'dep_type': 'rmt_match'},
 ('ing_port_vlan_mapping_ACTION', 'ing_validate_packet_ACTION'): {'delay': 1,
                                                                  'dep_type': 'rmt_action'},
 ('ing_port_vlan_mapping_MATCH', 'ing_port_vlan_mapping_ACTION'): {'delay': 9,
                                                                   'dep_type': 'new_match_to_action'},
 ('ing_rmac_ACTION', 'ing_fwd_result_MATCH'): {'delay': 1,
                                               'dep_type': 'rmt_match'},
 ('ing_rmac_ACTION', 'ing_system_acl_MATCH'): {'delay': 1,
                                               'dep_type': 'rmt_match'},
 ('ing_rmac_MATCH', '_condition_ing_21'): {'delay': 9,
                                           'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('ing_rmac_MATCH', '_condition_ing_25'): {'delay': 9,
                                           'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('ing_rmac_MATCH', 'ing_rmac_ACTION'): {'delay': 9,
                                         'dep_type': 'new_match_to_action'},
 ('ing_smac_ACTION', 'ing_learn_notify_MATCH'): {'delay': 1,
                                                 'dep_type': 'rmt_match'},
 ('ing_smac_MATCH', 'ing_smac_ACTION'): {'delay': 9,
                                         'dep_type': 'new_match_to_action'},
 ('ing_spanning_tree_ACTION', 'ing_learn_notify_MATCH'): {'delay': 1,
                                                          'dep_type': 'rmt_match'},
 ('ing_spanning_tree_ACTION', 'ing_system_acl_MATCH'): {'delay': 1,
                                                        'dep_type': 'rmt_match'},
 ('ing_spanning_tree_MATCH', 'ing_spanning_tree_ACTION'): {'delay': 9,
                                                           'dep_type': 'new_match_to_action'},
 ('ing_storm_control_ACTION', 'ing_ip_acl_ACTION'): {'delay': 1,
                                                     'dep_type': 'rmt_action'},
 ('ing_storm_control_ACTION', 'ing_ipv4_racl_ACTION'): {'delay': 1,
                                                        'dep_type': 'rmt_action'},
 ('ing_storm_control_ACTION', 'ing_mac_acl_ACTION'): {'delay': 1,
                                                      'dep_type': 'rmt_action'},
 ('ing_storm_control_ACTION', 'ing_meter_action_MATCH'): {'delay': 1,
                                                          'dep_type': 'rmt_match'},
 ('ing_storm_control_ACTION', 'ing_meter_index_MATCH'): {'delay': 1,
                                                         'dep_type': 'rmt_match'},
 ('ing_storm_control_ACTION', 'ing_storm_control_stats_MATCH'): {'delay': 1,
                                                                 'dep_type': 'rmt_match'},
 ('ing_storm_control_ACTION', 'ing_validate_packet_ACTION'): {'delay': 0,
                                                              'dep_type': 'rmt_reverse_read'},
 ('ing_storm_control_MATCH', 'ing_storm_control_ACTION'): {'delay': 9,
                                                           'dep_type': 'new_match_to_action'},
 ('ing_storm_control_stats_MATCH', 'ing_storm_control_stats_ACTION'): {'delay': 9,
                                                                       'dep_type': 'new_match_to_action'},
 ('ing_switch_config_params_ACTION', 'ing_dmac_ACTION'): {'delay': 1,
                                                          'dep_type': 'rmt_action'},
 ('ing_switch_config_params_ACTION', 'ing_ecmp_group_ACTION'): {'delay': 1,
                                                                'dep_type': 'rmt_action'},
 ('ing_switch_config_params_ACTION', 'ing_fabric_ingress_dst_lkp_ACTION'): {'delay': 1,
                                                                            'dep_type': 'rmt_action'},
 ('ing_switch_config_params_ACTION', 'ing_fabric_lag_ACTION'): {'delay': 1,
                                                                'dep_type': 'rmt_action'},
 ('ing_switch_config_params_ACTION', 'ing_fwd_result_ACTION'): {'delay': 1,
                                                                'dep_type': 'rmt_action'},
 ('ing_switch_config_params_ACTION', 'ing_ip_acl_ACTION'): {'delay': 1,
                                                            'dep_type': 'rmt_action'},
 ('ing_switch_config_params_ACTION', 'ing_lag_group_ACTION'): {'delay': 1,
                                                               'dep_type': 'rmt_action'},
 ('ing_switch_config_params_ACTION', 'ing_mac_acl_ACTION'): {'delay': 1,
                                                             'dep_type': 'rmt_action'},
 ('ing_switch_config_params_ACTION', 'ing_nexthop_ACTION'): {'delay': 1,
                                                             'dep_type': 'rmt_action'},
 ('ing_switch_config_params_ACTION', 'ing_system_acl_MATCH'): {'delay': 1,
                                                               'dep_type': 'rmt_match'},
 ('ing_switch_config_params_MATCH', 'ing_switch_config_params_ACTION'): {'delay': 9,
                                                                         'dep_type': 'new_match_to_action'},
 ('ing_system_acl_MATCH', 'ing_system_acl_ACTION'): {'delay': 9,
                                                     'dep_type': 'new_match_to_action'},
 ('ing_traffic_class_ACTION', 'ing_system_acl_ACTION'): {'delay': 1,
                                                         'dep_type': 'rmt_action'},
 ('ing_traffic_class_MATCH', 'ing_traffic_class_ACTION'): {'delay': 9,
                                                           'dep_type': 'new_match_to_action'},
 ('ing_urpf_bd_ACTION', 'ing_system_acl_MATCH'): {'delay': 1,
                                                  'dep_type': 'rmt_match'},
 ('ing_urpf_bd_MATCH', 'ing_urpf_bd_ACTION'): {'delay': 9,
                                               'dep_type': 'new_match_to_action'},
 ('ing_validate_outer_ethernet_ACTION', '_condition_ing_13'): {'delay': 1,
                                                               'dep_type': 'rmt_match'},
 ('ing_validate_outer_ethernet_ACTION', '_condition_ing_40'): {'delay': 1,
                                                               'dep_type': 'rmt_match'},
 ('ing_validate_outer_ethernet_ACTION', 'ing_bd_flood_MATCH'): {'delay': 1,
                                                                'dep_type': 'rmt_match'},
 ('ing_validate_outer_ethernet_ACTION', 'ing_compute_ipv4_hashes_MATCH'): {'delay': 1,
                                                                           'dep_type': 'rmt_match'},
 ('ing_validate_outer_ethernet_ACTION', 'ing_compute_non_ip_hashes_MATCH'): {'delay': 1,
                                                                             'dep_type': 'rmt_match'},
 ('ing_validate_outer_ethernet_ACTION', 'ing_drop_stats_ACTION'): {'delay': 1,
                                                                   'dep_type': 'rmt_action'},
 ('ing_validate_outer_ethernet_ACTION', 'ing_fabric_ingress_dst_lkp_ACTION'): {'delay': 0,
                                                                               'dep_type': 'rmt_reverse_read'},
 ('ing_validate_outer_ethernet_ACTION', 'ing_fwd_result_ACTION'): {'delay': 1,
                                                                   'dep_type': 'rmt_action'},
 ('ing_validate_outer_ethernet_ACTION', 'ing_ingress_qos_map_pcp_MATCH'): {'delay': 1,
                                                                           'dep_type': 'rmt_match'},
 ('ing_validate_outer_ethernet_ACTION', 'ing_mac_acl_MATCH'): {'delay': 1,
                                                               'dep_type': 'rmt_match'},
 ('ing_validate_outer_ethernet_ACTION', 'ing_native_packet_over_fabric_ACTION'): {'delay': 1,
                                                                                  'dep_type': 'rmt_action'},
 ('ing_validate_outer_ethernet_ACTION', 'ing_storm_control_MATCH'): {'delay': 1,
                                                                     'dep_type': 'rmt_match'},
 ('ing_validate_outer_ethernet_ACTION', 'ing_system_acl_MATCH'): {'delay': 1,
                                                                  'dep_type': 'rmt_match'},
 ('ing_validate_outer_ethernet_ACTION', 'ing_validate_packet_ACTION'): {'delay': 1,
                                                                        'dep_type': 'rmt_action'},
 ('ing_validate_outer_ethernet_MATCH', '_condition_ing_0'): {'delay': 9,
                                                             'dep_type': 'new_successor_conditional_on_table_result_action_type'},
 ('ing_validate_outer_ethernet_MATCH', 'ing_validate_outer_ethernet_ACTION'): {'delay': 9,
                                                                               'dep_type': 'new_match_to_action'},
 ('ing_validate_outer_ipv4_packet_ACTION', '_condition_ing_13'): {'delay': 1,
                                                                  'dep_type': 'rmt_match'},
 ('ing_validate_outer_ipv4_packet_ACTION', '_condition_ing_16'): {'delay': 1,
                                                                  'dep_type': 'rmt_match'},
 ('ing_validate_outer_ipv4_packet_ACTION', '_condition_ing_19'): {'delay': 1,
                                                                  'dep_type': 'rmt_match'},
 ('ing_validate_outer_ipv4_packet_ACTION', '_condition_ing_21'): {'delay': 1,
                                                                  'dep_type': 'rmt_match'},
 ('ing_validate_outer_ipv4_packet_ACTION', '_condition_ing_26'): {'delay': 1,
                                                                  'dep_type': 'rmt_match'},
 ('ing_validate_outer_ipv4_packet_ACTION', '_condition_ing_40'): {'delay': 1,
                                                                  'dep_type': 'rmt_match'},
 ('ing_validate_outer_ipv4_packet_ACTION', 'ing_compute_ipv4_hashes_MATCH'): {'delay': 1,
                                                                              'dep_type': 'rmt_match'},
 ('ing_validate_outer_ipv4_packet_ACTION', 'ing_compute_non_ip_hashes_MATCH'): {'delay': 1,
                                                                                'dep_type': 'rmt_match'},
 ('ing_validate_outer_ipv4_packet_ACTION', 'ing_drop_stats_ACTION'): {'delay': 1,
                                                                      'dep_type': 'rmt_action'},
 ('ing_validate_outer_ipv4_packet_ACTION', 'ing_fwd_result_MATCH'): {'delay': 1,
                                                                     'dep_type': 'rmt_match'},
 ('ing_validate_outer_ipv4_packet_ACTION', 'ing_ingress_qos_map_dscp_MATCH'): {'delay': 1,
                                                                               'dep_type': 'rmt_match'},
 ('ing_validate_outer_ipv4_packet_ACTION', 'ing_system_acl_MATCH'): {'delay': 1,
                                                                     'dep_type': 'rmt_match'},
 ('ing_validate_outer_ipv4_packet_ACTION', 'ing_validate_packet_MATCH'): {'delay': 1,
                                                                          'dep_type': 'rmt_match'},
 ('ing_validate_outer_ipv4_packet_MATCH', 'ing_validate_outer_ipv4_packet_ACTION'): {'delay': 9,
                                                                                     'dep_type': 'new_match_to_action'},
 ('ing_validate_packet_ACTION', '_condition_ing_40'): {'delay': 1,
                                                       'dep_type': 'rmt_match'},
 ('ing_validate_packet_ACTION', 'ing_bd_flood_MATCH'): {'delay': 1,
                                                        'dep_type': 'rmt_match'},
 ('ing_validate_packet_ACTION', 'ing_compute_ipv4_hashes_MATCH'): {'delay': 1,
                                                                   'dep_type': 'rmt_match'},
 ('ing_validate_packet_ACTION', 'ing_compute_non_ip_hashes_MATCH'): {'delay': 1,
                                                                     'dep_type': 'rmt_match'},
 ('ing_validate_packet_ACTION', 'ing_drop_stats_ACTION'): {'delay': 1,
                                                           'dep_type': 'rmt_action'},
 ('ing_validate_packet_ACTION', 'ing_fwd_result_MATCH'): {'delay': 1,
                                                          'dep_type': 'rmt_match'},
 ('ing_validate_packet_ACTION', 'ing_ingress_bd_stats_ACTION'): {'delay': 1,
                                                                 'dep_type': 'rmt_action'},
 ('ing_validate_packet_ACTION', 'ing_system_acl_MATCH'): {'delay': 1,
                                                          'dep_type': 'rmt_match'},
 ('ing_validate_packet_MATCH', 'ing_validate_packet_ACTION'): {'delay': 9,
                                                               'dep_type': 'new_match_to_action'}}
